import type { CreatedGoal } from '../components/GoalBuilder';
import type { PlannedCardio } from '../components/CardioPlanBuilder';
import type { AdaptiveProfile,RunResult } from '../features/training/AdaptiveTrainingProvider';
import { LONG_RUN_MAX_SHARE } from '../features/training/aiPlanService';

export type RunEvent='Mile'|'5K'|'10K'|'Half Marathon'|'Marathon'|'HYROX'|'Custom Run';
export type EventProfile={event:RunEvent;distanceMeters:number;durationWeeks:number;qualityFocus:string;longRunPeak:number;surface:string;demands:string[]};
export type GeneratedSession={id:string;goal:string;event:RunEvent;role:'Quality'|'Easy'|'Long'|'Race specific'|'Test';title:string;phase:string;week:number;plan:PlannedCardio;rationale:string;placement:string;stress:'Low'|'Moderate'|'High';progression:string;scaleNotes:string[];status:'Scheduled'|'Reduced'|'Repeat'|'Deferred'};
export type AdaptiveInput={profile:AdaptiveProfile;history:RunResult[];week?:number;lowerBodyDays?:number[]};
const standardMeters:Record<Exclude<RunEvent,'HYROX'|'Custom Run'>,number>={Mile:1609.344,'5K':5000,'10K':10000,'Half Marathon':21097.5,Marathon:42195};
const fallbackProfile:AdaptiveProfile={weeklyMileage:12,longestRunMiles:4,runningDays:3,experience:'Recreational',readiness:82,sleepHours:7.5,soreness:2,injuryConstraint:false,strengthFatigue:'Moderate',environment:'Road',heatAdjusted:true,watchConnected:false,easyHrMin:135,easyHrMax:150,thresholdHrMin:165,thresholdHrMax:178};
const parseClock=(value?:string,hoursFirst=false)=>{if(!value)return 0;const clock=value.match(/\d+(?::\d+){0,2}/)?.[0]||'';const parts=clock.split(':').map(Number);if(parts.some(Number.isNaN))return 0;if(parts.length===3)return parts[0]*3600+parts[1]*60+parts[2];if(parts.length===2)return hoursFirst?parts[0]*3600+parts[1]*60:parts[0]*60+parts[1];return parts[0]||0};
const formatClock=(seconds:number,decimals=false)=>{if(seconds>=3600){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=Math.round(seconds%60);return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}const m=Math.floor(seconds/60);const s=seconds-m*60;return `${m}:${s.toFixed(decimals?1:0).padStart(decimals?4:2,'0')}`};
const milesFrom=(value:number,unit='miles')=>unit.startsWith('kilo')?value*.621371:unit.startsWith('meter')?value/1609.344:value;
const detectEvent=(goal:CreatedGoal):RunEvent|null=>{const text=`${goal.exercise} ${goal.title}`.toLowerCase();if(text.includes('hyrox'))return'HYROX';if(text.includes('marathon')&&!text.includes('half'))return'Marathon';if(text.includes('half'))return'Half Marathon';if(text.includes('10k'))return'10K';if(text.includes('5k'))return'5K';if(/\bmile\b/.test(text)&&!goal.eventTemplate)return'Mile';if(goal.eventTemplate==='custom-running-event')return'Custom Run';return null};
export function getEventProfile(goal:CreatedGoal):EventProfile|null{const event=detectEvent(goal);if(!event)return null;const customMiles=milesFrom(Number(goal.eventDistance)||5,goal.eventDistanceUnit);const distanceMeters=event==='HYROX'?8000:event==='Custom Run'?customMiles*1609.344:standardMeters[event];const durationWeeks=event==='Mile'?10:event==='5K'?10:event==='10K'?12:event==='Half Marathon'?14:event==='Marathon'?18:event==='HYROX'?12:distanceMeters>30000?18:distanceMeters>15000?14:12;const longRunPeak=event==='Mile'?6:event==='5K'?7:event==='10K'?10:event==='Half Marathon'?12:event==='Marathon'?20:event==='HYROX'?7:Math.max(6,Math.min(20,distanceMeters/1609.344*.75));const qualityFocus=event==='Mile'?'speed and speed endurance':event==='5K'?'VO₂-oriented intervals and threshold':event==='10K'?'threshold and race-pace stamina':event==='Half Marathon'?'aerobic durability and goal-pace blocks':event==='Marathon'?'durability, fueling, and marathon-pace work':event==='HYROX'?'compromised running and station transitions':'event-specific pace and aerobic durability';return{event,distanceMeters,durationWeeks,qualityFocus,longRunPeak,surface:goal.eventSurface||'Road',demands:[qualityFocus,`Peak long run about ${longRunPeak} mi`,`Plan horizon ${durationWeeks} weeks`,event==='HYROX'?'8 × 1 km separated by stations':'Easy volume supports the quality work']}};
const goalSeconds=(goal:CreatedGoal,event:RunEvent)=>parseClock(goal.target,event==='HYROX')||(event==='Mile'?420:event==='5K'?1500:event==='10K'?3300:event==='Half Marathon'?7200:event==='Marathon'?15000:5400);
const currentSeconds=(goal:CreatedGoal,event:RunEvent)=>parseClock(goal.current,event==='HYROX');
const equivalent=(seconds:number,fromMeters:number,toMeters:number)=>seconds*Math.pow(toMeters/fromMeters,1.06);
const splitAt=(seconds:number,distance:number,rep:number)=>formatClock(seconds*rep/distance,true);
const pacePerMile=(seconds:number,meters:number)=>formatClock(seconds*1609.344/meters);
const plan=(id:number,activity:string,structure:PlannedCardio['structure'],extra:Partial<PlannedCardio>):PlannedCardio=>({id,activity,structure,targetSource:'Goal generated',...extra});
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
function adaptiveState(input?:Partial<AdaptiveInput>){const history=input?.history||[];const ordered=history.slice().sort((a,b)=>b.date.localeCompare(a.date));const anchor=ordered[0]?new Date(ordered[0].date).getTime():Date.now();const rolling=ordered.filter(run=>anchor-new Date(run.date).getTime()<=28*86400000);const observedWeekly=rolling.reduce((sum,run)=>sum+run.distanceMiles,0)/4;const observedLongest=rolling.reduce((max,run)=>Math.max(max,run.distanceMiles),0);const profile={...fallbackProfile,...input?.profile,...(rolling.length>=3?{weeklyMileage:Number(observedWeekly.toFixed(1)),longestRunMiles:Number(observedLongest.toFixed(1))}:{})};const recent=ordered.slice(0,4);const failed=recent.some(run=>!run.completed||(run.plannedReps&&Number(run.completedReps)<run.plannedReps*.8));const poorRecovery=(profile.watchConnected&&(profile.readiness<60||profile.sleepHours<6||profile.soreness>=4))||profile.injuryConstraint;const fatigue=profile.strengthFatigue==='High';const experienceScale={New:.72,Recreational:.88,Experienced:1,Competitive:1.08}[profile.experience];const capacityScale=clamp(profile.weeklyMileage/20,.6,1.15);const reduction=poorRecovery?.65:failed?.82:fatigue?.88:1;return{profile,history,failed,poorRecovery,fatigue,volumeScale:experienceScale*capacityScale*reduction,status:poorRecovery?'Reduced':failed?'Repeat':'Scheduled' as GeneratedSession['status']}};
function daysTo(date:string){return Math.ceil((new Date(date).getTime()-Date.now())/86400000)}
export function getCurrentPlanWeek(goal:CreatedGoal){const profile=getEventProfile(goal);if(!profile)return 1;return clamp(profile.durationWeeks-Math.ceil(Math.max(0,daysTo(goal.date))/7)+1,1,profile.durationWeeks)}
function phaseFor(goal:CreatedGoal,week:number,duration:number){const remaining=daysTo(goal.date);if(remaining<=14)return'Taper & race';const ratio=week/duration;return ratio<.3?'Foundation':ratio<.7?'Build':ratio<.9?'Specific':'Taper & test'}
function terrainPace(profile:AdaptiveProfile){const heat=profile.heatAdjusted?'heat-adjusted when conditions require':'';const terrain=profile.environment==='Road'?'':`${profile.environment.toLowerCase()} effort-adjusted`;return[terrain,heat].filter(Boolean).join(' · ')}
function bestEquivalent5k(history:RunResult[]){return history.filter(run=>run.completed&&run.distanceMiles>0&&run.durationMinutes>0).reduce((fastest,run)=>{const projected=run.durationMinutes*60*Math.pow(3.10686/run.distanceMiles,1.06);return fastest===0||projected<fastest?projected:fastest},0)}

export function generateGoalSessions(goal:CreatedGoal,week=1,input?:Partial<AdaptiveInput>):GeneratedSession[]{
  if(week<=0)week=getCurrentPlanWeek(goal);
  const eventProfile=getEventProfile(goal);if(!eventProfile)return[];const state=adaptiveState({...input,week});const p=state.profile;const event=eventProfile.event;const w=clamp(week,1,eventProfile.durationWeeks);const phase=phaseFor(goal,w,eventProfile.durationWeeks);const target=goalSeconds(goal,event);const current=currentSeconds(goal,event);const distance=eventProfile.distanceMeters;const runBaseline5k=bestEquivalent5k(state.history);const current5k=event==='HYROX'?runBaseline5k:equivalent(current,distance,5000);const thresholdPace=current5k?pacePerMile(equivalent(current5k,5000,10000)*.98,10000):'controlled threshold effort';const easyPace=current5k?pacePerMile(current5k*1.38,5000):'conversational';const scaleNotes=[`${p.experience} runner · ${p.runningDays} available days`,`${p.weeklyMileage} mi/week · ${p.longestRunMiles} mi current long run`,`${p.readiness}% readiness · ${p.strengthFatigue.toLowerCase()} strength fatigue`,p.watchConnected?`Watch zones: easy ${p.easyHrMin}–${p.easyHrMax} bpm`:'Conversational and goal-pace guidance until a watch is connected',event==='HYROX'&&!runBaseline5k?'No run pace inferred until a completed run establishes a baseline':'',terrainPace(p)].filter(Boolean);const common={goal:goal.title,event,phase,week:w,scaleNotes,status:state.status} as const;const qualityScale=state.status==='Repeat'?.85:state.volumeScale;const repCount=(base:number)=>Math.max(3,Math.round(base*qualityScale));const easyMinutes=Math.round(clamp((24+p.weeklyMileage*.7+w*1.5)*state.volumeScale,20,70));const placement=state.poorRecovery?'Recovery constraint active: replace hard running with easy movement or rest.':state.fatigue?'Keep at least 48 hours from heavy lower-body strength.':'Place on the freshest Forge-authorized day, ideally 48 hours from another hard session.';
  if(event==='Mile'){
    const ladder=[200,300,400,400,600,600,800,800,1000,1609];const rep=ladder[Math.min(w-1,ladder.length-1)];const test=rep===1609;const reps=test?1:repCount(Math.round((1500+w*100)/rep));return[
      {...common,id:`mile-${w}-quality`,role:test?'Test':'Quality',title:test?'Mile readiness test':`${reps} × ${rep} m at goal-mile pace`,stress:state.poorRecovery?'Low':'High',placement,progression:state.failed?'The last quality session was missed or incomplete, so Forge repeats a reduced step.':`Rep length progresses only after successful completion; week ${w} of ${eventProfile.durationWeeks}.`,rationale:`Target ${splitAt(target,distance,rep)} per rep, reduced by current durability and recovery when necessary.`,plan:plan(100+w,'Run','Intervals',{intervalBasis:'Distance',repeats:String(reps),workDistance:String(rep),workUnit:'meters',pace:`${splitAt(target,distance,rep)} per rep`,rest:String(rep<=300?60:rep<=600?120:180),recoveryType:'Walk',warmup:'10–15 min + strides',cooldown:'10 min'})},
      {...common,id:`mile-${w}-easy`,role:'Easy',title:`${easyMinutes} min easy + strides`,stress:'Low',placement:'Use on a Forge-authorized day or after upper-body strength.',progression:'Duration grows only when recent completion and recovery remain stable.',rationale:current5k?`Current-ability pace about ${easyPace}/mi; ${p.watchConnected?`stay near ${p.easyHrMin}–${p.easyHrMax} bpm.`:'keep it conversational.'}`:`No completed run baseline exists, so Forge uses ${p.watchConnected?`${p.easyHrMin}–${p.easyHrMax} bpm`:'conversational effort'} instead of inventing a pace.`,plan:plan(200+w,'Run','Steady',{duration:String(easyMinutes),distanceUnit:'miles',pace:current5k?`${easyPace}/mi · conversational`:p.watchConnected?`${p.easyHrMin}–${p.easyHrMax} bpm`:'conversational effort'})}
    ];
  }
  if(event==='HYROX'){
    const rounds=Math.max(3,Math.min(8,Math.round((3+w/2)*state.volumeScale)));return[{...common,id:`hyrox-${w}`,role:'Race specific',title:`${rounds} × 1 km compromised running`,stress:state.poorRecovery?'Moderate':'High',placement,progression:'Rounds and station volume grow separately; a full simulation is reserved for the specific phase.',rationale:runBaseline5k?'Run guidance comes from completed running history; station volume scales separately with training volume and recovery.':'No running pace is inferred from HYROX finish time. Use a controlled effort or recorded heart-rate zones until a completed run establishes pace.',plan:plan(900+w,'Circuit','Circuit',{circuitFormat:'Rounds',rounds:String(rounds),roundRest:'90',stationEntries:[{id:1,kind:'Cardio',name:'Run',target:'1000',unit:'meters',rest:'15'},{id:2,kind:'Cardio',name:'SkiErg / Row',target:String(Math.round(700*state.volumeScale/50)*50),unit:'meters',rest:'45'}]})}];
  }
  const isLong=event==='Half Marathon'||event==='Marathon'||event==='Custom Run'&&distance>=15000;const repMeters=event==='5K'?400:event==='10K'?800:isLong?1609:600;const baseReps=event==='5K'?8:event==='10K'?6:isLong?3:6;const reps=repCount(baseReps);const goalPace=pacePerMile(target,distance);const weeklyCap=Math.max(2,p.weeklyMileage*LONG_RUN_MAX_SHARE);const durabilityCap=Math.max(2,p.longestRunMiles+(state.failed||state.poorRecovery?0:.75));const taper=phase.startsWith('Taper')?.72:1;const longMiles=Number(Math.min(eventProfile.longRunPeak,weeklyCap,durabilityCap)*taper).toFixed(1);const sessions:GeneratedSession[]=[
    {...common,id:`${event}-${w}-quality`,role:isLong?'Race specific':'Quality',title:`${reps} × ${repMeters===1609?'1 mi':`${repMeters} m`} at ${event} pace`,stress:state.poorRecovery?'Low':'High',placement,progression:state.failed?'Repeat the prior progression with 15% less work.':'Progress only after the athlete completes the prescribed work without excessive fade.',rationale:`Goal pace ${goalPace}/mi gives ${splitAt(target,distance,repMeters)} per repetition. Volume is scaled to ${p.weeklyMileage} mi/week.`,plan:plan(300+w,'Run','Intervals',{intervalBasis:'Distance',repeats:String(reps),workDistance:repMeters===1609?'1':String(repMeters),workUnit:repMeters===1609?'miles':'meters',pace:`${splitAt(target,distance,repMeters)} per rep`,rest:String(repMeters<=400?75:repMeters<=800?120:150),recoveryType:'Easy movement',warmup:'10–15 min + strides',cooldown:'10 min'})},
    {...common,id:`${event}-${w}-easy`,role:'Easy',title:`${easyMinutes} min easy`,stress:'Low',placement:'Fits between harder sessions and may follow upper-body strength.',progression:'Easy volume grows conservatively and is the first volume reduced during poor recovery.',rationale:current5k?`Approximately ${easyPace}/mi${p.watchConnected?` or ${p.easyHrMin}–${p.easyHrMax} bpm`:''}.`:`No completed run baseline exists; use ${p.watchConnected?`${p.easyHrMin}–${p.easyHrMax} bpm`:'conversational effort'} instead of a fabricated pace.`,plan:plan(500+w,'Run','Steady',{duration:String(easyMinutes),pace:current5k?`${easyPace}/mi · conversational`:p.watchConnected?`${p.easyHrMin}–${p.easyHrMax} bpm`:'conversational effort',distanceUnit:'miles'})}
  ];
  if(isLong)sessions.splice(1,0,{...common,id:`${event}-${w}-long`,role:'Long',title:`${longMiles} mi easy long run`,stress:state.poorRecovery?'Low':'Moderate',placement:'Place on a standalone or low-fatigue day, away from heavy lower body.',progression:'The long run is the week’s longest easy run. It is capped near 25–35% of weekly mileage, grows no more than current durability permits, and drops for cutback/taper or poor recovery.',rationale:`Current long run ${p.longestRunMiles} mi · weekly volume ${p.weeklyMileage} mi · event peak cap ${eventProfile.longRunPeak} mi.`,plan:plan(600+w,'Run','Steady',{distance:longMiles,distanceUnit:'miles',pace:current5k?`${easyPace}/mi · easy`:p.watchConnected?`${p.easyHrMin}–${p.easyHrMax} bpm`:'conversational effort',duration:current5k?String(Math.round(Number(longMiles)*parseClock(easyPace)/60)):''})});
  return sessions.slice(0,Math.max(2,p.runningDays));
}

export function buildWeeklyCardio(goals:CreatedGoal[],week=1,input?:Partial<AdaptiveInput>){const state=adaptiveState({...input,week});const candidates=goals.filter(goal=>goal.type==='Endurance').flatMap(goal=>generateGoalSessions(goal,week,input));const dated=(item:GeneratedSession)=>new Date(goals.find(goal=>goal.title===item.goal)?.date||'2999').getTime();const hard=candidates.filter(item=>['Quality','Race specific','Test'].includes(item.role)).sort((a,b)=>dated(a)-dated(b));const supportive=candidates.filter(item=>item.role==='Easy'||item.role==='Long').sort((a,b)=>dated(a)-dated(b));const hardLimit=state.poorRecovery?0:state.profile.runningDays<3?1:state.fatigue||state.failed?1:2;const totalLimit=Math.max(1,state.profile.runningDays);const scheduled=[...hard.slice(0,hardLimit),...supportive].slice(0,totalLimit);const scheduledIds=new Set(scheduled.map(item=>item.id));return{scheduled,deferred:candidates.filter(item=>!scheduledIds.has(item.id)).map(item=>({...item,status:'Deferred' as const})),rule:state.poorRecovery?'Recovery safeguard active: hard work is paused until readiness improves.':`Scheduled across ${state.profile.runningDays} available run days with ${hardLimit} quality session${hardLimit===1?'':'s'} maximum. Nearest event priority; compatible easy and long work support secondary goals.`,eventProfiles:goals.map(getEventProfile).filter(Boolean) as EventProfile[]}}
