import type { CreatedGoal } from '../components/GoalBuilder';import { getCurrentPlanWeek,getEventProfile } from './cardioEngine';
export type GoalRoadmap={goal:string;domain:string;deadline:string;weeksRemaining:number;phase:string;current:string;target:string;requiredRate:string;status:'On track'|'Aggressive'|'Baseline needed';checkpoints:string[]};
const number=(value?:string)=>Number(String(value||'').replace(/[^0-9.]/g,''))||0;
export function buildGoalRoadmaps(goals:CreatedGoal[]):GoalRoadmap[]{return goals.map(goal=>{
  const weeks=Math.max(1,Math.ceil((new Date(goal.date).getTime()-Date.now())/604800000));const current=number(goal.current),target=number(goal.target);
  if(goal.type==='Endurance'){const event=getEventProfile(goal);const week=getCurrentPlanWeek(goal);const phase=weeks<=2?'Taper & race':week<Math.max(2,(event?.durationWeeks||12)*.3)?'Foundation':week<(event?.durationWeeks||12)*.75?'Build':'Specific';return{goal:goal.title,domain:'Endurance',deadline:goal.date,weeksRemaining:weeks,phase,current:goal.current||'Needed',target:goal.target,requiredRate:'Recalculated from completed sessions and event pace',status:current&&target?'On track':'Baseline needed',checkpoints:['Establish repeatable baseline','Build sustainable volume','Add event-specific work','Reduce volume and test']}}
  if(goal.type==='Strength'){const weeklyGain=current&&target?(target-current)/weeks:0;const aggressive=current>0&&weeklyGain/current>.006;return{goal:goal.title,domain:'Strength',deadline:goal.date,weeksRemaining:weeks,phase:weeks<=2?'Peak':weeks<=6?'Specific strength':'Build',current:goal.current||'Needed',target:goal.target,requiredRate:current?`${weeklyGain.toFixed(1)} lb/week in real-1RM progress`:'Real 1RM baseline required',status:!current?'Baseline needed':aggressive?'Aggressive':'On track',checkpoints:['Build strength with repeatable top sets','Use calculated max in Insights','Log a real one-rep result','Reduce fatigue before the deadline']}}
  return{goal:goal.title,domain:'Body Composition',deadline:goal.date,weeksRemaining:weeks,phase:weeks<=2?'Assess':'Sustainable trend',current:goal.current||'Needed',target:goal.target,requiredRate:current&&target?`${(Math.abs(target-current)/weeks).toFixed(1)} per week`:'Baseline required',status:current?'On track':'Baseline needed',checkpoints:['Confirm baseline','Track rolling trend','Adjust only after sustained plateau','Assess at deadline']};
})}
