import { isDemoMode } from '../../lib/env';
import { canonicalLiftKey, splitDayKey } from '../../lib/liftAliases';
import { calculateEstimatedOneRepMax, repMaxCoefficient, weightForReps, PRESCRIPTION_REP_CAP, REP_MAX_CAP } from '../../lib/strength';
import { supabase } from '../../lib/supabase';
import { localDayIso } from '../../lib/time';
import { qualitySession, qualityPhaseFor, QUALITY_MAX_SHARE } from '../../lib/qualitySession';
import { peakConflict } from '../../lib/interference';
import { eventProfileFor } from '../../lib/eventProfile';
import type { PaceModel } from '../../lib/paceModel';
import { normalizePhase, phaseFor, type TrainingPhase } from '../../lib/trainingPhase';

/* A running week is a peak when it is the race itself, the sharpening before
   it, or the specific phase where the race-pace work lives. */
const runningPeaks = (phase: string | undefined) => {
  const resolvedPhase = normalizePhase(phase);
  return resolvedPhase === 'Race' || resolvedPhase === 'Taper' || resolvedPhase === 'Specific';
};

/* The AI program: an 8-week block generated by the forge-plan edge function
   from the athlete's goals, split, logged bests, and actual logged running.
   It is stored (Supabase + local cache) and the Plan tab renders FROM STORAGE;
   a new block generates silently when this one runs low or inputs change. */

/* hold is client-side only: when a goal lift lands on a max week twice (the
   split runs the same day twice a cycle), only ONE instance is the attempt —
   the other carries the double it falls back to. */
export type AiPlanTopSet = { splitDay: string; exercise: string; weight: number; reps: number; hold?: { weight: number; reps: number } };
export type AiPlanWeek = {
  /* Two vocabularies, because a stored block written by the planner speaks the
     old one and the resolver writes the new one. normalizePhase reads either;
     nothing in the app should write 'Base' or 'Peak' again. */
  week: number; phase: 'Base' | 'Build' | 'Peak' | 'Deload' | 'Taper' | 'Race' | 'Foundation' | 'Specific';
  mileage: number; longRunMiles: number; longRunPace: string; longRunDay: string;
  quality: string; qualityPace: string; qualityDay: string;
  easyDays: string[]; easyMinutes: number; easyPace: string;
  /* Miles for each entry in easyDays, derived so the week's parts add up to
     its stated mileage. Client-side: a stored plan predates this field. */
  easyRuns?: number[];
  topSets: AiPlanTopSet[]; note: string;
};
/* adjustmentNote: when the athlete asked for a change in their own words, the
   builder answers in one sentence saying what it did with the request — so a
   request that could not be honored says so instead of silently vanishing.
   Optional: a block generated before this field existed has none. */
export type AiPlan = { summary: string; easyPace: string; weeks: AiPlanWeek[]; adjustmentNote?: string };
/* saved: the athlete has approved this block. Forge rebuilds a plan on its own
   when the inputs move — new goal, changed split, a PR past the baseline — and
   that is right until someone is happy with the block they have. A saved plan
   is pinned: nothing replaces it except an explicit, confirmed refresh. */
/* adjustments: the athlete's own words for how this block should differ, kept
   with the block because it is a STANDING instruction. Forge rebuilds on its
   own when the inputs move, and a rebuild that quietly dropped "no running on
   Mondays" would be Forge undoing what it was asked to do. It rides along
   until the athlete edits it or regenerates without it. */
/* waveOffset: which rung of the 8/6/4/2/1 wave this block's FIRST week is.
   A block always used to open at 8 reps, so an athlete who had just finished a
   week of 8s and regenerated — for any reason at all — was handed another week
   of 8s and told the wave is fixed. It is fixed; where you ENTER it is not.
   The offset is read from what the athlete has actually logged, so a rebuild
   continues the wave instead of restarting it. */
export type StoredAiPlan = { plan: AiPlan; generatedAt: string; startDate: string; fingerprint: string; blockWeeks: number; saved?: boolean; savedAt?: string; adjustments?: string; waveOffset?: number };

const localKey = 'forge-ai-plan-v1';

/* Stable fingerprint of everything the program depends on. When it changes
   (goal edited, split day renamed, exercises remapped), the block regenerates. */
export const planFingerprint = (input: unknown) => {
  const text = JSON.stringify(input);
  let hash = 0;
  for (let index = 0; index < text.length; index++) { hash = ((hash << 5) - hash + text.charCodeAt(index)) | 0; }
  return String(hash);
};

const readLocal = (): StoredAiPlan | null => { try { return JSON.parse(localStorage.getItem(localKey) || 'null'); } catch { return null; } };
/* Synchronous cache read for surfaces (Today, Coach) that align to the plan. */
export const readLocalAiPlan = readLocal;
const writeLocal = (stored: StoredAiPlan) => { try { localStorage.setItem(localKey, JSON.stringify(stored)); } catch { /* full */ } };

export async function loadStoredAiPlan(hasUser: boolean): Promise<StoredAiPlan | null> {
  const local = readLocal();
  if (isDemoMode || !hasUser) return local;
  try {
    const { data } = await supabase.from('training_plans').select('payload,generated_at').maybeSingle();
    if (data?.payload) {
      const stored = data.payload as StoredAiPlan;
      writeLocal(stored);
      return stored;
    }
  } catch { /* fall back to local */ }
  return local;
}

export async function saveStoredAiPlan(stored: StoredAiPlan, hasUser: boolean): Promise<void> {
  writeLocal(stored);
  window.dispatchEvent(new Event('forge-ai-plan-changed'));
  if (isDemoMode || !hasUser) return;
  try {
    const { data: userData } = await supabase.auth.getUser();
    if (!userData.user) return;
    await supabase.from('training_plans').upsert({ owner_id: userData.user.id, payload: stored, horizon_weeks: stored.blockWeeks, generated_at: stored.generatedAt }, { onConflict: 'owner_id' });
    /* Every block is kept — regeneration never destroys the record of what
       the program used to prescribe. */
    await supabase.from('training_plan_history').insert({ owner_id: userData.user.id, payload: stored, generated_at: stored.generatedAt });
  } catch { /* local copy still stands */ }
}

export async function generateAiPlan(context: Record<string, unknown>): Promise<AiPlan> {
  const { data, error } = await supabase.functions.invoke('forge-plan', { body: { context } });
  if (error || !data?.plan?.weeks?.length) {
    let detail = 'The plan service did not return a program.';
    const response = (error as { context?: Response } | null)?.context;
    if (response) { try { const body = await response.clone().json(); if (typeof body?.error === 'string') detail = body.error; } catch { /* keep default */ } }
    throw new Error(detail);
  }
  return data.plan as AiPlan;
}

/* ── The 8/6/4/2 wave, shared by every surface ────────────────────────────
   Weeks cycle 8 → 6 → 4 → 2(max attempt). Weights always derive from the
   athlete's CURRENT best calculated max, so the plan reacts to what they
   actually log: beat a prescription and everything scales up; miss one and
   the wave holds steady instead of assuming progress. Max week attempts the
   PR + ~5-10 lb (2.5 kg steps for metric athletes). */
/* Preston's system: a 5-WEEK wave — 8, 6, 4, 2, then MAX WEEK (a true 1RM
   attempt). The running deload lands on the 2-rep week so the max attempt
   always follows a lighter week. */
/* THE LONG RUN IS A SHARE OF THE WEEK, and the share is stated once. The
   roadmap used a flat 35%, the event generator 32%, and the resolver this
   band — three long runs for one week, all on screen together. */
export const LONG_RUN_MIN_SHARE = 0.25;
export const LONG_RUN_MAX_SHARE = 0.35;
/* HOW FAST A LONG RUN MAY GROW, IN ONE PLACE.

   The roadmap grew it 0.3 mi a week from the athlete's lifetime longest; the
   week resolver allowed a mile a week from the longest it could see, recent
   runs included. Two rules for one number, so the roadmap and the program
   printed different long runs for the same week. A mile a week off the
   longest run Forge actually knows about, never below six — which is the
   distance at which "long run" starts meaning anything.

   AND AN ATHLETE WHO HAS LOGGED NOTHING IS NOT AN ATHLETE WITH NO LIMIT. This
   returned Infinity for them, on the theory that the share of the week was the
   only thing that should bind — and the share of the week, on a two-day
   runner with a thirty-mile ceiling, let the plan prescribe a fifteen-mile
   long run to somebody with no running on file at all. "We know nothing about
   this person" is the strongest possible argument for caution, not the
   absence of one. With no evidence the cap starts at six miles and grows a
   mile a week, exactly as it would for someone who had logged a six-miler. */
export const UNPROVEN_LONG_RUN_MILES = 6;
/* And an athlete who has logged NOTHING does not climb forever on the strength
   of weeks passing. Growth is earned by covering the distance: without a single
   logged run the cap starts at six miles, grows a mile a week like anyone
   else's, and stops at ten. Past that, log a run — which is the whole premise
   of the app, and the one place it was quietly making an exception. */
export const UNPROVEN_LONG_RUN_CEILING = 10;
export const longRunCap = (longestKnown: number, weekIndex: number) =>
  longestKnown > 0
    ? Math.max(6, longestKnown + 1 + Math.max(0, weekIndex))
    : Math.min(UNPROVEN_LONG_RUN_CEILING, UNPROVEN_LONG_RUN_MILES + Math.max(0, weekIndex));
export const WAVE_REPS = [8, 6, 4, 2, 1] as const;
export const WAVE_LENGTH = WAVE_REPS.length;
export const waveSlot = (weekIndex: number) => ({ reps: WAVE_REPS[weekIndex % WAVE_LENGTH], isMax: weekIndex % WAVE_LENGTH === WAVE_LENGTH - 1 });

/* THE BLOCK OWNS THE MAX WEEK. THE LIFT OWNS ITS RUNG.

   A lift's rung is counted in the sessions it has actually answered, which is
   right — lifts are trained at different rates and a fortnightly movement
   should not be dragged along by the calendar. But the 1 at the top of
   8/6/4/2/1 is not a rung like the others: it is a TEST, and a test is an
   event the block schedules, not something a lift wanders into because its own
   session count happened to land on five.

   Preston opened week 1 of a ten-week block to "Squat 520 x 1" under a banner
   reading "4-REP WEEK" — 45 lb over his tested single, on a lift that had not
   ramped at all, in a week the block had called a build week. Two clocks, and
   the dangerous one won.

   So an ordinary week walks each lift up its own ramp — 8, 6, 4, 2, and back
   to 8 — and no week but the block's max week ever asks for a single. */
export const RAMP_REPS = [8, 6, 4, 2] as const;
export const RAMP_LENGTH = RAMP_REPS.length;
export const rampReps = (rung: number) => RAMP_REPS[((Math.round(rung) % RAMP_LENGTH) + RAMP_LENGTH) % RAMP_LENGTH];
/* How many times a lift has to have been trained inside the block before it is
   allowed to test. A cold max is not a max, it is an injury with a number. */
export const EXPOSURES_BEFORE_MAX = 3;
/* HOW FAR A BLOCK MAY OUTRUN A TESTED SINGLE.

   A calculated max is an inference from rep work; a tested single is a fact.
   When they disagree the fact wins, and Preston's disagreed by a lot — an
   all-out 415 x 8 estimates 526 while the bar he had actually taken for one
   was 475. Every rung written off 526 was about a tenth too heavy, which is
   how a ten-week block opened by asking for 45 lb over his best ever single.

   So a lift with a tested single is written from a max no more than five
   percent past it. Rep work still moves the number — the single is re-tested
   every max week and the ceiling moves with it — but it moves a block at a
   time, not in one jump off an estimate. */
export const MAX_OVER_TESTED = 1.05;

/* THE MAX FORGE IS WILLING TO ACT ON, which is not always the one arithmetic
   produces. A calculated max is an inference from rep work and a generous one;
   a tested single is a fact. Where both exist the inference is held to five
   percent over the fact — the same bound the wave is written under, so
   anything asking "has this athlete passed what the block prescribes" compares
   like with like.

   Without a tested single there is nothing to hold it to and the calculation
   stands: an athlete who has put up 500 for a double has genuinely outrun a
   block topping out at 495, and saying otherwise would pin them to a program
   they have already beaten. */
export const provenMax = (calculated: number, tested: number) =>
  tested > 0 ? Math.min(calculated, tested * MAX_OVER_TESTED) : calculated;

/* A LIFT WITH NO GOAL ON IT IS NOT TRAINED LIKE ONE THAT HAS.

   The 8/6/4/2/1 wave exists to walk a lift up to a tested single. An accessory
   has no single to walk to — running it up the same wave spends heavy, risky
   sets on a movement nothing is being measured against, and it is why a
   non-goal lift used to end its wave on a heavy double it had no reason to
   take. Accessories run 12/10/8/6 instead: rep work, off the calculated max,
   and they advance PER SESSION on that lift rather than per calendar week,
   because an accessory trained once a fortnight should not be four rungs along
   because the block is four weeks old.

   The load climbs one plate step every fifth completed session, and the raise
   compounds — it stacks on the max it already raised, so 100 becomes 105 and
   then 110, not 105 twice. */
export const ACCESSORY_REPS = [12, 10, 8, 6] as const;
export const ACCESSORY_LENGTH = ACCESSORY_REPS.length;
export const ACCESSORY_SESSIONS_PER_RAISE = 5;
export const accessorySlot = (sessionIndex: number) => ({ reps: ACCESSORY_REPS[Math.max(0, sessionIndex) % ACCESSORY_LENGTH] });

/* AFTER THE THIRD MISS, THE PLAN STOPS ASKING. Forge writes one plate step
   over the athlete's own best set at a rep count and waits to be beaten. Wait
   forever and the same bar sits there every session with nothing behind it but
   optimism. Three failed attempts at a rep count and the prescription returns
   to the last load actually completed there — no step on top — until the
   athlete succeeds again, which clears the count. */
export const FAILURES_BEFORE_BACKOFF = 3;

/* WHEN A SET ANSWERS WHAT THE PLAN ASKED.

   The tolerance runs one way. Asked for two and got three is the set — an extra
   rep is not a different session, and there is no credit for it. Asked for two
   and got ONE is not the set: that is coming up short, which is what the
   three-miss back-off exists to answer. Asked for two and got eight is neither
   — that is a different session, and it is off script.

   This lives here, beside the wave, because it is a training rule and not a
   detail of how progression is counted. Everything that asks "did they do it"
   asks here. */
export const REP_TOLERANCE = 1;
export const answeredThePlan = (asked: number, did: number) => did >= asked && did <= asked + REP_TOLERANCE;

/* WHAT AN EMPTY CALENDAR CELL SAYS. Two screens draw the same week and each
   wrote its own version of this line, so a change to one silently disagreed
   with the other. It consumes an already-derived stress/kind rather than
   deciding for itself what a rest day is — that answer belongs to isRestDay. */
export const calendarEmptyState = (session: { stress?: string; kind?: string }): 'rest' | 'open' | undefined =>
  session.stress === 'Rest' ? 'rest' : session.kind === 'Flexible' ? 'open' : undefined;
/* Max week is a TRUE 1RM attempt — strength goals track Real 1RM, which only
   a 1-rep set can register. The attempt targets the current best + 5-10 lb
   (2.5 kg steps for metric athletes). */
/* A lift with a Real 1RM goal is the only one that MUST be tested: the goal
   cannot move without a logged single, so max week exists for it. Every other
   lift holds the heavy double instead of spending a testing session it does
   not owe. No single is offered — not as an option, not when there are no
   strength goals at all. An earlier version of this comment promised both,
   and the promise outlived the code by weeks; the athlete read it on the Plan
   tab and waited for an offer that never came. */
export function goalLiftNames(goals: Array<{ type?: string; metric?: string; exercise?: string }>): Set<string> {
  /* Canonical keys, not raw names: a "Squat" goal must claim a prescription
     written as "Back Squat" — same lift, older spelling. */
  return new Set(goals.filter(goal => goal.type === 'Strength' && goal.exercise).map(goal => canonicalLiftKey(String(goal.exercise))));
}

/* THE RULE, IN ONE PLACE: a tested one-rep max exists ONLY to move a goal
   forward. A lift the athlete holds a Real 1RM goal on is tested on max week.
   Every other lift — no matter how heavy, how central to the day, or whether
   any goal exists at all — is never tested and never offered a single. No
   goal on a day means that day recommends its mapped work at the wave's rep
   count, nothing more. There are no exceptions to fall back on. */
export const testsOneRepMax = (exercise: string, goalLifts: Set<string>): boolean =>
  goalLifts.has(canonicalLiftKey(exercise));

/* ONE DEFINITION OF A REST DAY. It was written five times — a regex on
   `type`, the same regex on `dayType`, "no muscles and no lifts and no
   cardio" in two providers, and a SQL trigger with no concept of rest at all.
   A day the athlete marked rest but attached cardio to read as REST on the
   Plan tab and as a CARDIO day on Today, so the week's miles were divided by
   a different number of days on each screen. Whatever the athlete called it
   wins, and it is decided here. */
export const isRestDay = (day: { name?: string; type?: string; dayType?: string }): boolean =>
  /rest/i.test(String(day?.type ?? day?.dayType ?? '')) || /^\s*rest\b/i.test(String(day?.name || ''));

/* THE BEST CALCULATED MAX PER LIFT, KEYED CANONICALLY. Three surfaces built
   this map and only two folded aliases, so a history holding "Squat 315x6"
   and "Back Squat 275x5" gave the Plan tab a 321 max and Today a 380 — the
   same lift, the same week, forty-five pounds apart on two screens. Every
   surface builds it here now. */
export function bestsFromHistory(
  records: Array<{ date?: string; topSets?: Array<{ lift?: string; weight?: number; reps?: number; calculatedMax?: number; completed?: boolean; prescribedReps?: number }> }>,
): { bests: Map<string, number>; singles: Map<string, number>; anchors: LiftAnchors; sessions: Map<string, number>; misses: Map<string, Map<number, number>>; lastAt: LiftAnchors } {
  const bests = new Map<string, number>();
  const singles = new Map<string, number>();
  /* HOW MANY TIMES THIS LIFT HAS BEEN TRAINED, counted in days rather than in
     sets, so three sets of the same lift on one day is one session. This is
     what moves an accessory along its 12/10/8/6 cycle. */
  const sessionDays = new Map<string, Set<string>>();
  /* FAILURES SINCE THE LAST SUCCESS, per rep count. Records arrive newest
     first, so a completed set at a rep count stops the count for it: anything
     older than the athlete's last success there is history they have already
     answered. */
  const misses = new Map<string, Map<number, number>>();
  const settled = new Set<string>();
  /* THE LAST LOAD ACTUALLY COMPLETED AT EACH REP COUNT — the most recent one,
     not the heaviest. This is what a rung falls back to after three misses:
     "go back to the last successful 8" means the 8 the athlete really did, and
     if their heaviest 8 was a one-off from months ago that is not where the
     plan should restart them. */
  const lastAt: LiftAnchors = new Map();
  const lastOn = new Map<string, string>();
  /* THE HEAVIEST SET AT EACH REP COUNT, kept as itself. A single number per
     lift means every week of the wave is an extrapolation from one set —
     usually the athlete's best high-rep set, because that is what estimates
     highest — and the further the extrapolation travels the more wrong it
     gets. Held per rep count, the heavy weeks can be written from heavy
     evidence and the rep weeks from rep evidence. */
  const anchors: LiftAnchors = new Map();
  /* NEWEST FIRST, WHATEVER THE CALLER HANDED OVER. The failure count is
     "in a row", which only means anything walking backwards from today — a
     caller passing an oldest-first list would have counted misses the athlete
     has since answered. */
  const ordered = [...records].every(record => record.date)
    ? [...records].sort((a, b) => String(b.date).localeCompare(String(a.date)))
    : records;
  ordered.forEach((record, order) => (record.topSets || []).forEach(set => {
    if (!set.lift || !set.weight || !set.reps) return;
    const key = canonicalLiftKey(set.lift);
    /* A MISS BELONGS TO THE REP COUNT THAT WAS ASKED FOR, not the one the
       athlete managed. Asked for a double and got a single is a miss at the
       DOUBLE, and the double is the load the back-off has to drop. A set with
       no prescription behind it answers for itself, which is what this did
       before prescriptions were recorded. */
    const askedReps = set.prescribedReps || set.reps;
    const repSlot = Math.min(Math.max(Math.round(askedReps), 1), PRESCRIPTION_REP_CAP);
    const settledKey = `${key}|${repSlot}`;
    const cameUpShort = Boolean(set.prescribedReps) && !answeredThePlan(set.prescribedReps!, set.reps) && set.reps < set.prescribedReps!;
    if (set.completed === false || cameUpShort) {
      if (!settled.has(settledKey)) {
        const byReps = misses.get(key) || new Map<number, number>();
        byReps.set(repSlot, (byReps.get(repSlot) || 0) + 1);
        misses.set(key, byReps);
      }
      return;
    }
    settled.add(settledKey);
    const dayKey = record.date || `#${order}`;
    /* Walking newest first, the first completed set at a rep count is the
       latest one — later records only replace it if their date is genuinely
       newer, which covers a caller that has not sorted. */
    const stamp = record.date || '';
    const seenOn = lastOn.get(settledKey);
    if (seenOn === undefined || stamp > seenOn) {
      lastOn.set(settledKey, stamp);
      const byRepsLast = lastAt.get(key) || new Map<number, number>();
      byRepsLast.set(repSlot, set.weight);
      lastAt.set(key, byRepsLast);
    }
    const days = sessionDays.get(key) || new Set<string>();
    days.add(dayKey);
    sessionDays.set(key, days);
    const max = set.calculatedMax || calculateEstimatedOneRepMax(set.weight, set.reps) || 0;
    if (max > (bests.get(key) || 0)) bests.set(key, max);
    /* A real single is the only evidence a Real 1RM goal accepts. */
    if (set.reps === 1 && set.weight > (singles.get(key) || 0)) singles.set(key, set.weight);
    const reps = Math.min(Math.max(Math.round(set.reps), 1), 10);
    const byReps = anchors.get(key) || new Map<number, number>();
    if (set.weight > (byReps.get(reps) || 0)) byReps.set(reps, set.weight);
    anchors.set(key, byReps);
  }));
  const sessions = new Map([...sessionDays].map(([key, days]) => [key, days.size] as const));
  return { bests, singles, anchors, sessions, misses, lastAt };
}

/* Every lift's heaviest set at each rep count, 1-10. */
export type LiftAnchors = Map<string, Map<number, number>>;

/* WHAT THIS LIFT IS WORTH AT N REPS, from the evidence nearest to N reps.
   Each anchor is converted to N through the shared curve and the conversions
   are averaged by how far each had to travel, so a set at N reps decides it
   outright and a set six reps away barely gets a vote. The athlete's own set
   at N reps is a floor — evidence beats arithmetic — but never a ceiling, so
   an old light set at that rep count cannot hold back a lifter whose other
   work has moved on. With no anchors at all the calculated max stands in,
   which is exactly the old behaviour.

   AND IT ASKS FOR ONE STEP MORE. A plan built purely from evidence prescribes
   exactly what the athlete has already done and waits to be beaten — it
   mirrors them instead of moving them. Coming back to a rep count you have
   trained, the bar carries one more plate step than last time. Hit it and the
   floor rises with you; miss it and the set you did still stands, so the next
   time asks for the same thing rather than running away. */
export function loadFromAnchors(anchors: Map<number, number> | undefined, best: number, reps: number, step = 0): number {
  if (!anchors?.size) return weightForReps(best, reps);
  /* A SET THAT PROVES NOTHING NEW IS NOT EVIDENCE. Anyone who has done
     455 x 3 could have done 405 x 2, so an old 405 x 2 carries no information
     about this athlete — but it sits one rep from the double and would
     otherwise get the loudest vote in writing it. An anchor beaten outright
     by another (at least as many reps, at least as much weight) is dropped. */
  const live = [...anchors].filter(([at, weight]) =>
    ![...anchors].some(([other, heavier]) => other >= at && heavier >= weight && (other > at || heavier > weight)));
  let numerator = 0; let denominator = 0;
  live.forEach(([at, weight]) => {
    if (at === reps) return;
    const distance = Math.abs(at - reps);
    numerator += (weight * repMaxCoefficient(at) / repMaxCoefficient(reps)) / distance;
    denominator += 1 / distance;
  });
  const implied = denominator ? numerator / denominator : 0;
  const done = live.find(([at]) => at === reps)?.[1] || 0;
  return Math.max(done ? done + step : 0, implied);
}

/* RUNNING VOLUME AND RUN DAYS BELONG TO THE ATHLETE, NOT THE MODEL. The
   generator is told to use every stated running day and to stay inside the
   stated weekly-mileage range; it does not always comply. Preston runs 7 days
   a week with a 14-mile floor and got a block with easyDays: [] and 11.1
   miles — two running days, so most split days showed no cardio at all.
   Asking is not enforcing, so the week is corrected here, on the way to the
   screen: mileage clamped into range, and easy runs filled onto the split
   days that are not already carrying the long run or the quality session.
   Applied at render as well as at generation, so a block already stored on a
   device heals without being regenerated. */
export type SplitDayRef = { name: string; type?: string; dayType?: string; exercises?: string[] };
const paceToMinutes = (pace?: string): number => {
  const match = String(pace || '').match(/(\d+):(\d{2})/);
  return match ? Number(match[1]) + Number(match[2]) / 60 : 0;
};
/* recentWeeklyMileage / recentLongestRun: WHAT THE ATHLETE HAS ACTUALLY BEEN
   RUNNING, as opposed to what they typed into setup once. The plan was built
   from the stated number alone, so an athlete running more than they said —
   which is most people a month in — got a block pitched below their own
   training. Preston's week asked for 1.5-mile easy runs and a 4.2-mile long run
   while he was running five-mile long runs every week. A plan under the
   athlete's current level cannot drive an adaptation; it is a taper with a
   block's name on it. */
export type RunningAthlete = { runningDays?: number; minWeeklyMileage?: number; maxWeeklyMileage?: number; weeklyMileage?: number; longestRunMiles?: number; recentWeeklyMileage?: number; recentLongestRun?: number;
  /* 0-100, from the watch or from what the athlete said this morning. Absent
     means nothing is known and the block stands as written. */
  readiness?: number;
  /* THE GOAL THE HARD RUN IS FOR. Seconds per mile at the athlete's goal pace,
     and the event's distance. Given them, the week's quality session is WRITTEN
     here from qualitySession rather than inherited from whatever prose the
     model produced — which is why a 5K build could reach the Plan tab with no
     threshold running anywhere in it. Absent, the stored text stands. */
  goalPaceSecondsPerMile?: number;
  goalMiles?: number;
  /* Every training pace, derived from the athlete's own demonstrated fitness.
     Given, the hard run is paced off what they have run; absent, off the goal,
     which is the only thing Forge used to have. */
  paces?: PaceModel };

const round1 = (value: number) => Math.round(value * 10) / 10;

/* Miles a quality session actually covers, including warm-up and cool-down.
   The model writes these as prose ("6 × 400 m", "3 × 1 mi (5.8 mi total with
   warm-up/cool-down)", "20 min threshold"), and the week cannot be balanced
   without turning that back into a number. */
export const qualitySessionMiles = (quality: string, paceMinutes: number): number => {
  const text = String(quality || '');
  if (!text || /no goal/i.test(text)) return 0;
  const stated = text.match(/([\d.]+)\s*(?:mi|miles)\s*total/i);
  if (stated) return round1(Number(stated[1]));
  const reps = text.match(/(\d+)\s*[x\u00d7]\s*([\d.]+)\s*(m|mi|mile|miles|km)\b/i);
  if (reps) {
    const unit = reps[3].toLowerCase();
    const each = unit === 'm' ? Number(reps[2]) / 1609.34 : unit === 'km' ? Number(reps[2]) * 0.621371 : Number(reps[2]);
    return round1(Number(reps[1]) * each + 2);
  }
  const minutes = text.match(/(\d+)\s*min/i);
  if (minutes) return round1(Number(minutes[1]) / (paceMinutes || 9.5) + 2);
  return 0;
};

/* THE WEEK'S RUNNING IS ARITHMETIC, NOT PROSE. Two things were wrong and they
   compounded: the model wrote ONE easyMinutes for every easy day, so four
   different days all read "45 min"; and nothing ever checked that the pieces
   summed to the week's stated mileage. A 15.5-mile week was really scheduling
   5 + 5.8 + 4 x 4.7 = 29.6 miles — double its own header and past the 25-mile
   ceiling the athlete set.

   So the volume is computed here instead: a weekly target that ramps from
   what the athlete currently runs toward their stated maximum (deload on each
   wave's 2-rep week), a long run held to a sane share of it, the quality
   session measured from its own description, and the remainder split across
   the easy days as DISTANCES at the athlete's easy pace. mileage is then set
   to what was actually scheduled, so the number on the card is the sum of the
   runs under it. */
export function resolveWeekRunning<T extends AiPlanWeek>(
  week: T,
  splitDays: SplitDayRef[],
  athlete: RunningAthlete,
  block?: { weekIndex?: number; blockWeeks?: number; waveIndex?: number; liftingMaxWeek?: boolean; weeksToRace?: number; weeksToLiftGoal?: number },
): T {
  const runningDays = Math.max(0, Math.min(7, Math.round(Number(athlete.runningDays) || 0)));
  const floorMiles = Number(athlete.minWeeklyMileage) || 0;
  const ceilingMiles = Number(athlete.maxWeeklyMileage) || 0;
  /* A block with no running at all is a strength-only block — leave it. */
  if (!runningDays || !(Number(week.mileage) || 0)) return week;

  /* THE PHASE IS COMPUTED, NOT READ OFF THE STORED BLOCK.

     The block is written by the planner and every week of Preston's came back
     labelled "Base" — week one Base, week six Base, all ten of them. Trusting
     that string meant the whole periodisation collapsed: a permanent Foundation
     phase, so the rotation alternated the same two sessions forever, the
     specific phase never arrived, race-pace work never appeared, and there was
     no taper because nothing was ever anything but Base.

     Everything needed to answer this properly is already here — which week it
     is, how long the block runs, when the race is, and what the race is. So it
     is answered here, by the one function that owns the question, and the
     stored label is only a fallback for a block with no goal attached to it. */
  const phaseWeekIndex = Math.max(0, Number(block?.weekIndex) || 0);
  const phaseWaveIndex = Math.max(0, Number(block?.waveIndex ?? block?.weekIndex) || 0);
  const phaseBlockWeeks = Math.max(1, Number(block?.blockWeeks) || 10);
  const goalPaceForPhase = Math.max(0, Number(athlete.goalPaceSecondsPerMile) || 0);
  const storedPhase = normalizePhase(week.phase);
  const knowsRaceDate = typeof block?.weeksToRace === 'number' && Number.isFinite(block.weeksToRace);
  const computedPhase: TrainingPhase = goalPaceForPhase
    ? phaseFor({
        weekIndex: phaseWeekIndex,
        blockWeeks: phaseBlockWeeks,
        weeksToRace: knowsRaceDate ? block!.weeksToRace : undefined,
        deloading: phaseWaveIndex % 5 === 3,
        shape: eventProfileFor(Number(athlete.goalMiles) || undefined).shape,
      })
    : storedPhase;
  /* WITH ONE EXCEPTION, AND IT MATTERS. Taper and race week are the only two
     phases that are statements about a DATE rather than about a position in
     the block, and a caller that does not know when the race is cannot compute
     them — the daily screen is one such caller. Overwriting a stored "Race"
     because we happen not to have the date to hand would turn somebody's race
     day into an ordinary Tuesday. Where the date is known the computed answer
     wins outright; where it is not, an explicit Race or Taper stands. */
  const phase: TrainingPhase = !knowsRaceDate && (storedPhase === 'Race' || storedPhase === 'Taper')
    ? storedPhase
    : computedPhase;

  /* Which days run: the plan's long run and quality keep their days, and the
     rest of the athlete's stated run days are easy, never a rest day. */
  const isRest = (day: SplitDayRef) => isRestDay(day);
  /* A run only counts toward the week if its day is actually in the week. On a
     rolling cycle that is not 7 days long the days rotate, so the long run can
     sit outside a given week — counting it there is what made the header claim
     miles the schedule never showed. */
  const present = (name?: string) => Boolean(name) && splitDays.some(day => day.name === name);
  /* The race is the long run. Scheduling another one in the same seven days is
     how an athlete arrives at the start line already tired. */
  const raceWeek = phase === 'Race' && goalPaceForPhase > 0;
  const hasLong = !raceWeek && Number(week.longRunMiles) > 0 && present(week.longRunDay);
  const goalPace = Math.max(0, Number(athlete.goalPaceSecondsPerMile) || 0);
  /* With a dated goal the hard run exists whatever the stored text says — a
     block generated before the athlete set the goal wrote "No goal-driven
     cardio" into every week, and that string must not outlive the goal. */
  const hasQuality = present(week.qualityDay)
    && (goalPace > 0 || (Boolean(week.quality) && !/no goal/i.test(week.quality)));
  /* AND A HARD SESSION IS A SHARE OF THE DAYS THERE ARE. Thirty percent of the
     week is the right size on five running days and an impossible target on
     two, where the long run and one other run ARE the week — so the cap was
     silently sizing every session against a week that did not exist.

     The first fix tried was a three-day minimum before any quality session at
     all. That is defensible coaching and it was wrong here: most of the people
     using Forge run twice a week, and it would have removed their hard run
     entirely rather than sizing it. One long run and one quality session is a
     real minimalist week; what was broken was the arithmetic, not the plan. */
  const qualityShare = runningDays ? Math.max(QUALITY_MAX_SHARE, Math.min(0.45, 0.95 / runningDays)) : QUALITY_MAX_SHARE;
  const taken = new Set([hasLong ? week.longRunDay : '', hasQuality ? week.qualityDay : ''].filter(Boolean));
  /* A CANCELLED HARD RUN LEAVES A RUN BEHIND. When the check-in takes the
     quality session off, or the max attempt owns the week, that day does not
     stop existing — it becomes easy running. Folding it into nothing left a
     two-day athlete with the long run as their entire week, which is the
     opposite of what backing off is supposed to achieve. */
  const qualityStands = hasQuality && !(typeof athlete.readiness === 'number' && athlete.readiness < 55) ;
  const needed = Math.max(0, runningDays - (hasLong ? 1 : 0) - (qualityStands ? 1 : 0));
  const kept = (week.easyDays || []).filter(name => splitDays.some(day => day.name === name) && !taken.has(name));
  const fill = splitDays.filter(day => !isRest(day) && !taken.has(day.name) && !kept.includes(day.name)).map(day => day.name);
  const easyDays = [...kept, ...fill].slice(0, needed);

  /* The weekly target: start from what they actually run now and climb toward
     the ceiling they set, so a block finishes at the top of their range
     instead of hovering near the floor. Every wave's 2-rep week deloads. */
  const weekIndex = Math.max(0, Number(block?.weekIndex) || 0);
  /* The running deload lands on the wave's 2-rep week, so it follows the wave
     rather than the calendar when the block entered the wave mid-way. */
  const deloadIndex = Math.max(0, Number(block?.waveIndex ?? block?.weekIndex) || 0);
  const blockWeeks = Math.max(1, Number(block?.blockWeeks) || 10);
  const DELOAD_SHARE = 0.8;
  /* Shake-out running around the event, and nothing more. */
  const RACE_WEEK_EASY_MILES = 4;
  const TAPER_FIRST_SHARE = 0.68;
  const TAPER_LAST_SHARE = 0.5;
  const TAPER_LONG_SHARE = 0.6;
  const TAPER_WEEKS_BEFORE_RACE = 2;
  /* What a non-long run is worth, relative to the long one. */
  const OTHER_RUN_SHARE = 0.6;
  const WEEK_ON_WEEK_MAX = 1.2;
  const clampMiles = (value: number) => {
    const high = ceilingMiles ? Math.min(value, ceilingMiles) : value;
    return floorMiles ? Math.max(high, floorMiles) : high;
  };
  /* THE FLOOR IS WHAT THEY ARE ALREADY DOING. Stated mileage is a starting
     guess that goes stale the week after setup; the last few weeks of real
     running is not. The ceiling still holds — an athlete who has capped
     themselves at 25 is not handed 30 — but nothing below their own training
     gets prescribed as progress. */
  const actualMiles = Number(athlete.recentWeeklyMileage) || 0;
  const startMiles = clampMiles(Math.max(Number(athlete.weeklyMileage) || floorMiles || Number(week.mileage) || 0, actualMiles));
  const progress = blockWeeks > 1 ? Math.min(1, weekIndex / (blockWeeks - 1)) : 0;
  /* A SHORT HORIZON DOES NOT LICENSE A BIG JUMP. Dividing the whole climb by
     however many weeks are left asked an athlete on twelve miles for sixty in
     six weeks — a straight line to the ceiling, +50% a week, which is how
     people get stress fractures. Volume is rate-limited to ten percent a week
     off the real starting mileage whatever the curve wants; the roadmap has
     always done this and the block never did. */
  const smooth = ceilingMiles ? startMiles + (ceilingMiles - startMiles) * progress : startMiles;
  const climb = Math.min(smooth, Math.max(startMiles, startMiles * Math.pow(1.1, weekIndex)));
  /* THE MODEL'S WEEKLY NUMBER IS HONORED WHEN IT IS SANE. The athlete can ask
     the coach for a specific progression — "add 5 miles a week until 40" — and
     the model writes exactly that into each week. Overwriting it with our own
     linear climb silently undid the one thing they asked for. So the model's
     weekly mileage stands when it sits inside the athlete's stated bounds and
     within a humane ramp of the current baseline (+6 mi or +40% per week over
     the start, whichever is larger); anything wilder falls back to the climb. */
  const modelMiles = Number(week.mileage) || 0;
  const rampCap = startMiles + Math.max(6, startMiles * 0.4) * (weekIndex + 1);
  const modelSane = modelMiles > 0
    && (!ceilingMiles || modelMiles <= ceilingMiles + 1e-9)
    && (!floorMiles || modelMiles >= Math.min(floorMiles, startMiles) - 1e-9)
    && modelMiles <= rampCap;
  /* AND THE FLOOR BINDS WHICHEVER NUMBER WON. The model's weekly mileage is
     honoured when it is sane, and "sane" said nothing about whether it was
     above the athlete's own training — so a block written for 14 miles stood
     over someone running 18. The chosen number is raised to what they actually
     run, still under their own ceiling. A deload is measured from there and is
     allowed to be a deload. */
  /* A WEEK CANNOT HOLD MORE THAN ITS DAYS CAN CARRY. The ceiling an athlete
     types is a statement about how much they are willing to run; it is not a
     statement that they can run it in two sessions. A thirty-mile cap on two
     running days had the engine reaching for fifteen-mile runs twice a week
     from someone with no running on file — every individual rule respected,
     and the result nonsense.

     Capacity is the long run plus the other days at a realistic share of it.
     Where that is less than the athlete's own ceiling, capacity wins: the
     honest answer to "I want 30 miles on 2 days" is a smaller number, not a
     pair of half marathons. */
  const longestKnownForCapacity = Math.max(Number(athlete.longestRunMiles) || 0, Number(athlete.recentLongestRun) || 0);
  const singleRunCap = longRunCap(longestKnownForCapacity, weekIndex);
  const capacity = runningDays > 0
    ? singleRunCap + Math.max(0, runningDays - 1) * singleRunCap * OTHER_RUN_SHARE
    : Infinity;
  /* A DELOAD IS MEASURED AGAINST THE WEEK BEFORE IT, not against its own place
     on the climb. Taking 80% of a still-rising curve produced deload weeks
     HEAVIER than the week they were supposed to be a recovery from — the
     athlete saw a lighter label on a bigger number. The previous week's target
     is recomputed here rather than remembered, so a week drawn on its own
     still knows what it is stepping down from. */
  const climbAt = (index: number) => {
    const share = blockWeeks > 1 ? Math.min(1, Math.max(0, index) / (blockWeeks - 1)) : 0;
    const line = ceilingMiles ? startMiles + (ceilingMiles - startMiles) * share : startMiles;
    return clampMiles(Math.max(Math.min(line, Math.max(startMiles, startMiles * Math.pow(1.1, Math.max(0, index)))), actualMiles));
  };
  const deloading = deloadIndex % 5 === 3;
  /* WHAT LAST WEEK ACTUALLY WAS, not where the climb had got to. The rate
     limit and the deload both measure against the previous week, and the
     previous week is not a point on a rising line: it may have been a taper, a
     deload, or the race itself. Measured against the line, an athlete's volume
     doubled the Monday after their marathon — the curve had kept climbing
     while they raced. The same shaping is applied to the week before. */
  const away = (index: number) => (typeof block?.weeksToRace === 'number' ? block.weeksToRace - index : Number.NaN);
  const raceAt = typeof block?.weeksToRace === 'number' ? block.weeksToRace : Number.NaN;
  /* The volume the block had reached before it started tapering. It is the
     peak the taper steps down from, and the level training resumes at once the
     race is behind them. */
  const peakBefore = Number.isFinite(raceAt)
    ? climbAt(Math.max(0, raceAt - TAPER_WEEKS_BEFORE_RACE) - 1)
    : climbAt(Math.max(0, blockWeeks - 3));
  const shapedAt = (index: number) => {
    const gap = away(index);
    const line = climbAt(index);
    if (gap === 0 && Number(athlete.goalMiles)) return Number(athlete.goalMiles) + RACE_WEEK_EASY_MILES;
    /* AFTER THE RACE, training resumes where it left off rather than where the
       curve had wandered to while the athlete was tapering and racing. The
       first week back is a recovery week off that peak; after that the normal
       climb applies, and the week-on-week limit carries them up to it. */
    if (gap < 0) return Math.min(line, peakBefore * (gap === -1 ? DELOAD_SHARE : 1));
    if (gap > 0 && gap <= TAPER_WEEKS_BEFORE_RACE) return line * (gap <= 1 ? TAPER_LAST_SHARE : TAPER_FIRST_SHARE);
    return ((index + (deloadIndex - weekIndex)) % 5 + 5) % 5 === 3 ? line * DELOAD_SHARE : line;
  };
  /* AND THE CHAIN HAS TO BE CONSISTENT. Shaping one week back was not enough:
     week seven was held to six miles by the limit, and week eight then
     measured itself against an UNLIMITED week seven of twelve and doubled.
     Every week's ceiling depends on the ceiling of the week before it, so the
     series is walked forward from the start of the block. It is a handful of
     multiplications and it is the only way the numbers agree with each other. */
  const shapedSeries = (upTo: number) => {
    let last = startMiles;
    for (let index = 0; index <= upTo; index += 1) {
      const want = shapedAt(index);
      last = index === 0 ? want : Math.min(want, last * WEEK_ON_WEEK_MAX);
    }
    return last;
  };
  const previousWeek = weekIndex > 0 ? shapedSeries(weekIndex - 1) : startMiles;
  /* And the same ceiling applies to THIS week when it is after the race. */
  const postRaceCap = away(weekIndex) < 0 ? shapedAt(weekIndex) : Infinity;
  const chosen = Math.min(capacity, postRaceCap, clampMiles(Math.max(modelSane ? modelMiles : climb, actualMiles)));
  /* RACE WEEK IS THE RACE. An athlete who capped their training at eighteen
     miles a week and entered a half marathon was handed a week that tried to
     fit 13.1 miles inside a 30% share of eighteen — so the race was scheduled
     alongside a long run and a full week's easy running, and the header read
     nineteen miles for someone whose ceiling was eighteen.

     The ceiling is about TRAINING. It is not a statement that the athlete
     will not run the race they signed up for. So race week is built around
     the event instead: the race, a little easy running either side of it, no
     long run, and no ceiling — because the distance is not negotiable and
     pretending otherwise just produces a dishonest number. */
  const racing = phase === 'Race' && goalPace > 0;
  const raceMiles = racing ? Math.max(0, Number(athlete.goalMiles) || 0) : 0;
  /* A TAPER IS A VOLUME CUT. It is the only thing a taper is, and the engine
     did not have one — so the two weeks before a race came out HEAVIER than
     the block that built to them, because the climb kept climbing and the
     durability cap kept letting the long run grow. An athlete following that
     arrives at the start line having just run their biggest week.

     Two thirds, then half. The intensity stays (that is what the strides are
     for); the volume is what comes off, which is the whole mechanism by which
     a taper works. The floor does not apply — an athlete's minimum weekly
     mileage is a statement about training, and a taper is the deliberate
     exception to it. */
  const tapering = phase === 'Taper';
  const lastTaperWeek = typeof block?.weeksToRace === 'number'
    ? block.weeksToRace - weekIndex <= 1
    : weekIndex >= blockWeeks - 2;
  const taperShare = tapering ? (lastTaperWeek ? TAPER_LAST_SHARE : TAPER_FIRST_SHARE) : 1;
  /* AND IT STEPS DOWN FROM THE PEAK, not from wherever the climb had reached.
     Measured against the still-rising curve, the second taper week came out
     bigger than the first — a taper that went back up. The base is the last
     week before the taper began, for every taper week, so the steps can only
     descend. */
  const taperStart = typeof block?.weeksToRace === 'number'
    ? Math.max(0, block.weeksToRace - TAPER_WEEKS_BEFORE_RACE)
    : Math.max(0, blockWeeks - 1 - TAPER_WEEKS_BEFORE_RACE);
  const taperBase = tapering ? climbAt(taperStart - 1) : 0;
  const target = racing && raceMiles
    ? round1(raceMiles + RACE_WEEK_EASY_MILES)
    : tapering
      ? round1(Math.min(chosen, climb, previousWeek, taperBase) * taperShare)
      : clampMiles(round1(deloading ? Math.min(chosen, climb, previousWeek) * DELOAD_SHARE : chosen));

  /* THE WEEK'S REAL BUDGET, decided before anything is sized against it. The
     hard session and the long run were both measured against `target` and then
     the week was trimmed underneath them — so a session sized for a twelve-mile
     week ended up 58% of the seven-mile week it actually landed in. Everything
     downstream reads this number. */
  const rateLimit = weekIndex > 0 && !racing ? previousWeek * WEEK_ON_WEEK_MAX : Infinity;
  const budget = racing ? target : Math.min(target, ceilingMiles || Infinity, rateLimit);

  const pace = paceToMinutes(week.easyPace) || 9.5;
  /* The long run is a share of the week, not an independent number — and it is
     also capped by the body doing it: no plan hands an athlete whose longest
     run is 13.7 miles a 27-mile day. It may grow ~1 mile a week from their
     longest logged run; with no logged longest, the share caps alone hold. */
  const longestKnown = Math.max(Number(athlete.longestRunMiles) || 0, Number(athlete.recentLongestRun) || 0);
  /* And durability stops growing in a taper: a long-run personal best nine
     days before a race is not a taper, it is a race nobody entered. */
  const taperingNow = phase === 'Taper';
  const longCap = taperingNow
    ? longRunCap(longestKnown, Math.max(0, weekIndex - 2)) * TAPER_LONG_SHARE
    : longRunCap(longestKnown, weekIndex);
  /* A long run the athlete has already been doing is the floor for the long
     run, not a stretch goal — bounded by the week's volume, so it cannot eat
     the whole week on a deload. */
  /* AND THE SHARE DEPENDS ON HOW MANY DAYS THERE ARE TO SHARE IT WITH. A third
     of the week is the right long run on five running days and an impossible
     one on two, where the long run and one other run ARE the week. The cap
     opens as the days close in, so a two-day athlete gets a long run and an
     easy run rather than a long run that has to pretend to be short. */
  /* AND THE TWO SHARES HAVE TO FIT IN ONE WEEK. Opening the long run to 62%
     and the hard session to 47% on a two-day week let them total 109% of the
     target between them — every part respecting its own cap and the sum
     clearing the ceiling the athlete set. The long run yields, because the
     hard session is the one that has to be a specific size to do its job. */
  const openLongShare = Math.max(LONG_RUN_MAX_SHARE, runningDays ? Math.min(0.65, 1.25 / runningDays) : LONG_RUN_MAX_SHARE);
  const maxLongShare = Math.max(LONG_RUN_MIN_SHARE, Math.min(openLongShare, 1 - (hasQuality ? qualityShare : 0)));
  const longFloor = Math.min(Number(athlete.recentLongestRun) || 0, budget * maxLongShare);
  const longRunMiles = hasLong ? round1(Math.min(Math.max(Number(week.longRunMiles), budget * LONG_RUN_MIN_SHARE, longFloor), budget * maxLongShare, longCap)) : 0;
  /* A HARD SESSION ON A BODY THAT CANNOT ABSORB IT IS WORSE THAN NO SESSION.
     The block was written weeks ago and does not know how this morning went;
     the check-in does. Below 55 the hard run comes off and the miles stay as
     easy running — the week keeps its volume, it just stops asking for
     something the athlete has already said they do not have. */
  const cooked = typeof athlete.readiness === 'number' && athlete.readiness < 55;
  /* ONE FUNCTION DECIDES WHAT THE HARD RUN IS, on both paths. The roadmap has
     called qualitySession since it was written; the stored block never did, so
     threshold work existed in the preview and nowhere the athlete trains. */
  /* THE OTHER HALF OF ONE PEAK AT A TIME. When the max attempt owns the week,
     the hard run is the thing that gives way — and it gives way by becoming
     easy running, not by vanishing, so the week keeps its volume. */
  const yielding = peakConflict({
    liftingMaxWeek: Boolean(block?.liftingMaxWeek),
    runningPeakWeek: phase === 'Specific' || phase === 'Taper' || phase === 'Race',
    weeksToRace: block?.weeksToRace,
    weeksToLiftGoal: block?.weeksToLiftGoal,
  })?.owner === 'lifting';
  const written = goalPace && hasQuality && !yielding
    ? qualitySession({
        phase,
        weekIndex,
        goalPaceSecondsPerMile: goalPace,
        weeklyMiles: budget,
        maxShare: qualityShare,
        readiness: athlete.readiness,
        goalMiles: Number(athlete.goalMiles) || undefined,
        paces: athlete.paces,
      })
    : null;
  const qualityText = written ? written.text
    : yielding ? 'Easy — your max attempt is this week and owns it'
    : cooked ? 'Easy only — the hard run moves to when you have recovered' : String(week.quality);
  /* Race week keeps its miles whatever the check-in said: the session IS the
     event, qualitySession has already changed what it says about it, and a
     week that silently drops the race from its own total is lying about the
     one day it exists for. */
  const qualityMiles = hasQuality && (raceWeek || (!cooked && !yielding)) ? (written ? written.miles : qualitySessionMiles(String(week.quality), pace)) : 0;

  /* THE WEEK HITS ITS NUMBER EVEN WHEN THERE IS NOWHERE TO PUT THE DIFFERENCE.
     On two running days there are no easy runs to absorb anything, so the
     week's total became whatever the long run and the hard session happened to
     add up to — and since a fartlek week and a threshold week are different
     sizes, an athlete's volume swung 45% between consecutive weeks for no
     reason connected to their training. The long run takes up the slack, up to
     its own caps, so weekly volume is stable and the variation lands where it
     is harmless. */
  const slack = round1(budget - longRunMiles - qualityMiles);
  /* THE LONG RUN IS THE BALANCING ITEM, bounded by durability and nothing else.
     On a two-run week the hard session's size swings with its type — a
     marathon race-pace segment is eight miles where a strides session is
     three — and if the long run does not take up that difference, the
     athlete's weekly volume swings with it: fifteen miles one week and
     twenty-five the next, from a plan that thought it was progressing at ten
     percent. An attempt to limit it by ratio (the long run no more than twice
     the other run) only moved the problem: the week came in short instead.

     So it absorbs the whole shortfall, and the thing that stops it running
     away is the durability cap — a mile a week over what the athlete has
     actually covered, which is the limit that matters. A long run that is 80%
     of a two-run week is arithmetic, not a mistake. A long run past what they
     have ever run is a mistake whatever share it is. */
  const longTopUp = hasLong && slack > 0 && easyDays.length === 0
    ? round1(Math.min(slack, Math.max(0, Math.min(budget * maxLongShare, longCap) - longRunMiles)))
    : 0;
  let longRun = round1(longRunMiles + longTopUp);

  /* Whatever is left is easy volume, split into real distances. */
  const easyTotal = Math.max(0, round1(budget - longRun - qualityMiles));
  const easyRuns: number[] = [];
  if (easyDays.length && easyTotal > 0) {
    const base = Math.max(1, Math.floor((easyTotal / easyDays.length) * 2) / 2);
    for (let index = 0; index < easyDays.length; index++) easyRuns.push(base);
    let spare = round1(easyTotal - base * easyDays.length);
    for (let index = 0; spare >= 0.5 - 1e-9 && index < easyDays.length * 4; index++) {
      easyRuns[index % easyDays.length] = round1(easyRuns[index % easyDays.length] + 0.5);
      spare = round1(spare - 0.5);
    }
  } else if (easyDays.length) {
    for (let index = 0; index < easyDays.length; index++) easyRuns.push(1);
  }

  /* The header equals the sum of what is actually scheduled beneath it — and
     the sum of rounded parts can clear a ceiling the target respected. An
     athlete who capped themselves at 18 and is handed 18.1 has been ignored,
     by a tenth of a mile, which is exactly the kind of thing that teaches
     people the number they typed does not matter. The overshoot comes off the
     easy running, which is the only part with nothing riding on its length. */
  const sum = () => round1(longRun + qualityMiles + easyRuns.reduce((total, miles) => total + miles, 0));
  let scheduled = sum();
  /* AND IT NEVER CLEARS ITS OWN TARGET. The sum of rounded parts can exceed a
     number every part respected: an athlete who capped themselves at 18 was
     handed 18.4, and a deload week came out heavier than the week it was
     recovering from — by a tenth of a mile each time, which is exactly the
     kind of thing that teaches people the numbers do not mean anything. The
     overshoot comes off the easy running, the only part with nothing riding on
     its length. Race week is exempt: the distance is not negotiable. */
  /* AND THE NUMBER THE ATHLETE SEES IS RATE-LIMITED, not just the number the
     engine aimed at. The target respects a 10%-a-week climb, but the week's
     total is the sum of its parts, and those parts change size when the
     session type changes — a marathon race-pace week is eight miles where a
     strides week is three. That swing pushed a two-day athlete from 15 miles
     to 25 in one step, with every individual rule satisfied. A fifth more than
     last week is the most any week is allowed to be. */
  const hardCap = racing ? Infinity : budget;
  if (scheduled > hardCap) {
    let over = round1(scheduled - hardCap);
    for (let index = easyRuns.length - 1; index >= 0 && over > 0; index -= 1) {
      const trim = Math.min(over, round1(Math.max(0, easyRuns[index] - 1)));
      easyRuns[index] = round1(easyRuns[index] - trim);
      over = round1(over - trim);
    }
    /* Nothing left to take it from but the long run, which happens on a week
       with no easy running in it at all. */
    if (over > 0 && longRun > 0) longRun = round1(Math.max(budget * LONG_RUN_MIN_SHARE, longRun - over));
    scheduled = sum();
  }
  const easyMinutes = easyRuns.length ? Math.round((easyRuns[0] * pace) / 5) * 5 : 0;
  /* The written session names its own pace; the stored qualityPace is appended
     by the card and would contradict it. */
  return { ...week, phase, quality: hasQuality ? qualityText : week.quality, qualityPace: written || yielding ? '' : week.qualityPace, mileage: scheduled, longRunMiles: raceWeek ? 0 : longRun || week.longRunMiles, easyDays, easyRuns, easyMinutes };
}

/* `projectSteps` is how many times this rep count comes round between now and
   the week being drawn. The wave is written from what the athlete has logged,
   so every week of a block resolves from TODAY's evidence — which made the
   second half of a ten-week block a carbon copy of the first: the same 415 x 8
   in week 4 and week 9, the same max attempt twice. Weeks further out are
   drawn one step heavier per pass, which is exactly what will happen if the
   athlete hits them. It is a projection and it says so; miss a week and the
   weeks after it recompute from what was really done. */
export type WaveOptions = {
  /* Kilograms: plate steps and bumps change size, nothing else. */
  metric?: boolean;
  /* The athlete's heaviest real single, when they have one. */
  bestSingle?: number;
  /* Whether this lift carries a Real 1RM goal, which is the only thing that
     earns a tested single at the top of the wave. */
  tests?: boolean;
  anchors?: Map<number, number>;
  /* Weeks drawn ahead of today, each one step heavier — a projection. */
  projectSteps?: number;
  /* Ask for exactly what has already been done, with no step on top. */
  holding?: boolean;
  /* A lift with no goal on it: 12/10/8/6 off the calculated max instead. */
  accessory?: boolean;
  /* Whether the BLOCK is on its max week. Given, it — and nothing about the
     lift's own session count — decides whether a single is on the table, and
     ordinary weeks read the rep count off the 8/6/4/2 ramp. Omitted, the old
     behaviour stands: weekIndex is a block wave index and answers both. */
  maxWeek?: boolean;
  /* Whether this lift has been trained enough inside the block to test.
     Default true, so nothing that does not track exposures changes. */
  ramped?: boolean;
  /* Completed sessions on this lift, which is what moves an accessory along. */
  sessions?: number;
  /* Failed attempts since the last success, per rep count. */
  misses?: Map<number, number>;
  /* The last load actually completed at each rep count — where a rung that has
     been failed three times in a row goes back to. */
  lastAt?: Map<number, number>;
};

/* THE ARGUMENT LIST WAS EIGHT POSITIONS LONG and three of them were booleans,
   so `(best, i, false, 0, true, anchors)` said nothing about what it meant and
   a call site that got the order wrong was silently a different program. */
export function wavePrescription(best: number, weekIndex: number, options: WaveOptions = {}): { weight: number; reps: number; isMax: boolean } {
  const { metric = false, bestSingle = 0, tests = false, anchors, projectSteps = 0, holding = false, accessory = false, sessions = 0, misses, lastAt, maxWeek, ramped = true } = options;
  /* `holding` asks for exactly what the athlete has already done, with no step
     on top — for the caller that has decided the evidence does not support one
     yet. Without it, a lift with a single logged session was stepped up five
     pounds under a sentence saying it was being held. */
  const plateStep = metric ? 2.5 : 5;
  /* THREE MISSES AT A REP COUNT AND THE STEP COMES OFF, so the prescription
     falls back to the last load actually completed there rather than asking
     again for a bar that has beaten the athlete three times. */
  const backedOff = (count: number) => (misses?.get(Math.min(Math.max(Math.round(count), 1), PRESCRIPTION_REP_CAP)) || 0) >= FAILURES_BEFORE_BACKOFF;
  const stepFor = (count: number) => (holding || backedOff(count) ? 0 : plateStep);
  const step = holding ? 0 : plateStep;
  const bump = metric ? 3.75 : 7.5;
  /* WHERE A BACKED-OFF RUNG LANDS: the last load the athlete actually
     completed at that rep count, falling back to their heaviest there when the
     history has no dated copy of it. */
  const completedAt = (count: number) => {
    const slot = Math.min(Math.max(Math.round(count), 1), PRESCRIPTION_REP_CAP);
    return lastAt?.get(slot) || anchors?.get(Math.min(slot, REP_MAX_CAP)) || 0;
  };
  if (accessory) {
    const { reps: accessoryReps } = accessorySlot(sessions);
    /* EACH RUNG ANSWERS FOR ITSELF. Succeed at the 12 and the 10 and they keep
       climbing with the working max; fail the 8 three times in a row and the 8
       — and only the 8 — goes back to the load actually completed there. The
       whole cycle used to move together, so one rung the athlete could not hold
       either dragged every other rung down with it or kept being asked for. */
    const held = backedOff(accessoryReps) ? completedAt(accessoryReps) : 0;
    if (held) return { weight: Math.max(plateStep, Math.floor(held / plateStep) * plateStep), reps: accessoryReps, isMax: false };
    /* Compounding: every completed fifth session adds another plate step to
       the max the load is written from, and the next raise stacks on that. */
    const raises = holding ? 0 : Math.floor(Math.max(0, sessions) / ACCESSORY_SESSIONS_PER_RAISE);
    const workingMax = Math.max(0, best) + raises * plateStep;
    /* ONE MAX WRITES ALL FOUR RUNGS, which is the point of running them off a
       calculated max at all: the twelve, the ten, the eight and the six stay in
       proportion to each other and to the athlete. Writing each rung from its
       own logged history instead let them drift apart — a 105 x 12 beside a
       105 x 6 is not a ladder, it is four unrelated numbers that happen to sit
       on the same lift. The only thing that ever breaks the proportion is a
       rung the athlete has failed three times, which is handled above. */
    const weight = Math.max(plateStep, Math.ceil(weightForReps(workingMax, accessoryReps) / plateStep) * plateStep);
    return { weight, reps: accessoryReps, isMax: false };
  }
  /* When the caller knows what the block is doing, the block decides the test
     and the lift's own rung only picks its place on the ramp. */
  const slot = waveSlot(weekIndex);
  const isMax = maxWeek === undefined ? slot.isMax : maxWeek;
  const reps = maxWeek === undefined ? slot.reps : rampReps(weekIndex);
  /* "A rep higher than last PR by 5-10": a real logged single anchors the
     attempt directly; without one, the estimated max stands in. */
  const projection = Math.max(0, projectSteps) * plateStep;
  /* BACKED OFF MEANS THE LOAD THEY ACTUALLY COMPLETED, not a blend that
     happens to land near it. The nearest-evidence average still reads the
     athlete's other sets — a 225 x 10 pushes the implied double to 256 — so
     dropping the step alone left the bar where it was. After three misses the
     prescription is their own completed set at that rep count, full stop. */
  /* The heaviest this lift may be asked for at a given rep count, given what
     the athlete has actually tested. Infinity for a lift never tested — there
     is no fact to be disciplined by. Rounded DOWN to a plate step, so the
     rounding cannot walk back over the ceiling it was applied to. */
  const testedCeiling = (count: number) => {
    /* A tested single is a fact about the LIFT, not about whether a goal
       happens to be attached to it. Reading it off `tests` left the fallback
       double — which is written with tests off — unclamped, so it came out
       above the attempt it was meant to be lighter than. */
    if (!bestSingle) return Infinity;
    /* A PROJECTED WEEK ASSUMES THE MAX WEEKS BETWEEN HERE AND THERE HAPPENED.
       Without this the ceiling froze the whole block at one number: week ten
       could not be heavier than week five, because both were measured against
       a single that, in the projection, had already been beaten twice. */
    const headroom = Math.pow(MAX_OVER_TESTED, 1 + Math.max(0, projectSteps));
    const supported = count <= 1 ? bestSingle * headroom : weightForReps(bestSingle * headroom, count);
    return Math.max(plateStep, Math.floor(supported / plateStep) * plateStep);
  };
  const loadFor = (count: number) => {
    const held = backedOff(count) ? completedAt(count) : 0;
    if (held) return Math.max(plateStep, Math.floor(held / plateStep) * plateStep);
    const asked = Math.max(plateStep, Math.ceil((loadFromAnchors(anchors, best, count, stepFor(count)) + projection) / plateStep) * plateStep);
    return Math.min(asked, testedCeiling(count));
  };
  /* THE ATTEMPT SITS ABOVE THE DOUBLE. The rep weeks are written from the
     calculated max (what the athlete's best rep work proves); the attempt was
     anchored to the last real single. When rep work had moved on and the
     single had not — 415 × 8 says 520-ish, the last single was 475 — the
     block prescribed 490 × 2 one week and a 485 "max attempt" the next: a
     single lighter than the double just done. A max attempt is never below
     the heavy double plus one plate step; the single anchors it only when
     that is the higher number. */
  const attemptWeight = () => {
    /* Converted through the shared curve, so "the max plus a bump" means a
       single and not a single shrunk by whatever the curve says about 1 rep. */
    const anchored = bestSingle ? bestSingle + bump : weightForReps(best + bump, 1);
    /* AND THE REP WORK GETS A VOTE. A single is a moment; rep work is months.
       An athlete whose last tested single is from the spring and who has since
       put up heavy fours deserves an attempt written from the fours — asking
       for ten pounds over a stale single is a max week that cannot find the
       max. This is the same nearest-evidence blend the rep weeks use, read at
       one rep, so it is bounded by the athlete's own sets. */
    const fromRepWork = anchors?.size ? loadFromAnchors(anchors, best, 1, stepFor(1)) : 0;
    /* A ceiling on the jump, not a target: however loudly the rep work
       argues, one block does not add a tenth to a tested single. Five percent
       of a 475 lb squat is still 20 lb, which is a real PR attempt; ten was
       45 lb and that is a different lift. This binds only when an estimate has
       run away — a normal max week never reaches it. */
    const attempt = Math.max(anchored, fromRepWork, loadFor(2) + plateStep) + projection;
    const rounded = Math.max(plateStep, Math.ceil(attempt / plateStep) * plateStep);
    /* Clamped AFTER rounding: rounding up to the next plate used to step back
       over the ceiling — a 475 single capped at 498.75 came out as 500. */
    return Math.min(rounded, testedCeiling(1));
  };
  if (isMax) {
    /* A LIFT THAT HAS NOT RAMPED DOES NOT TEST. Arriving at the block's max
       week having trained the lift once is not a peak; it takes the double
       instead and tests on the next one. */
    if (tests && ramped) return { weight: attemptWeight(), reps: 1, isMax: true };
    /* No goal on this lift: it holds the double it earned. It is not offered
       a single — a max that serves no goal is a max the plan did not ask for. */
    return { weight: loadFor(2), reps: 2, isMax: false };
  }
  return { weight: loadFor(reps), reps, isMax };
}

/* Which split days land inside a given plan week. A rolling cycle that is not
   7 days long rotates, so an 8-day split shows only 7 of its days in any one
   week — the volume math has to agree with the schedule about which. */
/* AN ANCHOR BELONGS TO A DATE, AND IT IS NOT ALWAYS TODAY.

   The anchor is the NEXT split day — the one after the last session logged.
   This assumed that day was today's, and on any day the athlete had already
   trained it was tomorrow's: the whole week got drawn one day early, and the
   day that should have been tomorrow was painted onto today, where the logged
   session covers it. Preston trained Chest & Back 2 on the Friday, so Legs 2
   was written onto Friday behind it and the week read Chest & Back 2 → Sharms
   2. Legs 2, the next day in his own split, did not appear anywhere. */
export function weekCycleDays(startIso: string, weekIndex: number, splitDays: SplitDayRef[], rhythm: 'rolling' | 'weekly', anchor?: { position: number; dateIso?: string }): SplitDayRef[] {
  const cycle = splitDays.length ? splitDays : [{ name: 'Training', dayType: 'strength' } as SplitDayRef];
  const start = new Date(`${startIso}T12:00:00`); start.setDate(start.getDate() + weekIndex * 7);
  const anchorDay = anchor?.dateIso ? new Date(`${anchor.dateIso}T12:00:00`) : new Date();
  anchorDay.setHours(12, 0, 0, 0);
  const todayAbsolute = Math.floor(anchorDay.getTime() / 86400000);
  const anchorIndex = anchor ? cycle.findIndex((_, index) => index + 1 === anchor.position) : -1;
  return Array.from({ length: 7 }, (_, index) => {
    const date = new Date(start); date.setDate(start.getDate() + index);
    const absoluteDay = Math.floor(date.getTime() / 86400000);
    const cycleIndex = rhythm !== 'rolling' ? index % cycle.length
      : anchorIndex >= 0 ? (((anchorIndex + (absoluteDay - todayAbsolute)) % cycle.length) + cycle.length) % cycle.length
      : ((absoluteDay % cycle.length) + cycle.length) % cycle.length;
    return cycle[cycleIndex];
  });
}

/* ONE 1RM ATTEMPT PER LIFT PER WEEK, DECIDED IN ONE PLACE. A rolling split
   shorter than seven days hits the same day twice inside a week. The Plan tab
   knew that and demoted the second exposure to the heavy double; Today did
   not, and told the athlete to attempt a true single on BOTH days. Whoever is
   drawing the week asks here which exposure carries the attempt: the cheapest
   day — the one not already carrying the long run or the quality session.
   Keyed canonically, so "Squat" and "Back Squat" cannot each claim one. */
export function chooseMaxAttemptDays(
  days: Array<{ exercise?: string; reps?: number; hasHold?: boolean; cost: number }>,
): Set<number> {
  const best = new Map<string, { index: number; cost: number }>();
  days.forEach((day, index) => {
    if (!day.exercise || day.reps !== 1 || !day.hasHold) return;
    const key = canonicalLiftKey(day.exercise);
    const held = best.get(key);
    if (!held || day.cost < held.cost) best.set(key, { index, cost: day.cost });
  });
  return new Set([...best.values()].map(entry => entry.index));
}

/* ONE RESOLVED WEEK, SHARED BY EVERY SURFACE. The stored block is raw model
   output; what the athlete is actually shown is that block after three
   corrections — running rebuilt into distances that add up, the goal lift
   claiming its day, and every top set recomputed from the current logged best
   through the wave. Plan, Today and Coach all read THIS, so the coach cannot
   quote a number the app does not display. Anything reading storedPlan.weeks
   directly is a bug waiting to contradict the screen. */
export function resolvePlanWeek<T extends AiPlanWeek>(
  week: T,
  splitDays: SplitDayRef[],
  athlete: RunningAthlete,
  /* weekIndex is the CALENDAR week; waveIndex is where that week sits in the
     8/6/4/2/1 wave and defaults to it. They differ when the block entered the
     wave mid-way — see StoredAiPlan.waveOffset. */
  /* weeksToRace / weeksToLiftGoal: how long each goal has left. They are what
     decides who owns a week when a max attempt and a race-effort week land
     together — the nearer goal, because that is the only one for which this
     particular week cannot be replaced. */
  block: { weekIndex: number; blockWeeks: number; waveIndex?: number; currentWaveIndex?: number; currentWeekIndex?: number; liftingMaxWeek?: boolean; weeksToRace?: number; weeksToLiftGoal?: number },
  /* `rungOf` is how far along its own progression a lift is — how many
     prescriptions it has answered. Every lift has its own, because they are
     trained at different rates and an off-script set on one must not move the
     others. `exposuresPerWeek` is what turns that into a projection for a week
     further out: a lift trained twice a week is two rungs along by next week.
     Without them this falls back to the block's single wave index, which is
     what every surface used before positions existed. */
  strength: { bests: Map<string, number>; singles?: Map<string, number>; goalLifts: Set<string>; metric?: boolean; anchors?: LiftAnchors; sessions?: Map<string, number>; misses?: Map<string, Map<number, number>>; lastAt?: LiftAnchors; rungOf?: (lift: string) => number | undefined; exposuresPerWeek?: (lift: string) => number },
  /* The days this week actually contains — a rolling cycle longer than 7 days
     shows only some of itself per week, and the running has to be measured
     over what is really there. Defaults to the whole split. */
  runWindow?: SplitDayRef[],
): T & { adjusted: boolean } {
  const resolved = resolveWeekRunning(week, runWindow?.length ? runWindow : splitDays, athlete, block);
  /* WHICH GOAL LIFT OWNS A DAY CANNOT DEPEND ON ARRAY ORDER. "Chest & Back"
     maps Bench and Pull Ups — both goal lifts — and the day appears twice in
     the cycle. Taking the FIRST match meant the owner was decided by however
     the exercises happened to be stored, and the two instances were stored in
     opposite orders: Chest & Back prescribed Bench, Chest & Back 2 prescribed
     Pull Ups, for what is one day. Reorder the list in the plan editor and the
     prescription changed under the athlete.

     Two goal lifts on a day that occurs twice is not a conflict — it is one
     each. So the instances of a day are folded together, its goal lifts sorted
     canonically so the answer never moves, and handed out round-robin by
     instance: the first exposure takes the first lift, the second takes the
     second. One goal lift on a day still owns every instance of it. */
  const instancesOfDay = new Map<string, string[]>();
  splitDays.forEach(day => {
    const key = splitDayKey(day.name);
    instancesOfDay.set(key, [...(instancesOfDay.get(key) || []), day.name]);
  });
  const goalLiftsOfDay = new Map<string, string[]>();
  splitDays.forEach(day => {
    const key = splitDayKey(day.name);
    const owned = (day.exercises || []).filter(name => strength.goalLifts.has(canonicalLiftKey(name)));
    const merged = new Map<string, string>();
    [...(goalLiftsOfDay.get(key) || []), ...owned].forEach(name => merged.set(canonicalLiftKey(name), name));
    goalLiftsOfDay.set(key, [...merged.values()].sort((a, b) => canonicalLiftKey(a).localeCompare(canonicalLiftKey(b))));
  });
  const dayGoalLift = new Map<string, string>();
  instancesOfDay.forEach((names, key) => {
    const owners = goalLiftsOfDay.get(key) || [];
    if (!owners.length) return;
    names.forEach((name, index) => dayGoalLift.set(name, owners[index % owners.length]));
    dayGoalLift.set(key, owners[0]);
  });
  const lookup = (table: Map<string, number> | undefined, name: string) =>
    table?.get(name) ?? [...(table?.entries() || [])].find(([lift]) => canonicalLiftKey(lift) === canonicalLiftKey(name))?.[1];
  const anchorsFor = (name: string) => strength.anchors?.get(canonicalLiftKey(name));
  const missesFor = (name: string) => strength.misses?.get(canonicalLiftKey(name));
  const lastAtFor = (name: string) => strength.lastAt?.get(canonicalLiftKey(name));
  const sessionsFor = (name: string) => strength.sessions?.get(canonicalLiftKey(name)) || 0;
  let adjusted = false;
  /* A DAY THAT TRAINS TWO GOAL LIFTS PRESCRIBES BOTH ON THE SAME DAY, and a
     day's other work keeps its own name. The rule "the goal lift owns its day"
     was written when a day carried exactly ONE top set; applied per row it
     rewrote every row on the day to the same lift, so a Chest & Back day read
     "Bench 300×8 · Bench 300×8" and the second movement vanished. What the
     rule actually means is that the day must PRESCRIBE its goal lifts — not
     that every set on it is one. Each goal lift is placed once; every other
     row is left exactly as the block wrote it. */
  const rowsByDay = new Map<string, number[]>();
  (resolved.topSets || []).forEach((row, index) => {
    rowsByDay.set(row.splitDay, [...(rowsByDay.get(row.splitDay) || []), index]);
  });
  const forcedExercise = new Map<number, string>();
  rowsByDay.forEach((indexes, dayName) => {
    const key = splitDayKey(dayName);
    const owners = goalLiftsOfDay.get(key) || [];
    if (!owners.length) return;
    /* One instance of a day owes one goal lift when the cycle visits it more
       than once; a day with more rows than instances can carry more. */
    const instanceOwner = dayGoalLift.get(dayName) || dayGoalLift.get(key);
    const owed = owners.length > 1 ? owners : instanceOwner ? [instanceOwner] : [];
    const present = new Set(indexes
      .map(index => canonicalLiftKey((resolved.topSets || [])[index].exercise))
      .filter(liftKey => owed.some(name => canonicalLiftKey(name) === liftKey)));
    const missing = owed.filter(name => !present.has(canonicalLiftKey(name)));
    if (!missing.length) return;
    /* Only rows that are NOT already a goal lift give way. */
    for (const index of indexes) {
      if (!missing.length) break;
      const rowKey = canonicalLiftKey((resolved.topSets || [])[index].exercise);
      if (owners.some(name => canonicalLiftKey(name) === rowKey)) continue;
      forcedExercise.set(index, missing.shift()!);
    }
  });
  /* EVERY MOVEMENT MAPPED TO THE DAY GETS A PRESCRIPTION.

     The block's rows are whatever the model wrote — usually one or two per day
     — and this function only ever repaired them. So a Chest & Back day mapping
     Bench, Pull Ups, Smith Machine Incline Bench and Lat Pulldown showed two
     lines, and opening the day showed the same two: the athlete had mapped four
     movements and Forge had an opinion about two of them. The accessory cycle
     exists precisely so the other two can be prescribed — 12/10/8/6 off the
     calculated max — and nothing was asking it.

     A day's remaining movements are appended in the order the athlete mapped
     them, after the rows the block wrote, and go through the same prescription
     below. A lift with no logged history is skipped: there is nothing to wave
     off, and a row reading "0 × 0" is worse than no row. */
  const padded = [...(resolved.topSets || [])];
  const daysThisWeek = (runWindow?.length ? runWindow : splitDays).filter(day => !isRestDay(day));
  const seenDay = new Set<string>();
  daysThisWeek.forEach(day => {
    /* A rolling cycle can land the same day twice in one week; its movements
       are listed once. */
    if (seenDay.has(day.name)) return;
    seenDay.add(day.name);
    /* Read the row's exercise AFTER the goal-lift repair. A row rewritten to
       carry a goal lift no longer holds the movement it started with, and
       judging presence from the old value would drop that movement — the
       repair would silently cost the athlete an exercise instead of adding
       one. Read this way it comes back below, as an accessory. */
    const already = new Set(padded
      .map((row, index) => ({ row, exercise: forcedExercise.get(index) || row.exercise }))
      .filter(entry => entry.row.splitDay === day.name)
      .map(entry => canonicalLiftKey(entry.exercise)));
    (day.exercises || []).forEach(name => {
      const liftKey = canonicalLiftKey(name);
      if (already.has(liftKey)) return;
      if (!lookup(strength.bests, name)) return;
      already.add(liftKey);
      padded.push({ splitDay: day.name, exercise: name, weight: 0, reps: 0 });
      adjusted = true;
    });
  });
  const topSets = padded.map((raw, index) => {
    const forced = forcedExercise.get(index);
    const set = forced && canonicalLiftKey(forced) !== canonicalLiftKey(raw.exercise) ? { ...raw, exercise: forced } : raw;
    if (set !== raw) adjusted = true;
    const best = lookup(strength.bests, set.exercise);
    if (!best) return set;
    const tests = testsOneRepMax(set.exercise, strength.goalLifts);
    /* THE RUNG IS THE LIFT'S, NOT THE BLOCK'S. One wave index for the whole
       week meant Today and Plan could never agree — Today counted sessions per
       lift, Plan counted calendar weeks — and a lift trained once a fortnight
       was dragged along by the calendar. A week further out is a projection:
       the lift's position plus the exposures it would collect getting there. */
    /* A GOAL LIFT RIDES THE BLOCK'S WAVE. THE ACCESSORIES RIDE THEIR OWN.

       Giving every lift its own rung, counted in the sessions it had answered,
       was meant to stop an off-script set from shunting the whole program. It
       does stop that — but so does the calendar, which an off-script set
       cannot touch at all, and the calendar is the clock the athlete is
       actually shown. Two clocks meant the header said "4-rep week" over a
       squat asking for a single, and Today and Plan could disagree about the
       same Saturday.

       So the goal lifts follow the block: one rung of 8/6/4/2/1 per block
       week, the thing the banner names. Accessories are the case the per-lift
       rung was really for — a movement trained once a fortnight should not be
       four rungs along because the block is four weeks old — and they still
       advance on their own session count, through accessorySlot below. */
    const waveIndex = block.waveIndex ?? block.weekIndex;
    /* How many passes through the wave separate this week from the one the
       athlete is actually in. Zero for the current pass and everything behind
       it — those are drawn from evidence, not projected. */
    const projectSteps = Math.max(0, Math.floor((waveIndex - (block.currentWaveIndex ?? waveIndex)) / WAVE_LENGTH));
    /* A NON-GOAL LIFT TAKES THE ACCESSORY CYCLE, advanced by how many times it
       has actually been trained rather than by how old the block is — plus one
       step per projected pass, since a projected week is drawn as though the
       sessions between here and there were completed. */
    const accessory = !tests;
    /* THE MAX WEEK IS THE BLOCK'S, NOT THE LIFT'S. `waveIndex` above is how
       far along its OWN progression this lift is — the right clock for a rep
       rung and the wrong one for a test. Read on its own it put a 1RM attempt
       in week 1 of a ten-week block, under a header the block had already
       named a build week. The block says which week tests; the lift's rung
       says where on 8/6/4/2 it stands the rest of the time. */
    /* A MAX ATTEMPT IS THE LAST THING TO TAKE ON A BAD DAY, and the one most
       likely to hurt someone. Readiness gates the CURRENT week only: a future
       week is a projection and is drawn as though the athlete arrives at it in
       one piece, which they usually do. */
    const thisWeek = block.weekIndex === (block.currentWeekIndex ?? block.weekIndex);
    const readyEnough = !(thisWeek && typeof athlete.readiness === 'number' && athlete.readiness < 55);
    /* ONE PEAK AT A TIME. A max single and a race-effort week are both all-out,
       and stacking them is how an athlete arrives at a race having squatted a
       lifetime best four days earlier. The nearer goal keeps its week; the
       other one holds at what it has already earned, which is a back-off, not
       a skip. */
    const running = peakConflict({
      liftingMaxWeek: tests,
      runningPeakWeek: runningPeaks(resolved.phase),
      weeksToRace: block.weeksToRace,
      weeksToLiftGoal: block.weeksToLiftGoal,
    });
    const liftYields = running?.owner === 'running';
    const waveOptions = { metric: strength.metric, bestSingle: lookup(strength.singles, set.exercise) || 0, tests: tests && readyEnough && !liftYields, anchors: anchorsFor(set.exercise), projectSteps, accessory, sessions: sessionsFor(set.exercise) + projectSteps, misses: missesFor(set.exercise), lastAt: lastAtFor(set.exercise), ramped: sessionsFor(set.exercise) + projectSteps >= EXPOSURES_BEFORE_MAX };
    const live = wavePrescription(best, waveIndex, waveOptions);
    if (live.weight !== set.weight || live.reps !== set.reps) adjusted = true;
    /* On a max week a tested lift also carries the double it falls back to
       when the split hits that day more than once in the same week. */
    const hold = live.reps === 1 ? wavePrescription(best, waveIndex, { ...waveOptions, tests: false, accessory: false }) : undefined;
    return { ...set, weight: live.weight, reps: live.reps, hold: hold && { weight: hold.weight, reps: hold.reps } };
  });
  return { ...resolved, topSets, adjusted };
}

/* How many plan weeks remain from today. Week 1 starts at startDate. */
export const weeksRemaining = (stored: StoredAiPlan): number => {
  const start = new Date(`${stored.startDate}T12:00:00`).getTime();
  const elapsed = Math.floor((Date.now() - start) / 604800000);
  return stored.plan.weeks.length - elapsed;
};

/* The plan week that covers today (clamped into the block). This is a CALENDAR
   position and nothing else: week 1 is the week of startDate, and today is
   always inside the week this returns.

   The wave offset deliberately does NOT belong here. Folding it in shifted the
   week the schedule drew, so a block that entered the wave at 6 reps rendered
   next week's dates and the athlete opened Plan to a week that was not the one
   they were in. Where the block enters the wave is a question about REPS; which
   week it is, is a question about the calendar. `waveIndexOf` answers the
   first, this answers the second. */
export const currentWeekIndex = (stored: StoredAiPlan): number => weekIndexOn(stored, localDayIso());

/* The same question asked about a DAY THAT HAS ALREADY HAPPENED. Judging how a
   session went means knowing what was prescribed on the day it was run, not
   what is prescribed this week. */
export const weekIndexOn = (stored: StoredAiPlan, dayIso: string): number => {
  const start = new Date(`${stored.startDate}T12:00:00`).getTime();
  const elapsed = Math.floor((new Date(`${dayIso}T12:00:00`).getTime() - start) / 604800000);
  return Math.max(0, Math.min(stored.plan.weeks.length - 1, elapsed));
};

/* Which rung of the 8/6/4/2/1 wave a given block week sits on, once the
   block's entry point is taken into account. Every surface that asks "is this
   a max week / what rep count is this" asks here. */
export const waveIndexOf = (stored: Pick<StoredAiPlan, 'waveOffset'>, weekIndex: number): number =>
  weekIndex + (stored.waveOffset || 0);

/* WHERE THE ATHLETE IS IN THE WAVE, read from what they logged rather than
   asked about. The most recent completed top set on a goal lift names the rung
   they just finished (8/6/4/2/1); the next block opens on the one after it.
   Nothing logged in the last three weeks means the wave starts at the top. */
export function waveOffsetFromHistory(
  records: Array<{ date: string; topSets?: Array<{ lift: string; reps: number; completed?: boolean }> }>,
  goalLifts: Set<string> | string[],
): number {
  const wanted = new Set([...goalLifts].map(name => canonicalLiftKey(String(name))));
  const cutoff = localDayIso(new Date(Date.now() - 21 * 86400000));
  let latestDate = '';
  let latestReps = 0;
  records.forEach(record => {
    if (record.date < cutoff) return;
    (record.topSets || []).forEach(set => {
      if (set.completed === false || !set.lift || !(set.reps > 0)) return;
      if (wanted.size && !wanted.has(canonicalLiftKey(set.lift))) return;
      if (record.date >= latestDate) { latestDate = record.date; latestReps = set.reps; }
    });
  });
  if (!latestReps) return 0;
  /* Snap an honest rep count onto the nearest rung — a set of 7 is an 8 week. */
  let slot = 0, best = Infinity;
  WAVE_REPS.forEach((reps, index) => { const gap = Math.abs(reps - latestReps); if (gap < best) { best = gap; slot = index; } });
  return (slot + 1) % WAVE_LENGTH;
}
