import { isDemoMode } from '../../lib/env';
import { canonicalLiftKey } from '../../lib/liftAliases';
import { supabase } from '../../lib/supabase';

/* The AI program: an 8-week block generated by the forge-plan edge function
   from the athlete's goals, split, logged bests, and actual logged running.
   It is stored (Supabase + local cache) and the Plan tab renders FROM STORAGE;
   a new block generates silently when this one runs low or inputs change. */

/* hold is client-side only: when a goal lift lands on a max week twice (the
   split runs the same day twice a cycle), only ONE instance is the attempt —
   the other carries the double it falls back to. */
export type AiPlanTopSet = { splitDay: string; exercise: string; weight: number; reps: number; hold?: { weight: number; reps: number } };
export type AiPlanWeek = {
  week: number; phase: 'Base' | 'Build' | 'Peak' | 'Deload' | 'Taper' | 'Race';
  mileage: number; longRunMiles: number; longRunPace: string; longRunDay: string;
  quality: string; qualityPace: string; qualityDay: string;
  easyDays: string[]; easyMinutes: number; easyPace: string;
  /* Miles for each entry in easyDays, derived so the week's parts add up to
     its stated mileage. Client-side: a stored plan predates this field. */
  easyRuns?: number[];
  topSets: AiPlanTopSet[]; note: string;
};
export type AiPlan = { summary: string; easyPace: string; weeks: AiPlanWeek[] };
/* saved: the athlete has approved this block. Forge rebuilds a plan on its own
   when the inputs move — new goal, changed split, a PR past the baseline — and
   that is right until someone is happy with the block they have. A saved plan
   is pinned: nothing replaces it except an explicit, confirmed refresh. */
export type StoredAiPlan = { plan: AiPlan; generatedAt: string; startDate: string; fingerprint: string; blockWeeks: number; saved?: boolean; savedAt?: string };

const localKey = 'forge-ai-plan-v1';

/* Stable fingerprint of everything the program depends on. When it changes
   (goal edited, split day renamed, exercises remapped), the block regenerates. */
export const planFingerprint = (input: unknown) => {
  const text = JSON.stringify(input);
  let hash = 0;
  for (let index = 0; index < text.length; index++) { hash = ((hash << 5) - hash + text.charCodeAt(index)) | 0; }
  return String(hash);
};

const readLocal = (): StoredAiPlan | null => { try { return JSON.parse(localStorage.getItem(localKey) || 'null'); } catch { return null; } };
/* Synchronous cache read for surfaces (Today, Coach) that align to the plan. */
export const readLocalAiPlan = readLocal;
const writeLocal = (stored: StoredAiPlan) => { try { localStorage.setItem(localKey, JSON.stringify(stored)); } catch { /* full */ } };

export async function loadStoredAiPlan(hasUser: boolean): Promise<StoredAiPlan | null> {
  const local = readLocal();
  if (isDemoMode || !hasUser) return local;
  try {
    const { data } = await supabase.from('training_plans').select('payload,generated_at').maybeSingle();
    if (data?.payload) {
      const stored = data.payload as StoredAiPlan;
      writeLocal(stored);
      return stored;
    }
  } catch { /* fall back to local */ }
  return local;
}

export async function saveStoredAiPlan(stored: StoredAiPlan, hasUser: boolean): Promise<void> {
  writeLocal(stored);
  window.dispatchEvent(new Event('forge-ai-plan-changed'));
  if (isDemoMode || !hasUser) return;
  try {
    const { data: userData } = await supabase.auth.getUser();
    if (!userData.user) return;
    await supabase.from('training_plans').upsert({ owner_id: userData.user.id, payload: stored, horizon_weeks: stored.blockWeeks, generated_at: stored.generatedAt }, { onConflict: 'owner_id' });
    /* Every block is kept — regeneration never destroys the record of what
       the program used to prescribe. */
    await supabase.from('training_plan_history').insert({ owner_id: userData.user.id, payload: stored, generated_at: stored.generatedAt });
  } catch { /* local copy still stands */ }
}

export async function generateAiPlan(context: Record<string, unknown>): Promise<AiPlan> {
  const { data, error } = await supabase.functions.invoke('forge-plan', { body: { context } });
  if (error || !data?.plan?.weeks?.length) {
    let detail = 'The plan service did not return a program.';
    const response = (error as { context?: Response } | null)?.context;
    if (response) { try { const body = await response.clone().json(); if (typeof body?.error === 'string') detail = body.error; } catch { /* keep default */ } }
    throw new Error(detail);
  }
  return data.plan as AiPlan;
}

/* ── The 8/6/4/2 wave, shared by every surface ────────────────────────────
   Weeks cycle 8 → 6 → 4 → 2(max attempt). Weights always derive from the
   athlete's CURRENT best calculated max, so the plan reacts to what they
   actually log: beat a prescription and everything scales up; miss one and
   the wave holds steady instead of assuming progress. Max week attempts the
   PR + ~5-10 lb (2.5 kg steps for metric athletes). */
/* Preston's system: a 5-WEEK wave — 8, 6, 4, 2, then MAX WEEK (a true 1RM
   attempt). The running deload lands on the 2-rep week so the max attempt
   always follows a lighter week. */
export const WAVE_REPS = [8, 6, 4, 2, 1] as const;
export const WAVE_LENGTH = WAVE_REPS.length;
export const waveSlot = (weekIndex: number) => ({ reps: WAVE_REPS[weekIndex % WAVE_LENGTH], isMax: weekIndex % WAVE_LENGTH === WAVE_LENGTH - 1 });
/* Max week is a TRUE 1RM attempt — strength goals track Real 1RM, which only
   a 1-rep set can register. The attempt targets the current best + 5-10 lb
   (2.5 kg steps for metric athletes). */
/* A lift with a Real 1RM goal is the only one that MUST be tested: the goal
   cannot move without a logged single, so max week exists for it. Every other
   lift holds the heavy double instead of spending a testing session it does
   not owe, and the single is offered as optional for the day the athlete
   feels like taking it. With no strength goal set at all, nothing would ever
   be tested and a calc max would never convert, so every lift tests. */
export function goalLiftNames(goals: Array<{ type?: string; metric?: string; exercise?: string }>): Set<string> {
  /* Canonical keys, not raw names: a "Squat" goal must claim a prescription
     written as "Back Squat" — same lift, older spelling. */
  return new Set(goals.filter(goal => goal.type === 'Strength' && goal.exercise).map(goal => canonicalLiftKey(String(goal.exercise))));
}

/* THE RULE, IN ONE PLACE: a tested one-rep max exists ONLY to move a goal
   forward. A lift the athlete holds a Real 1RM goal on is tested on max week.
   Every other lift — no matter how heavy, how central to the day, or whether
   any goal exists at all — is never tested and never offered a single. No
   goal on a day means that day recommends its mapped work at the wave's rep
   count, nothing more. There are no exceptions to fall back on. */
export const testsOneRepMax = (exercise: string, goalLifts: Set<string>): boolean =>
  goalLifts.has(canonicalLiftKey(exercise));

/* RUNNING VOLUME AND RUN DAYS BELONG TO THE ATHLETE, NOT THE MODEL. The
   generator is told to use every stated running day and to stay inside the
   stated weekly-mileage range; it does not always comply. Preston runs 7 days
   a week with a 14-mile floor and got a block with easyDays: [] and 11.1
   miles — two running days, so most split days showed no cardio at all.
   Asking is not enforcing, so the week is corrected here, on the way to the
   screen: mileage clamped into range, and easy runs filled onto the split
   days that are not already carrying the long run or the quality session.
   Applied at render as well as at generation, so a block already stored on a
   device heals without being regenerated. */
export type SplitDayRef = { name: string; type?: string; dayType?: string };
const paceToMinutes = (pace?: string): number => {
  const match = String(pace || '').match(/(\d+):(\d{2})/);
  return match ? Number(match[1]) + Number(match[2]) / 60 : 0;
};
export type RunningAthlete = { runningDays?: number; minWeeklyMileage?: number; maxWeeklyMileage?: number; weeklyMileage?: number };

const round1 = (value: number) => Math.round(value * 10) / 10;

/* Miles a quality session actually covers, including warm-up and cool-down.
   The model writes these as prose ("6 × 400 m", "3 × 1 mi (5.8 mi total with
   warm-up/cool-down)", "20 min threshold"), and the week cannot be balanced
   without turning that back into a number. */
export const qualitySessionMiles = (quality: string, paceMinutes: number): number => {
  const text = String(quality || '');
  if (!text || /no goal/i.test(text)) return 0;
  const stated = text.match(/([\d.]+)\s*(?:mi|miles)\s*total/i);
  if (stated) return round1(Number(stated[1]));
  const reps = text.match(/(\d+)\s*[x\u00d7]\s*([\d.]+)\s*(m|mi|mile|miles|km)\b/i);
  if (reps) {
    const unit = reps[3].toLowerCase();
    const each = unit === 'm' ? Number(reps[2]) / 1609.34 : unit === 'km' ? Number(reps[2]) * 0.621371 : Number(reps[2]);
    return round1(Number(reps[1]) * each + 2);
  }
  const minutes = text.match(/(\d+)\s*min/i);
  if (minutes) return round1(Number(minutes[1]) / (paceMinutes || 9.5) + 2);
  return 0;
};

/* THE WEEK'S RUNNING IS ARITHMETIC, NOT PROSE. Two things were wrong and they
   compounded: the model wrote ONE easyMinutes for every easy day, so four
   different days all read "45 min"; and nothing ever checked that the pieces
   summed to the week's stated mileage. A 15.5-mile week was really scheduling
   5 + 5.8 + 4 x 4.7 = 29.6 miles — double its own header and past the 25-mile
   ceiling the athlete set.

   So the volume is computed here instead: a weekly target that ramps from
   what the athlete currently runs toward their stated maximum (deload on each
   wave's 2-rep week), a long run held to a sane share of it, the quality
   session measured from its own description, and the remainder split across
   the easy days as DISTANCES at the athlete's easy pace. mileage is then set
   to what was actually scheduled, so the number on the card is the sum of the
   runs under it. */
export function resolveWeekRunning<T extends AiPlanWeek>(
  week: T,
  splitDays: SplitDayRef[],
  athlete: RunningAthlete,
  block?: { weekIndex?: number; blockWeeks?: number },
): T {
  const runningDays = Math.max(0, Math.min(7, Math.round(Number(athlete.runningDays) || 0)));
  const floorMiles = Number(athlete.minWeeklyMileage) || 0;
  const ceilingMiles = Number(athlete.maxWeeklyMileage) || 0;
  /* A block with no running at all is a strength-only block — leave it. */
  if (!runningDays || !(Number(week.mileage) || 0)) return week;

  /* Which days run: the plan's long run and quality keep their days, and the
     rest of the athlete's stated run days are easy, never a rest day. */
  const isRest = (day: SplitDayRef) => /rest/i.test(String(day.type ?? day.dayType ?? '')) || /^\s*rest\b/i.test(day.name);
  /* A run only counts toward the week if its day is actually in the week. On a
     rolling cycle that is not 7 days long the days rotate, so the long run can
     sit outside a given week — counting it there is what made the header claim
     miles the schedule never showed. */
  const present = (name?: string) => Boolean(name) && splitDays.some(day => day.name === name);
  const hasLong = Number(week.longRunMiles) > 0 && present(week.longRunDay);
  const hasQuality = Boolean(week.quality) && !/no goal/i.test(week.quality) && present(week.qualityDay);
  const taken = new Set([hasLong ? week.longRunDay : '', hasQuality ? week.qualityDay : ''].filter(Boolean));
  const needed = Math.max(0, runningDays - (hasLong ? 1 : 0) - (hasQuality ? 1 : 0));
  const kept = (week.easyDays || []).filter(name => splitDays.some(day => day.name === name) && !taken.has(name));
  const fill = splitDays.filter(day => !isRest(day) && !taken.has(day.name) && !kept.includes(day.name)).map(day => day.name);
  const easyDays = [...kept, ...fill].slice(0, needed);

  /* The weekly target: start from what they actually run now and climb toward
     the ceiling they set, so a block finishes at the top of their range
     instead of hovering near the floor. Every wave's 2-rep week deloads. */
  const weekIndex = Math.max(0, Number(block?.weekIndex) || 0);
  const blockWeeks = Math.max(1, Number(block?.blockWeeks) || 10);
  const clampMiles = (value: number) => {
    const high = ceilingMiles ? Math.min(value, ceilingMiles) : value;
    return floorMiles ? Math.max(high, floorMiles) : high;
  };
  const startMiles = clampMiles(Number(athlete.weeklyMileage) || floorMiles || Number(week.mileage) || 0);
  const progress = blockWeeks > 1 ? Math.min(1, weekIndex / (blockWeeks - 1)) : 0;
  const climb = ceilingMiles ? startMiles + (ceilingMiles - startMiles) * progress : startMiles;
  const target = clampMiles(round1(weekIndex % 5 === 3 ? climb * 0.8 : climb));

  const pace = paceToMinutes(week.easyPace) || 9.5;
  /* The long run is a share of the week, not an independent number. */
  const longRunMiles = hasLong ? round1(Math.min(Math.max(Number(week.longRunMiles), target * 0.25), target * 0.35)) : 0;
  const qualityMiles = hasQuality ? qualitySessionMiles(String(week.quality), pace) : 0;

  /* Whatever is left is easy volume, split into real distances. */
  const easyTotal = Math.max(0, round1(target - longRunMiles - qualityMiles));
  const easyRuns: number[] = [];
  if (easyDays.length && easyTotal > 0) {
    const base = Math.max(1, Math.floor((easyTotal / easyDays.length) * 2) / 2);
    for (let index = 0; index < easyDays.length; index++) easyRuns.push(base);
    let spare = round1(easyTotal - base * easyDays.length);
    for (let index = 0; spare >= 0.5 - 1e-9 && index < easyDays.length * 4; index++) {
      easyRuns[index % easyDays.length] = round1(easyRuns[index % easyDays.length] + 0.5);
      spare = round1(spare - 0.5);
    }
  } else if (easyDays.length) {
    for (let index = 0; index < easyDays.length; index++) easyRuns.push(1);
  }

  /* The header equals the sum of what is actually scheduled beneath it. */
  const scheduled = round1(longRunMiles + qualityMiles + easyRuns.reduce((total, miles) => total + miles, 0));
  const easyMinutes = easyRuns.length ? Math.round((easyRuns[0] * pace) / 5) * 5 : 0;
  return { ...week, mileage: scheduled, longRunMiles: longRunMiles || week.longRunMiles, easyDays, easyRuns, easyMinutes };
}

export function wavePrescription(best: number, weekIndex: number, metric = false, bestSingle = 0, tests = false): { weight: number; reps: number; isMax: boolean } {
  const step = metric ? 2.5 : 5;
  const bump = metric ? 3.75 : 7.5;
  const { reps, isMax } = waveSlot(weekIndex);
  /* "A rep higher than last PR by 5-10": a real logged single anchors the
     attempt directly; without one, the estimated max stands in. */
  const attemptWeight = () => {
    const attempt = bestSingle ? bestSingle + bump : (best + bump) / (1 + 1 / 30);
    return Math.max(step, Math.ceil(attempt / step) * step);
  };
  const loadFor = (count: number) => Math.max(step, Math.ceil(best / (1 + count / 30) / step) * step);
  if (isMax) {
    if (tests) return { weight: attemptWeight(), reps: 1, isMax: true };
    /* No goal on this lift: it holds the double it earned. It is not offered
       a single — a max that serves no goal is a max the plan did not ask for. */
    return { weight: loadFor(2), reps: 2, isMax: false };
  }
  return { weight: loadFor(reps), reps, isMax };
}

/* How many plan weeks remain from today. Week 1 starts at startDate. */
export const weeksRemaining = (stored: StoredAiPlan): number => {
  const start = new Date(`${stored.startDate}T12:00:00`).getTime();
  const elapsed = Math.floor((Date.now() - start) / 604800000);
  return stored.plan.weeks.length - elapsed;
};

/* The plan week that covers today (clamped into the block). */
export const currentWeekIndex = (stored: StoredAiPlan): number => {
  const start = new Date(`${stored.startDate}T12:00:00`).getTime();
  const elapsed = Math.floor((Date.now() - start) / 604800000);
  return Math.max(0, Math.min(stored.plan.weeks.length - 1, elapsed));
};
