import { isDemoMode } from '../../lib/env';
import { supabase } from '../../lib/supabase';

/* The AI program: an 8-week block generated by the forge-plan edge function
   from the athlete's goals, split, logged bests, and actual logged running.
   It is stored (Supabase + local cache) and the Plan tab renders FROM STORAGE;
   a new block generates silently when this one runs low or inputs change. */

export type AiPlanTopSet = { splitDay: string; exercise: string; weight: number; reps: number };
export type AiPlanWeek = {
  week: number; phase: 'Base' | 'Build' | 'Peak' | 'Deload' | 'Taper' | 'Race';
  mileage: number; longRunMiles: number; longRunPace: string; longRunDay: string;
  quality: string; qualityPace: string; qualityDay: string;
  easyDays: string[]; easyMinutes: number; easyPace: string;
  topSets: AiPlanTopSet[]; note: string;
};
export type AiPlan = { summary: string; easyPace: string; weeks: AiPlanWeek[] };
export type StoredAiPlan = { plan: AiPlan; generatedAt: string; startDate: string; fingerprint: string; blockWeeks: number };

const localKey = 'forge-ai-plan-v1';

/* Stable fingerprint of everything the program depends on. When it changes
   (goal edited, split day renamed, exercises remapped), the block regenerates. */
export const planFingerprint = (input: unknown) => {
  const text = JSON.stringify(input);
  let hash = 0;
  for (let index = 0; index < text.length; index++) { hash = ((hash << 5) - hash + text.charCodeAt(index)) | 0; }
  return String(hash);
};

const readLocal = (): StoredAiPlan | null => { try { return JSON.parse(localStorage.getItem(localKey) || 'null'); } catch { return null; } };
/* Synchronous cache read for surfaces (Today, Coach) that align to the plan. */
export const readLocalAiPlan = readLocal;
const writeLocal = (stored: StoredAiPlan) => { try { localStorage.setItem(localKey, JSON.stringify(stored)); } catch { /* full */ } };

export async function loadStoredAiPlan(hasUser: boolean): Promise<StoredAiPlan | null> {
  const local = readLocal();
  if (isDemoMode || !hasUser) return local;
  try {
    const { data } = await supabase.from('training_plans').select('payload,generated_at').maybeSingle();
    if (data?.payload) {
      const stored = data.payload as StoredAiPlan;
      writeLocal(stored);
      return stored;
    }
  } catch { /* fall back to local */ }
  return local;
}

export async function saveStoredAiPlan(stored: StoredAiPlan, hasUser: boolean): Promise<void> {
  writeLocal(stored);
  window.dispatchEvent(new Event('forge-ai-plan-changed'));
  if (isDemoMode || !hasUser) return;
  try {
    const { data: userData } = await supabase.auth.getUser();
    if (!userData.user) return;
    await supabase.from('training_plans').upsert({ owner_id: userData.user.id, payload: stored, horizon_weeks: stored.blockWeeks, generated_at: stored.generatedAt }, { onConflict: 'owner_id' });
    /* Every block is kept — regeneration never destroys the record of what
       the program used to prescribe. */
    await supabase.from('training_plan_history').insert({ owner_id: userData.user.id, payload: stored, generated_at: stored.generatedAt });
  } catch { /* local copy still stands */ }
}

export async function generateAiPlan(context: Record<string, unknown>): Promise<AiPlan> {
  const { data, error } = await supabase.functions.invoke('forge-plan', { body: { context } });
  if (error || !data?.plan?.weeks?.length) {
    let detail = 'The plan service did not return a program.';
    const response = (error as { context?: Response } | null)?.context;
    if (response) { try { const body = await response.clone().json(); if (typeof body?.error === 'string') detail = body.error; } catch { /* keep default */ } }
    throw new Error(detail);
  }
  return data.plan as AiPlan;
}

/* ── The 8/6/4/2 wave, shared by every surface ────────────────────────────
   Weeks cycle 8 → 6 → 4 → 2(max attempt). Weights always derive from the
   athlete's CURRENT best calculated max, so the plan reacts to what they
   actually log: beat a prescription and everything scales up; miss one and
   the wave holds steady instead of assuming progress. Max week attempts the
   PR + ~5-10 lb (2.5 kg steps for metric athletes). */
/* Preston's system: a 5-WEEK wave — 8, 6, 4, 2, then MAX WEEK (a true 1RM
   attempt). The running deload lands on the 2-rep week so the max attempt
   always follows a lighter week. */
export const WAVE_REPS = [8, 6, 4, 2, 1] as const;
export const WAVE_LENGTH = WAVE_REPS.length;
export const waveSlot = (weekIndex: number) => ({ reps: WAVE_REPS[weekIndex % WAVE_LENGTH], isMax: weekIndex % WAVE_LENGTH === WAVE_LENGTH - 1 });
/* Max week is a TRUE 1RM attempt — strength goals track Real 1RM, which only
   a 1-rep set can register. The attempt targets the current best + 5-10 lb
   (2.5 kg steps for metric athletes). */
export function wavePrescription(best: number, weekIndex: number, metric = false, bestSingle = 0): { weight: number; reps: number; isMax: boolean } {
  const step = metric ? 2.5 : 5;
  const bump = metric ? 3.75 : 7.5;
  const { reps, isMax } = waveSlot(weekIndex);
  if (isMax) {
    /* "A rep higher than last PR by 5-10": a real logged single anchors the
       attempt directly; without one, the estimated max stands in. */
    const attempt = bestSingle ? bestSingle + bump : (best + bump) / (1 + 1 / 30);
    return { weight: Math.max(step, Math.ceil(attempt / step) * step), reps: 1, isMax };
  }
  const weight = Math.max(step, Math.ceil(best / (1 + reps / 30) / step) * step);
  return { weight, reps, isMax };
}

/* How many plan weeks remain from today. Week 1 starts at startDate. */
export const weeksRemaining = (stored: StoredAiPlan): number => {
  const start = new Date(`${stored.startDate}T12:00:00`).getTime();
  const elapsed = Math.floor((Date.now() - start) / 604800000);
  return stored.plan.weeks.length - elapsed;
};

/* The plan week that covers today (clamped into the block). */
export const currentWeekIndex = (stored: StoredAiPlan): number => {
  const start = new Date(`${stored.startDate}T12:00:00`).getTime();
  const elapsed = Math.floor((Date.now() - start) / 604800000);
  return Math.max(0, Math.min(stored.plan.weeks.length - 1, elapsed));
};
