import { createContext, ReactNode, useContext, useEffect, useMemo, useRef, useState } from 'react';
import type { CardioLogDraft } from '../../lib/cardioSession';
import { isDemoMode } from '../../lib/env';
import { useAuth } from '../auth/AuthProvider';
import { deleteWorkoutDay,loadWorkoutHistory,saveWorkoutDay } from './workoutHistoryService';

export type LoggedTopSet = { id?:string; recommendationTopSetId?:string; muscle:string; lift:string; weight:number; reps:number; calculatedMax?:number; completed?:boolean };
export type WorkoutRecord = { id:string; date:string; title:string; muscles:string[]; topSets?:LoggedTopSet[]; lift?:string; weight?:number; reps?:number; calculatedMax?:number; hasCardio:boolean; cardioSessions?:CardioLogDraft[]; effort?:string; notes?:string; bodyWeight?:number; recommendationId?:string; selectedRecommendationTopSetIds?:string[]; splitId?:string; splitDayId?:string; splitPosition?:number };
const seedRecords:WorkoutRecord[]=[];
type AddResult={ok:true;record:WorkoutRecord}|{ok:false;duplicate:WorkoutRecord};
type UpdateResult={ok:true;record:WorkoutRecord}|{ok:false;missing:true};
type HistoryValue={records:WorkoutRecord[];loading:boolean;syncing:boolean;syncError:string|null;retrySync:()=>void;addRecord:(record:Omit<WorkoutRecord,'id'>)=>AddResult;updateRecord:(id:string,record:Omit<WorkoutRecord,'id'>)=>UpdateResult;deleteRecord:(id:string)=>Promise<boolean>};
const HistoryContext=createContext<HistoryValue|null>(null);
const storageKey='forge-workout-history-v1';
const cardioSignature=(sessions:CardioLogDraft[]|undefined)=>JSON.stringify(sessions||[],(key,value)=>key==='id'?undefined:value);
const normalizedTopSets=(record:Partial<WorkoutRecord>):LoggedTopSet[]=>Array.isArray(record.topSets)&&record.topSets.length?record.topSets.filter(set=>set&&set.lift).map(set=>({...set,muscle:set.muscle||record.muscles?.[0]||'Primary',weight:Number(set.weight),reps:Number(set.reps),completed:set.completed!==false})):(record.lift&&record.weight&&record.reps?[{muscle:record.muscles?.[0]||'Primary',lift:record.lift,weight:Number(record.weight),reps:Number(record.reps),calculatedMax:record.calculatedMax,completed:true}]:[]);
const normalizeRecord=<T extends Partial<WorkoutRecord>>(record:T)=>{const topSets=normalizedTopSets(record);const first=topSets[0];return{...record,topSets:topSets.length?topSets:undefined,lift:first?.lift??record.lift,weight:first?.weight??record.weight,reps:first?.reps??record.reps,calculatedMax:first?.calculatedMax??record.calculatedMax}};
const setSignature=(set:LoggedTopSet)=>`${set.muscle}|${set.lift}|${set.weight}|${set.reps}`;
const mergeDay=(existing:WorkoutRecord,incoming:Partial<WorkoutRecord>):WorkoutRecord=>{const incomingSets=normalizedTopSets(incoming);const combinedSets=[...normalizedTopSets(existing)];incomingSets.forEach(set=>{if(!combinedSets.some(saved=>setSignature(saved)===setSignature(set)))combinedSets.push(set)});const cardio=[...(existing.cardioSessions||[])];(incoming.cardioSessions||[]).forEach(session=>{if(!cardio.some(saved=>saved.id===session.id&&cardioSignature([saved])===cardioSignature([session])))cardio.push(session)});const first=combinedSets[0];const incomingTitle=String(incoming.title||'');const title=incomingTitle&&!incomingTitle.startsWith('Top set ·')?incomingTitle:existing.title.startsWith('Top set ·')?'Training day':existing.title;const selectedRecommendationTopSetIds=[...new Set([...(existing.selectedRecommendationTopSetIds||[]),...(incoming.selectedRecommendationTopSetIds||[])])];return{...existing,...incoming,id:existing.id,date:existing.date,title,muscles:[...new Set([...existing.muscles,...(incoming.muscles||[])])],topSets:combinedSets.length?combinedSets:undefined,lift:first?.lift,weight:first?.weight,reps:first?.reps,calculatedMax:first?.calculatedMax,hasCardio:Boolean(existing.hasCardio||incoming.hasCardio||cardio.length),cardioSessions:cardio.length?cardio:undefined,notes:[existing.notes,incoming.notes].filter((value,index,all)=>value&&all.indexOf(value)===index).join('\n')||undefined,effort:incoming.effort||existing.effort,bodyWeight:incoming.bodyWeight||existing.bodyWeight,selectedRecommendationTopSetIds:selectedRecommendationTopSetIds.length?selectedRecommendationTopSetIds:undefined}};
const consolidateDays=(items:WorkoutRecord[])=>{const days=new Map<string,WorkoutRecord>();items.sort((a,b)=>b.date.localeCompare(a.date)).forEach(record=>{const existing=days.get(record.date);days.set(record.date,existing?mergeDay(existing,record):record)});return [...days.values()].sort((a,b)=>b.date.localeCompare(a.date))};
export function WorkoutHistoryProvider({children}:{children:ReactNode}){
  const {user}=useAuth();
  const [records,setRecords]=useState<WorkoutRecord[]>(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');const migrated=Array.isArray(saved)?saved.filter(item=>item&&typeof item==='object').map((item,index)=>normalizeRecord({...item,id:String(item.id||`migrated-${index}`),date:String(item.date||new Date().toISOString().slice(0,10)),title:String(item.title||'Completed workout'),muscles:Array.isArray(item.muscles)?item.muscles:[],hasCardio:Boolean(item.hasCardio),cardioSessions:Array.isArray(item.cardioSessions)?item.cardioSessions:undefined}) as WorkoutRecord):seedRecords;const consolidated=consolidateDays(migrated);localStorage.setItem(storageKey,JSON.stringify(consolidated));return consolidated}catch{return seedRecords}});
  const [loading,setLoading]=useState(!isDemoMode);const [syncing,setSyncing]=useState(false);const [syncError,setSyncError]=useState<string|null>(null);const pendingSync=useRef<WorkoutRecord|null>(null);const syncQueue=useRef<Promise<void>>(Promise.resolve());
  useEffect(()=>{if(isDemoMode||!user){setLoading(false);return}let active=true;setLoading(true);void loadWorkoutHistory().then(remote=>{if(!active)return;setRecords(remote);localStorage.setItem(storageKey,JSON.stringify(remote));setSyncError(null)}).catch(error=>{if(active)setSyncError(error instanceof Error?error.message:'Could not load workout history.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user]);
  const persist=(record:WorkoutRecord)=>{if(isDemoMode||!user)return;pendingSync.current=record;setSyncing(true);setSyncError(null);const operation=syncQueue.current.catch(()=>undefined).then(()=>saveWorkoutDay(record)).then(()=>{if(pendingSync.current===record)pendingSync.current=null;setSyncError(null);window.dispatchEvent(new Event('forge-training-cycle-changed'))});syncQueue.current=operation.then(()=>undefined,()=>undefined);void operation.catch(error=>setSyncError(error instanceof Error?error.message:'Could not sync this training day.')).finally(()=>{if(!pendingSync.current)setSyncing(false)})};
  const value=useMemo<HistoryValue>(()=>({records,loading,syncing,syncError,retrySync:()=>{if(pendingSync.current)persist(pendingSync.current);else if(!isDemoMode&&user){setLoading(true);void loadWorkoutHistory().then(remote=>{setRecords(remote);localStorage.setItem(storageKey,JSON.stringify(remote));setSyncError(null)}).catch(error=>setSyncError(error instanceof Error?error.message:'Could not load workout history.')).finally(()=>setLoading(false))}},addRecord:(draft)=>{
    const normalized=normalizeRecord(draft);const sameDay=records.find(item=>item.date===draft.date);const incomingSets=normalizedTopSets(normalized);const duplicate=sameDay&&incomingSets.length>0&&incomingSets.every(set=>normalizedTopSets(sameDay).some(saved=>setSignature(saved)===setSignature(set)))&&!draft.cardioSessions?.length?sameDay:undefined;
    if(duplicate)return {ok:false,duplicate};
    const record=sameDay?mergeDay(sameDay,normalized):({...normalized,id:`day-${draft.date}-${Date.now()}`} as WorkoutRecord);const next=(sameDay?records.map(item=>item.id===sameDay.id?record:item):[record,...records]).sort((a,b)=>b.date.localeCompare(a.date));setRecords(next);localStorage.setItem(storageKey,JSON.stringify(next));persist(record);return {ok:true,record};
  },updateRecord:(id,draft)=>{
    if(!records.some(item=>item.id===id))return {ok:false,missing:true};
    const record={...normalizeRecord(draft),id} as WorkoutRecord;
    const next=records.map(item=>item.id===id?record:item).sort((a,b)=>b.date.localeCompare(a.date));
    setRecords(next);localStorage.setItem(storageKey,JSON.stringify(next));persist(record);return {ok:true,record};
  },deleteRecord:async(id)=>{if(!records.some(item=>item.id===id))return false;try{if(!isDemoMode&&user)await deleteWorkoutDay(id);const next=records.filter(item=>item.id!==id);setRecords(next);localStorage.setItem(storageKey,JSON.stringify(next));setSyncError(null);window.dispatchEvent(new Event('forge-training-cycle-changed'));return true}catch(error){setSyncError(error instanceof Error?error.message:'Could not delete this training day.');return false}
  }}),[records,loading,syncing,syncError,user]);
  return <HistoryContext.Provider value={value}>{children}</HistoryContext.Provider>;
}
export function useWorkoutHistory(){const value=useContext(HistoryContext);if(!value)throw new Error('Workout history provider missing');return value}
