import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import { normalizeMuscleGroups } from '../../lib/muscleGroups';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../auth/AuthProvider';

export type AthleteSetup = {
  displayName:string; username:string; birthDate:string; units:'Imperial'|'Metric'; height:string;
  startingWeight:string; currentWeight:string; primaryFocus:'Strength'|'Endurance'|'Body composition'|'Hybrid';
  strengthExperience:'Beginner'|'Intermediate'|'Advanced'|'Competitive'; runningExperience:'New'|'Recreational'|'Experienced'|'Competitive';
  trainingDays:number; runningDays:number; weeklyMileage:number; longestRun:number; strengthSessionMinutes:number; cardioSessionMinutes:number; combinedSessionMinutes:number;
  minWeeklyMileage?:number; maxWeeklyMileage?:number;
  scheduleStyle:'Rolling cycle'|'Weekly schedule'; equipment:string; environment:'Road'|'Track'|'Trail'|'Treadmill'|'Mixed';
  splitSource:'Recommended'|'Custom'; splitDays:Array<{name:string;type:'Strength'|'Cardio'|'Mixed'|'Rest';muscles?:string[]}>;
  injuryConstraint:boolean; limitationNotes:string; wearableIntent:'Connect now'|'Connect later'|'Manual only';
  profileVisibility:'Private'|'Friends only'; acceptedSafety:boolean; completedAt:string;
};

const legacyStorageKey='forge-athlete-setup-v1';
const storageKey=(userId:string)=>`${legacyStorageKey}:${userId}`;
const setupDefaults:AthleteSetup={displayName:'Athlete',username:'',birthDate:'',units:'Imperial',height:'',startingWeight:'',currentWeight:'',primaryFocus:'Hybrid',strengthExperience:'Intermediate',runningExperience:'Recreational',trainingDays:4,runningDays:3,weeklyMileage:0,longestRun:0,strengthSessionMinutes:60,cardioSessionMinutes:45,combinedSessionMinutes:75,scheduleStyle:'Rolling cycle',equipment:'',environment:'Mixed',splitSource:'Recommended',splitDays:[{name:'Upper Strength',type:'Strength',muscles:['Chest','Back','Shoulders','Biceps','Triceps']},{name:'Lower Strength',type:'Strength',muscles:['Quads','Hamstrings','Glutes']},{name:'Conditioning',type:'Cardio',muscles:[]},{name:'Recovery',type:'Rest',muscles:[]}],injuryConstraint:false,limitationNotes:'',wearableIntent:'Connect later',profileVisibility:'Private',acceptedSafety:false,completedAt:''};
const normalizeSetup=(value:unknown):AthleteSetup|null=>{if(!value||typeof value!=='object')return null;const saved=value as Partial<AthleteSetup>;const splitDays=Array.isArray(saved.splitDays)&&saved.splitDays.length?saved.splitDays.map(day=>({...day,muscles:Array.isArray(day.muscles)?day.muscles:[]})):setupDefaults.splitDays;return{...setupDefaults,...saved,splitDays,units:saved.units==='Metric'?'Metric':'Imperial'}};
type Value={setup:AthleteSetup|null;completed:boolean;loading:boolean;saveSetup:(setup:AthleteSetup)=>void;clearSetup:()=>void};
const Context=createContext<Value|null>(null);

type ProfileRow={username:string|null;display_name:string|null;birth_date:string|null;height_cm:number|null;starting_weight:number|null;current_weight:number|null;unit_system:'imperial'|'metric';experience_level:'beginner'|'intermediate'|'advanced'|'competitive';primary_goal:'strength'|'muscle'|'endurance'|'general_fitness'|'weight_change';equipment:string[]|null;preferred_training_days:number[]|null;onboarding_completed:boolean;updated_at:string};
const readStored=(key:string)=>{try{return normalizeSetup(JSON.parse(localStorage.getItem(key)||'null'))}catch{return null}};
const sameAthlete=(saved:AthleteSetup|null,profile:ProfileRow,userName:string)=>{const a=saved?.displayName.trim().toLowerCase();const b=(profile.display_name||userName).trim().toLowerCase();return Boolean(a&&b&&(a===b||a.split(' ')[0]===b.split(' ')[0]))};
const focusFromProfile=(value:ProfileRow['primary_goal']):AthleteSetup['primaryFocus']=>value==='strength'||value==='muscle'?'Strength':value==='endurance'?'Endurance':value==='weight_change'?'Body composition':'Hybrid';
const experienceFromProfile=(value:ProfileRow['experience_level']):AthleteSetup['strengthExperience']=>`${value[0].toUpperCase()}${value.slice(1)}` as AthleteSetup['strengthExperience'];
const setupFromProfile=(profile:ProfileRow,local:AthleteSetup|null):AthleteSetup=>({...setupDefaults,...(local||{}),username:profile.username||local?.username||'',displayName:profile.display_name||local?.displayName||'Athlete',birthDate:profile.birth_date||local?.birthDate||'',units:profile.unit_system==='metric'?'Metric':'Imperial',height:profile.height_cm?`${profile.height_cm} cm`:(local?.height||''),startingWeight:profile.starting_weight?String(profile.starting_weight):(local?.startingWeight||''),currentWeight:profile.current_weight?String(profile.current_weight):(local?.currentWeight||''),primaryFocus:focusFromProfile(profile.primary_goal),strengthExperience:experienceFromProfile(profile.experience_level),equipment:(profile.equipment||[]).join(', ')||local?.equipment||'',trainingDays:profile.preferred_training_days?.length||local?.trainingDays||4,completedAt:profile.onboarding_completed?(local?.completedAt||profile.updated_at):''});

export function ProfileSetupProvider({children}:{children:ReactNode}){
  const {user}=useAuth();
  const [setup,setSetup]=useState<AthleteSetup|null>(null);
  const [loadedUserId,setLoadedUserId]=useState<string|null>(null);
  const loading=Boolean(user)&&loadedUserId!==user?.id;
  const saveSetup=(next:AthleteSetup)=>{if(user)localStorage.setItem(storageKey(user.id),JSON.stringify(next));setSetup(next)};
  const clearSetup=()=>{if(user)localStorage.removeItem(storageKey(user.id));setSetup(null)};
  useEffect(()=>{let active=true;if(!user){setSetup(null);setLoadedUserId(null);return()=>{active=false}}setSetup(null);setLoadedUserId(null);void supabase.from('profiles').select('username,display_name,birth_date,height_cm,starting_weight,current_weight,unit_system,experience_level,primary_goal,equipment,preferred_training_days,onboarding_completed,updated_at').eq('id',user.id).maybeSingle().then(async({data,error})=>{if(!active)return;if(error||!data){setLoadedUserId(user.id);return}const profile=data as ProfileRow;const scoped=readStored(storageKey(user.id));const legacy=readStored(legacyStorageKey);const matchingLegacy=sameAthlete(legacy,profile,String(user.user_metadata?.full_name||''))?legacy:null;const local=scoped||matchingLegacy;if(!profile.onboarding_completed&&local?.completedAt){await supabase.from('profiles').update({onboarding_completed:true}).eq('id',user.id);profile.onboarding_completed=true}if(!active)return;const next=setupFromProfile(profile,local);if(next.completedAt){localStorage.setItem(storageKey(user.id),JSON.stringify(next));if(matchingLegacy)localStorage.removeItem(legacyStorageKey)}setSetup(next.completedAt?next:null);setLoadedUserId(user.id)});return()=>{active=false}},[user]);
  useEffect(()=>{if(!user||loading)return;let active=true;void supabase.from('training_splits').select('name,training_split_days(position,name,muscle_groups,goal_lifts,cardio_types)').eq('owner_id',user.id).eq('is_active',true).maybeSingle().then(({data,error})=>{if(!active||error||!data)return;const rows=[...(data.training_split_days||[])].sort((a,b)=>a.position-b.position);setSetup(current=>{if(!current)return current;const days=rows.map((day,index)=>{const muscles=normalizeMuscleGroups(day.muscle_groups);const exercises=Array.isArray(day.goal_lifts)?day.goal_lifts:[];const cardio=Array.isArray(day.cardio_types)?day.cardio_types:[];const hasStrength=muscles.length>0||exercises.length>0;const hasCardio=cardio.length>0;const dayType=hasStrength&&hasCardio?'mixed':hasStrength?'strength':hasCardio?'cardio':'rest';const strengthDuration=String(current.strengthSessionMinutes||60);return{name:day.name||`Day ${index+1}`,weekday:['MON','TUE','WED','THU','FRI','SAT','SUN'][index%7],dayType,muscles,exercises,cardioPolicy:hasCardio?'forge':'none',cardio:[],recoveryStyle:'Full rest',strengthDuration,maxDuration:dayType==='cardio'?String(current.cardioSessionMinutes||45):strengthDuration}});localStorage.setItem('forge-training-plan-v1',JSON.stringify({name:data.name,rhythm:current.scheduleStyle==='Weekly schedule'?'weekly':'rolling',days}));const next={...current,splitSource:'Custom' as const,trainingDays:days.filter(day=>day.dayType!=='rest').length,splitDays:days.map(day=>({name:day.name,type:(day.dayType[0].toUpperCase()+day.dayType.slice(1)) as 'Strength'|'Cardio'|'Mixed'|'Rest',muscles:day.muscles}))};localStorage.setItem(storageKey(user.id),JSON.stringify(next));return next})});return()=>{active=false}},[user,loading]);
  return <Context.Provider value={{setup,completed:Boolean(setup?.completedAt),loading,saveSetup,clearSetup}}>{children}</Context.Provider>;
}
export function useProfileSetup(){const value=useContext(Context);if(!value)throw new Error('useProfileSetup must be used inside ProfileSetupProvider');return value}
