import { useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageIntro } from '../components/AppShell';
import { useWorkoutHistory, type WorkoutRecord } from '../features/training/WorkoutHistoryProvider';
import { useProfileSetup } from '../features/profile/ProfileSetupProvider';
import { calculateEstimatedOneRepMax } from '../lib/strength';
import { cardioMiles, formatCardioSummary as baseCardioSummary, type CardioLogDraft } from '../lib/cardioSession';

const formatDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const formatCardioSummary=(session:CardioLogDraft)=>{const summary=baseCardioSummary(session);const distance=summary.match(/(\d+(?:\.\d+)?)\s*mi(?:les?)?\b/i);const duration=summary.match(/\b(\d{1,2}:\d{2}(?::\d{2})?)\b/);if(!distance||!duration)return summary;const parts=duration[1].split(':').map(Number);const seconds=parts.length===3?parts[0]*3600+parts[1]*60+parts[2]:parts[0]*60+parts[1];const paceSeconds=Math.round(seconds/Number(distance[1]));if(!Number.isFinite(paceSeconds)||paceSeconds<=0)return summary;const pace=`${Math.floor(paceSeconds/60)}:${String(paceSeconds%60).padStart(2,'0')} /mi`;const withoutBadPace=summary.replace(/\s*·\s*PACE\s+(?=\d+(?:\.\d+)?\s*mi(?:les?)?\b)/i,' · ');const unlabeledSuffix=` · ${pace}`;const clean=withoutBadPace.endsWith(unlabeledSuffix)?withoutBadPace.slice(0,-unlabeledSuffix.length):withoutBadPace;return`${clean} · PACE ${pace}`};
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const iso=(year:number,month:number,day:number)=>`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
const nonStrengthMuscles=new Set(['cardio','none','rest','n/a','na']);
const strengthMuscles=(record:WorkoutRecord)=>record.muscles.filter(muscle=>{const normalized=muscle.trim().toLowerCase();return normalized&&!nonStrengthMuscles.has(normalized)});

export function HistoryPage(){
  const {records}=useWorkoutHistory();const {setup}=useProfileSetup();const weightUnit=setup?.units==='Metric'?'kg':'lb';const now=new Date();
  const recordTopSets=(record:WorkoutRecord)=>record.topSets?.length?record.topSets.filter(set=>set.completed!==false):(record.lift&&record.weight&&record.reps?[{muscle:record.muscles[0]||'Primary',lift:record.lift,weight:record.weight,reps:record.reps,calculatedMax:record.calculatedMax}]:[]);
  const hasStrength=(record:WorkoutRecord)=>strengthMuscles(record).length>0||recordTopSets(record).length>0;
  const hasCardio=(record:WorkoutRecord)=>(record.cardioSessions||[]).length>0;
  const hasTraining=(record:WorkoutRecord)=>hasStrength(record)||hasCardio(record);
  const trainingRecords=records.filter(hasTraining);
  const [selectedId,setSelectedId]=useState(trainingRecords[0]?.id??'');const [selectedDate,setSelectedDate]=useState(trainingRecords[0]?.date??iso(now.getFullYear(),now.getMonth(),now.getDate()));const [query,setQuery]=useState('');const [cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1));const selected=records.find(record=>record.id===selectedId&&record.date===selectedDate);const year=cursor.getFullYear(),month=cursor.getMonth(),days=new Date(year,month+1,0).getDate(),leading=(new Date(year,month,1).getDay()+6)%7;
  const activeDateKinds=trainingRecords.reduce((map,record)=>{const current=map.get(record.date)||{strength:false,cardio:false};map.set(record.date,{strength:current.strength||hasStrength(record),cardio:current.cardio||hasCardio(record)});return map},new Map<string,{strength:boolean;cardio:boolean}>());
  const cursorMonthPrefix=`${year}-${String(month+1).padStart(2,'0')}`;const monthRecords=records.filter(record=>record.date.startsWith(cursorMonthPrefix));
  const shownRecords=useMemo(()=>{const term=query.trim().toLowerCase();return term?trainingRecords.filter(record=>`${record.date} ${record.title} ${record.lift??''} ${(record.topSets||[]).map(set=>`${set.muscle} ${set.lift}`).join(' ')} ${record.muscles.join(' ')} ${(record.cardioSessions||[]).map(formatCardioSummary).join(' ')}`.toLowerCase().includes(term)):trainingRecords},[query,trainingRecords]);
  const cardioSummary=(record:WorkoutRecord)=>record.cardioSessions?.length?record.cardioSessions.map(formatCardioSummary).join(' · '):'—';
  const monthStrengthDays=new Set(monthRecords.filter(hasStrength).map(record=>record.date)).size;const monthCardioDays=new Set(monthRecords.filter(hasCardio).map(record=>record.date)).size;const monthMiles=monthRecords.reduce((total,record)=>total+(record.cardioSessions||[]).reduce((sum,session)=>sum+cardioMiles(session),0),0);const monthWeights=monthRecords.map(record=>record.bodyWeight).filter((value):value is number=>typeof value==='number'&&value>0);const monthAverageWeight=monthWeights.length?monthWeights.reduce((sum,value)=>sum+value,0)/monthWeights.length:null;
  const dayGroups=useMemo(()=>{const groups=new Map<string,WorkoutRecord[]>();shownRecords.forEach(record=>groups.set(record.date,[...(groups.get(record.date)||[]),record]));return [...groups.entries()].sort(([a],[b])=>b.localeCompare(a)).map(([date,items])=>({date,items,topSets:items.flatMap(record=>recordTopSets(record).map(set=>({...set,recordId:record.id}))),cardio:items.flatMap(record=>(record.cardioSessions||[]).map(session=>({...session,recordId:record.id})))}))},[shownRecords]);
  const calendarTouchStart=useRef<number|null>(null);
  const streaks=useMemo(()=>{const activeDays=[...new Set(trainingRecords.map(record=>record.date))].sort();if(!activeDays.length)return{current:0,best:0};const dayNumber=(date:string)=>Math.floor(new Date(`${date}T12:00:00`).getTime()/86400000);let best=1,run=1;for(let index=1;index<activeDays.length;index+=1){run=dayNumber(activeDays[index])-dayNumber(activeDays[index-1])===1?run+1:1;best=Math.max(best,run)}let current=1;for(let index=activeDays.length-1;index>0;index-=1){if(dayNumber(activeDays[index])-dayNumber(activeDays[index-1])!==1)break;current+=1}const latestGap=dayNumber(iso(now.getFullYear(),now.getMonth(),now.getDate()))-dayNumber(activeDays[activeDays.length-1]);return{current:latestGap<=1?current:0,best}},[trainingRecords,now]);
  const topSet=(record:WorkoutRecord)=>recordTopSets(record).length?recordTopSets(record).map(set=>`${set.muscle}: ${set.lift} · ${set.weight} ${weightUnit} × ${set.reps}`).join(' | '):'—';
  const selectRecord=(record:WorkoutRecord)=>{setSelectedId(record.id);setSelectedDate(record.date);const date=new Date(`${record.date}T12:00:00`);setCursor(new Date(date.getFullYear(),date.getMonth(),1))};const selectDate=(date:string)=>{setSelectedDate(date);const record=trainingRecords.find(item=>item.date===date);setSelectedId(record?.id||'')};const selectedHasTraining=selected?hasTraining(selected):false;const shiftMonth=(change:number)=>setCursor(new Date(year,month+change,1));
  const dayHistory=<section className="history-day-groups"><header><div><span className="eyebrow">TRAINING DAYS</span><h2>Completed results by day</h2><p>Repeated top-set attempts stay together. Forge highlights the strongest result for each exercise.</p></div><label><span>Search</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Exercise, muscle, cardio, or date"/></label></header>{dayGroups.map(group=>{const strongest=group.topSets.reduce<Record<string,number>>((best,set)=>{const max=set.calculatedMax||calculateEstimatedOneRepMax(set.weight,set.reps)||set.weight;return{...best,[set.lift]:Math.max(best[set.lift]||0,max)}},{});const attempts=[...group.topSets].reverse();return <details className="history-day-card" open={selected?.date===group.date} key={group.date}><summary onClick={()=>group.items[0]&&selectRecord(group.items[0])}><div><strong>{formatDate(group.date)}</strong><small>{group.topSets.length} top {group.topSets.length===1?'set':'sets'} · {group.cardio.length} cardio {group.cardio.length===1?'entry':'entries'}</small></div><span>{[...new Set(group.items.flatMap(record=>record.muscles).filter(muscle=>muscle!=='Cardio'))].join(' · ')||'Cardio'}</span><b>View day</b></summary><div className="history-day-body">{attempts.length>0&&<section><span className="field-caption">TOP-SET ATTEMPTS</span>{attempts.map((set,index)=>{const max=set.calculatedMax||calculateEstimatedOneRepMax(set.weight,set.reps)||set.weight;const attemptNumber=attempts.slice(0,index+1).filter(item=>item.lift===set.lift).length;return <article className={max===strongest[set.lift]?'strongest':''} key={`${set.recordId}-${set.lift}-${index}`}><div><strong>{set.lift}</strong><small>{set.muscle} · Attempt {attemptNumber}</small></div><b>{set.weight} {weightUnit} ×{set.reps}</b><span>Calculated max {max} {weightUnit}</span>{max===strongest[set.lift]&&<em>Strongest</em>}</article>})}</section>}{group.cardio.length>0&&<section><span className="field-caption">CARDIO</span>{group.cardio.map(session=><article key={`${session.recordId}-${session.id}`}><div><strong>{session.activity}</strong><small>{session.structure}</small></div><span>{formatCardioSummary(session)}</span></article>)}</section>}<Link className="button ghost" to={`/workout?edit=${group.items[0].id}`}>Edit day</Link></div></details>})}{!dayGroups.length&&<div className="history-table-empty">No completed results match this search.</div>}</section>;

  return <div className="stack-xl history-page">
    <PageIntro eyebrow="TRAINING HISTORY" title="Every completed workout" copy="Select a calendar day or table row to review the session."/>
    {records.length?<>
      <section className="classic-streak"><span className="section-title">ACTIVITY STREAK</span><div><article><strong>{streaks.current}</strong><span>Day streak</span></article><article><strong>{streaks.best}</strong><span>Best streak</span></article></div></section>
      <section className="card history-calendar restored-calendar classic-calendar" onTouchStart={event=>{calendarTouchStart.current=event.touches[0]?.clientX??null}} onTouchEnd={event=>{if(calendarTouchStart.current===null)return;const distance=(event.changedTouches[0]?.clientX??calendarTouchStart.current)-calendarTouchStart.current;calendarTouchStart.current=null;if(Math.abs(distance)>55)shiftMonth(distance<0?1:-1)}}><div className="history-toolbar"><button onClick={()=>shiftMonth(-1)} aria-label="Previous month">‹</button><div><span className="eyebrow">CALENDAR</span><h3>{months[month]} {year}</h3><small>Tap a day · swipe to change month</small></div><button onClick={()=>shiftMonth(1)} aria-label="Next month">›</button></div><div className="history-summary calendar-kpis"><div><strong>{monthMiles.toFixed(1)}</strong><span>Miles</span></div><div><strong>{monthStrengthDays}</strong><span>Lifts</span></div><div><strong>{monthCardioDays}</strong><span>Cardio</span></div><div><strong>{monthAverageWeight===null?'—':monthAverageWeight.toFixed(1)}</strong><span>Avg Wt</span></div></div><div className="weekday-row">{['MO','TU','WE','TH','FR','SA','SU'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({length:leading}).map((_,index)=><i key={`empty-${index}`}/>)}{Array.from({length:days},(_,index)=>index+1).map(day=>{const date=iso(year,month,day);const activity=activeDateKinds.get(date);const trained=Boolean(activity);return <button key={date} className={`${trained?'trained ':''}${selectedDate===date?'selected':''}`} onClick={()=>selectDate(date)} aria-label={`${formatDate(date)}${trained?' — preview training day':' — preview empty day'}`}><span>{day}</span>{activity&&<span className="calendar-markers">{activity.strength&&<i className="strength"/>}{activity.cardio&&<i className="cardio"/>}</span>}</button>})}</div><div className="calendar-legend"><span><i className="strength"/>Lift</span><span><i className="cardio"/>Cardio</span></div></section>
      <section className="card simple-day-preview"><header><div><span className="eyebrow">SELECTED DAY</span><h2>{formatDate(selectedDate)}</h2></div><Link className="button" to={selectedHasTraining&&selected?`/workout?edit=${selected.id}`:`/workout?date=${selectedDate}`}>{selectedHasTraining?'Edit day':'Add training'}</Link></header>{selectedHasTraining&&selected?<><p>{strengthMuscles(selected).join(' · ')||(hasCardio(selected)?'Cardio day':'')}</p>{selected.recommendationId&&<small className="recommendation-lineage">Completed from Forge recommendation · split position {selected.splitPosition||'—'}</small>}<div className="simple-preview-results">{recordTopSets(selected).map((set,index)=><div key={`${set.lift}-${index}`}><strong>{set.lift}</strong><span>{set.weight} {weightUnit} ×{set.reps}</span></div>)}{recordTopSets(selected).length===0&&strengthMuscles(selected).length>0&&<div><strong>Strength workout</strong><span>{strengthMuscles(selected).join(' · ')} · no historical top set recorded</span></div>}{(selected.cardioSessions||[]).map(session=><div key={session.id}><strong>{session.activity}</strong><span>{formatCardioSummary(session)}</span></div>)}</div>{selected.notes&&<aside className="selected-day-notes"><span className="eyebrow">NOTES</span><p>{selected.notes}</p></aside>}</>:<p>No training is logged for this date.</p>}</section>
      <section className="card history-table-card"><header><div><span className="eyebrow">ALL WORKOUTS</span><h2>History</h2><small>{shownRecords.length} of {trainingRecords.length} sessions</small></div><label><span>Search</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Exercise, muscle, cardio, or date"/></label></header><div className="history-table-scroll"><table className="history-data-table"><thead><tr><th>Date</th><th>Muscle group</th><th>Top set</th><th>Cardio</th></tr></thead><tbody>{shownRecords.map(record=><tr className={selected?.id===record.id?'selected':''} onClick={()=>selectRecord(record)} key={record.id} tabIndex={0} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectRecord(record)}}}><td><strong>{formatDate(record.date)}</strong><small>{record.title}</small></td><td>{strengthMuscles(record).length?strengthMuscles(record).join(' · '):'—'}</td><td>{topSet(record)}</td><td>{cardioSummary(record)}</td></tr>)}</tbody></table>{!shownRecords.length&&<div className="history-table-empty">No workouts match that search.</div>}</div></section>
    </>:<section className="card history-first-empty"><strong>Your history starts with your first completed workout.</strong><span>Nothing is prefilled or estimated here—only saved results appear.</span><Link className="button" to="/workout?source=blank">Log a workout →</Link></section>}
  </div>;
}
