import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { PageIntro, Metric } from '../components/AppShell';
import { openCoachBubble } from '../features/training/coachService';
import { athlete, friends, splitDays } from '../data/demo';
import { CardioBuilder } from '../components/CardioBuilder';
import { calculateEstimatedOneRepMax } from '../lib/strength';
import { TopSetHistory } from '../components/TopSetHistory';
import { useWorkoutHistory, type LoggedTopSet, type WorkoutRecord } from '../features/training/WorkoutHistoryProvider';
import { useProfileSetup } from '../features/profile/ProfileSetupProvider';
import { formatCardioSummary, type CardioLogDraft } from '../lib/cardioSession';
import { exerciseCategory, useTrainingLibrary } from '../features/training/TrainingLibraryProvider';
import { LastPerformanceBanner } from '../components/LastPerformance';
import { TopSetCards } from '../components/TopSetCards';
import { useDailyRecommendation } from '../features/training/DailyRecommendationProvider';

function CompletedDayReview({record,unit}:{record:WorkoutRecord;unit:string}) {
  const completedTopSets=(record.topSets||[]).filter(set=>set.completed!==false);
  const topSets=completedTopSets.length?completedTopSets:(record.lift&&record.weight&&record.reps?[{muscle:record.muscles.find(muscle=>muscle!=='Cardio')||'Strength',lift:record.lift,weight:record.weight,reps:record.reps,calculatedMax:record.calculatedMax,completed:true}]:[]);
  const cardio=record.cardioSessions||[];
  if(!topSets.length&&!cardio.length)return null;
  return <div className="completed-day-review-grid">
    {topSets.length>0&&<section className="completed-day-review-block">
      <header><span>TOP SETS</span><b>{topSets.length}</b></header>
      <div className="completed-day-review-list">{topSets.map((set,index)=>{
        const max=set.calculatedMax??calculateEstimatedOneRepMax(set.weight,set.reps);
        return <article key={`${set.lift}-${index}`}><div><strong>{set.lift}</strong><small>{set.muscle}</small></div><div><b>{set.weight} {unit} × {set.reps}</b><small>{set.reps===1?`Real 1RM ${set.weight} ${unit}`:max?`Calculated max ${max} ${unit}`:'Calculated max unavailable'}</small></div></article>;
      })}</div>
    </section>}
    {cardio.length>0&&<section className="completed-day-review-block">
      <header><span>CARDIO</span><b>{cardio.length}</b></header>
      <div className="completed-day-review-list">{cardio.map((session,index)=>{
        /* The row already names the activity on the left, and "steady" is an
           internal structure name, not something an athlete logged. Show the
           measurements only. */
        const detail=formatCardioSummary(session).replace(new RegExp(`^${session.activity.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*·\\s*`),'');
        const lineCount=Array.isArray(session.prescription.legacyIntervals)?(session.prescription.legacyIntervals as unknown[]).length:0;
        return <article key={session.id||`${session.activity}-${index}`}><div><strong>{session.activity||'Cardio'}</strong>{lineCount>1&&<small>{lineCount} lines</small>}</div><div className="completed-cardio-summary"><b>{detail||formatCardioSummary(session)}</b>{session.prescription.note?<small>{String(session.prescription.note)}</small>:null}</div></article>;
      })}</div>
    </section>}
  </div>;
}

export function WorkoutPage() {
  /* The editor initializes its state from the record being edited, so it must
     remount whenever the edit target changes (SPA navigation from the
     completed-day card, History links) or when the record it needs arrives
     from the async history load. Keying the editor handles both. */
  const [searchParams]=useSearchParams();
  const {records,loading}=useWorkoutHistory();
  const editParam=searchParams.get('edit');
  const recordReady=editParam?records.some(record=>record.id===editParam):false;
  if(editParam&&loading&&!recordReady)return <div className="narrow stack-xl"><section className="card"><p className="muted">Loading workout…</p></section></div>;
  return <WorkoutEditor key={`${editParam||'new'}:${recordReady?'1':'0'}:${searchParams.get('date')||''}`}/>;
}

function WorkoutEditor() {
  const navigate=useNavigate();
  const {addRecord,updateRecord,deleteRecord,records}=useWorkoutHistory();
  const {exercises,addExercise}=useTrainingLibrary();
  const {setup}=useProfileSetup();
  const {recommendation,markCompleted}=useDailyRecommendation();
  const weightUnit=setup?.units==='Metric'?'kg':'lb';
  const [searchParams]=useSearchParams();
  const editId=searchParams.get('edit');const editingRecord=editId?records.find(record=>record.id===editId):undefined;
  const today=new Date();const todayIso=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;const requestedDate=searchParams.get('date');const sessionIso=editingRecord?.date||(requestedDate&&/^\d{4}-\d{2}-\d{2}$/.test(requestedDate)?requestedDate:todayIso);const sessionDate=new Date(`${sessionIso}T12:00:00`);const todayLong=sessionDate.toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric',year:'numeric'});const todayShort=sessionDate.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'});
  const completedOnEntry=!editId&&!requestedDate?records.find(record=>record.date===todayIso):undefined;
  const muscleOptions = ['Chest','Back','Shoulders','Quads','Hamstrings','Glutes','Biceps','Triceps','Forearms','Abs','Cardio'];
  const savedPlan=(()=>{try{return JSON.parse(localStorage.getItem('forge-training-plan-v1')||'null') as {days?:Array<{name:string;dayType:string;muscles?:string[];exercises?:string[]}>}|null}catch{return null}})();const savedDays=savedPlan?.days||[];const recommendationIndex=Math.max(0,(recommendation?.splitDay.position||1)-1);const [selectedPlanDay,setSelectedPlanDay]=useState(recommendationIndex);const savedDay=savedDays[selectedPlanDay];const plannedDay=recommendation?{name:recommendation.splitDay.name,type:recommendation.splitDay.type[0].toUpperCase()+recommendation.splitDay.type.slice(1),muscles:recommendation.splitDay.muscles,exercises:recommendation.splitDay.exercises}:savedDay?{name:savedDay.name,type:savedDay.dayType[0].toUpperCase()+savedDay.dayType.slice(1),muscles:savedDay.muscles||[],exercises:savedDay.exercises||[]}:setup?.splitDays.find(day=>day.type!=='Rest');
  const [muscles,setMuscles]=useState<string[]>(editingRecord?.muscles??['Quads','Hamstrings','Glutes']);
  const [workoutSource,setWorkoutSource]=useState<'plan'|'repeat'|'blank'>(searchParams.get('source')==='repeat'?'repeat':searchParams.get('source')==='blank'?'blank':'plan');
  const recentWorkouts=records.slice(0,5).map(record=>({id:record.id,date:new Date(`${record.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}),name:record.title,detail:[record.lift,record.hasCardio?'Cardio':null].filter(Boolean).join(' · ')||'Completed workout',muscles:record.muscles,exercises:(record.topSets||[]).map(set=>set.lift).filter(Boolean),topSets:(record.topSets||[]).filter(set=>set.completed!==false)}));
  const [selectedRecent,setSelectedRecent]=useState(recentWorkouts[0]?.id||'');
  const repeatTopSetsFor=(id:string):LoggedTopSet[]=>{const source=records.find(record=>record.id===id)||records.find(record=>record.id===recentWorkouts[0]?.id);return (source?.topSets||[]).filter(set=>set.completed!==false).map(set=>({muscle:set.muscle,lift:set.lift,weight:0,reps:0,completed:true}))};
  const [manualMuscles,setManualMuscles]=useState(Boolean(editingRecord));
  const [hasCardio,setHasCardio]=useState(Boolean(editingRecord?.hasCardio));
  const [cardioSessions,setCardioSessions]=useState<CardioLogDraft[]>(editingRecord?.cardioSessions??[]);
  const queryTopSets=(()=>{try{const parsed=JSON.parse(searchParams.get('topSets')||'[]');return Array.isArray(parsed)?parsed:[]}catch{return []}})() as Array<{muscle:string;lift:string;weight:number|string;reps:number|string}>;
  const splitDayTopSets:LoggedTopSet[]=(savedDay?.muscles||[]).flatMap(muscle=>{const assigned=(savedDay?.exercises||[]).map(name=>exercises.find(exercise=>exercise.name===name)).find(exercise=>exercise?.enabled&&exercise.kind==='Strength'&&exerciseCategory(exercise)==='Strength'&&exercise.muscles.includes(muscle));return assigned?[{muscle,lift:assigned.name,weight:0,reps:0,completed:true}]:[]});
  const recommendationTopSets:LoggedTopSet[]=(recommendation?.topSets||[]).filter(set=>set.selected).map(set=>({recommendationTopSetId:set.id,muscle:set.muscle,lift:set.exercise,weight:set.weight,reps:set.reps,calculatedMax:set.calculatedMax||undefined,completed:true}));
  const initialTopSets:LoggedTopSet[]=editingRecord?.topSets?.length?editingRecord.topSets:(queryTopSets.length?queryTopSets.map(set=>({muscle:set.muscle||'Primary',lift:set.lift,weight:Number(set.weight)||0,reps:Number(set.reps)||0,completed:true})):(editingRecord?.lift&&editingRecord.weight&&editingRecord.reps?[{muscle:editingRecord.muscles[0]||'Primary',lift:editingRecord.lift,weight:editingRecord.weight,reps:editingRecord.reps,calculatedMax:editingRecord.calculatedMax,completed:true}]:workoutSource==='plan'&&recommendationTopSets.length?recommendationTopSets:workoutSource==='plan'?splitDayTopSets:[]));
  const [topSets,setTopSets]=useState<LoggedTopSet[]>(initialTopSets);
  const [historyExercise,setHistoryExercise]=useState(initialTopSets[0]?.lift||'');
  const [lift,setLift]=useState(editingRecord?.lift??searchParams.get('lift')??''); const [weight,setWeight]=useState(editingRecord?.weight?String(editingRecord.weight):(searchParams.get('weight')??'')); const [reps,setReps]=useState(editingRecord?.reps?String(editingRecord.reps):(searchParams.get('reps')??'1'));
  const [newTopSetMuscle,setNewTopSetMuscle]=useState('');
  const [showAllExercises,setShowAllExercises]=useState(false);
  useEffect(()=>setQuickLogMessage(''),[lift,weight,reps]);
  const initialLiftRef=useRef(lift);useEffect(()=>{if(lift&&lift!==initialLiftRef.current){setHistoryExercise(lift);initialLiftRef.current=lift}},[lift]);
  const [saved,setSaved]=useState(false);
  const [quickLoggedKeys,setQuickLoggedKeys]=useState<string[]>([]);const [quickLogMessage,setQuickLogMessage]=useState('');
  const [reviewing,setReviewing]=useState(false);
  const [saveMessage,setSaveMessage]=useState('');
  const [bodyWeight,setBodyWeight]=useState(editingRecord?.bodyWeight?String(editingRecord.bodyWeight):(setup?.currentWeight||''));
  const [effort,setEffort]=useState(editingRecord?.effort||'');
  const [notes,setNotes]=useState(editingRecord?.notes||'');
  const [addingExercise,setAddingExercise]=useState(false);const [newExerciseName,setNewExerciseName]=useState('');const [newExerciseMuscles,setNewExerciseMuscles]=useState<string[]>([]);
  const liftMuscles:Record<string,string[]>={'Squat':['Quads','Hamstrings','Glutes'],'Hack Squat':['Quads','Glutes'],'Bench Press':['Chest','Shoulders','Triceps'],'Smith Machine Shoulder Press':['Shoulders','Triceps'],'Pull Ups':['Back','Biceps','Forearms'],'Lat Pulldown':['Back','Biceps']};
  const repeatedWorkout=recentWorkouts.find(item=>item.id===selectedRecent)??recentWorkouts[0]??{id:'',date:'',name:'Workout',detail:'',muscles:[],exercises:[]};
  const sourceMuscles=workoutSource==='plan'?(plannedDay?.muscles??[]):workoutSource==='repeat'?repeatedWorkout.muscles:[];
  const derivedMuscles=Array.from(new Set([...sourceMuscles,...(liftMuscles[lift]??[]),...(hasCardio?['Cardio']:[])]));
  const displayedMuscles=manualMuscles?muscles:derivedMuscles;
  const plannedExerciseNames=new Set((((plannedDay as {exercises?:string[]}|undefined)?.exercises)||[]).map((name:string)=>String(name).trim().toLowerCase()));
  const restrictToPlannedExercises=workoutSource==='plan'&&plannedExerciseNames.size>0&&!showAllExercises;
  const strengthCatalogue=exercises.filter(exercise=>exercise.enabled&&exercise.kind==='Strength'&&exerciseCategory(exercise)==='Strength');
  const allowedStrengthExercises=strengthCatalogue.filter(exercise=>restrictToPlannedExercises
    ?plannedExerciseNames.has(exercise.name.trim().toLowerCase())
    :(workoutSource!=='plan'||!plannedExerciseNames.size)&&(workoutSource!=='plan'||!sourceMuscles.length||exercise.muscles.some(muscle=>sourceMuscles.includes(muscle)))||showAllExercises||plannedExerciseNames.has(exercise.name.trim().toLowerCase()));
  const topSetExerciseOptions=allowedStrengthExercises.filter(exercise=>!newTopSetMuscle||exercise.muscles.includes(newTopSetMuscle));
  const manualLiftData=exercises.find(exercise=>exercise.name===lift);const manualTopSet:LoggedTopSet|undefined=lift&&Number(weight)&&Number(reps)?{muscle:manualLiftData?.muscles.find(muscle=>sourceMuscles.includes(muscle))||manualLiftData?.muscles[0]||sourceMuscles[0]||'Primary',lift,weight:Number(weight),reps:Number(reps),completed:true}:undefined;
  const calculatedMax=calculateEstimatedOneRepMax(Number(weight),Number(reps));
  const previousRecord=records.filter(record=>record.lift===lift&&record.weight&&record.reps).sort((a,b)=>b.date.localeCompare(a.date))[0];
  const previousSet=previousRecord?{weight:previousRecord.weight!,reps:previousRecord.reps!,date:previousRecord.date}:undefined;
  const previousCalculatedMax=previousSet?calculateEstimatedOneRepMax(previousSet.weight,previousSet.reps):null;
  const chooseMuscle=(muscle:string)=>setMuscles(current=>current.includes(muscle)?current.filter(x=>x!==muscle):[...current,muscle]);
  const startAdjustingMuscles=()=>{setMuscles(derivedMuscles);setManualMuscles(true)};
  const useRecent=(name:string,nextWeight:string,nextReps:string)=>{setLift(name);setWeight(nextWeight);setReps(nextReps)};
  const chooseRepeatedWorkout=(id:string)=>{setSelectedRecent(id);setManualMuscles(false);setTopSets(repeatTopSetsFor(id));setLift('');setWeight('');setReps('1');setNewTopSetMuscle('')};
  const toggleNewExerciseMuscle=(muscle:string)=>setNewExerciseMuscles(current=>current.includes(muscle)?current.filter(item=>item!==muscle):[...current,muscle]);
  const saveNewExercise=()=>{const name=newExerciseName.trim();if(!name||!newExerciseMuscles.length)return;const created=addExercise({name,kind:'Strength',muscles:newExerciseMuscles,detail:'Added while logging · Weight + reps',enabled:true,custom:true});setLift(created.name);setHistoryExercise(created.name);setAddingExercise(false);setNewExerciseName('');setNewExerciseMuscles([])};
  const topSetKey=(set:LoggedTopSet)=>set.id||`${set.muscle}::${set.lift}::${set.weight}::${set.reps}`;const completedTopSets=topSets.filter(set=>set.lift&&set.weight>0&&set.reps>0&&!quickLoggedKeys.includes(topSetKey(set))).map(set=>({...set,completed:true,calculatedMax:calculateEstimatedOneRepMax(set.weight,set.reps)??undefined}));
  const updateTopSet=(index:number,patch:Partial<LoggedTopSet>)=>setTopSets(current=>current.map((set,setIndex)=>setIndex===index?{...set,...patch}:set));
  const addBlankTopSet=()=>setTopSets(current=>[...current,{id:`top-set-${Date.now()}`,muscle:'',lift:'',weight:0,reps:0,completed:true}]);const removeTopSet=(index:number)=>setTopSets(current=>current.filter((_,setIndex)=>setIndex!==index));
  const createExerciseForTopSet=(name:string,mappedMuscles:string[])=>{const created=addExercise({name,kind:'Strength',muscles:mappedMuscles,detail:'Added while logging · Weight + reps',enabled:true,custom:true});setTopSets(current=>{const blankIndex=current.findIndex(set=>!set.lift);if(blankIndex>=0)return current.map((set,index)=>index===blankIndex?{...set,lift:created.name,muscle:created.muscles.find(muscle=>sourceMuscles.includes(muscle))||created.muscles[0]||'Primary',weight:0,reps:0}:set);return[...current,{id:`top-set-${Date.now()}`,muscle:created.muscles.find(muscle=>sourceMuscles.includes(muscle))||created.muscles[0]||'Primary',lift:created.name,weight:0,reps:0,completed:true}]});setQuickLogMessage(`${created.name} was added to your exercise library.`)};
  const addAnotherTopSet=()=>{if(!lift||!Number(weight)||!Number(reps))return;const exercise=exercises.find(item=>item.name===lift);const muscle=newTopSetMuscle||exercise?.muscles.find(item=>sourceMuscles.includes(item))||exercise?.muscles[0]||sourceMuscles[0]||'Primary';setTopSets(current=>[...current,{id:`top-set-${Date.now()}`,muscle,lift,weight:Number(weight),reps:Number(reps),completed:true}]);setLift('');setWeight('');setReps('1');setNewTopSetMuscle('')};
  const recommendationMetadata=workoutSource==='plan'&&recommendation?{recommendationId:recommendation.id,splitId:recommendation.splitDay.splitId,splitDayId:recommendation.splitDay.id,splitPosition:recommendation.splitDay.position}:{};
  const quickLogTopSet=(set:LoggedTopSet)=>{if(!set.lift||!set.weight||!set.reps)return;const completed={...set,completed:true,calculatedMax:calculateEstimatedOneRepMax(set.weight,set.reps)??undefined};const result=addRecord({date:sessionIso,title:`Top set · ${set.lift}`,muscles:[set.muscle],topSets:[completed],lift:set.lift,weight:set.weight,reps:set.reps,calculatedMax:completed.calculatedMax,hasCardio:false,...recommendationMetadata,selectedRecommendationTopSetIds:set.recommendationTopSetId?[set.recommendationTopSetId]:[]});if(!result.ok){setQuickLogMessage('That exact top set is already saved.');return}markCompleted();setQuickLoggedKeys(current=>[...current,topSetKey(set)]);setQuickLogMessage(`${set.lift} · ${set.weight} ${weightUnit} ×${set.reps} logged.`);if(!topSets.length){setLift('');setWeight('');setReps('1')}};
  const editLoggedTopSet=(index:number,original:LoggedTopSet,corrected:LoggedTopSet)=>{
    const sameDay=records.find(record=>record.date===sessionIso);if(!sameDay){setQuickLogMessage('The completed training day could not be found. Refresh and try again.');return false}
    const originalSignature=`${original.muscle}|${original.lift}|${original.weight}|${original.reps}`;let replaced=false;
    const nextSets=(sameDay.topSets||[]).map(savedSet=>{const matches=Boolean((original.recommendationTopSetId&&savedSet.recommendationTopSetId===original.recommendationTopSetId)||(original.id&&savedSet.id===original.id)||`${savedSet.muscle}|${savedSet.lift}|${savedSet.weight}|${savedSet.reps}`===originalSignature);if(!matches||replaced)return savedSet;replaced=true;return{...savedSet,...corrected,id:savedSet.id,recommendationTopSetId:savedSet.recommendationTopSetId||corrected.recommendationTopSetId,completed:true,calculatedMax:calculateEstimatedOneRepMax(corrected.weight,corrected.reps)??undefined}});
    if(!replaced){setQuickLogMessage('That completed top set could not be found. Refresh and try again.');return false}
    const firstSet=nextSets[0];const musclesForDay=Array.from(new Set([...nextSets.map(set=>set.muscle),...(sameDay.hasCardio?['Cardio']:[])]));const {id,...savedDay}=sameDay;
    const result=updateRecord(id,{...savedDay,muscles:musclesForDay,topSets:nextSets,lift:firstSet?.lift,weight:firstSet?.weight,reps:firstSet?.reps,calculatedMax:firstSet?.calculatedMax});if(!result.ok){setQuickLogMessage('The correction could not be saved. Refresh and try again.');return false}
    const localCorrected={...original,...corrected,completed:true,calculatedMax:calculateEstimatedOneRepMax(corrected.weight,corrected.reps)??undefined};setTopSets(current=>current.map((set,setIndex)=>setIndex===index?localCorrected:set));const oldKey=topSetKey(original);const newKey=topSetKey(localCorrected);setQuickLoggedKeys(current=>[...current.filter(key=>key!==oldKey),newKey]);setQuickLogMessage(`${corrected.lift} corrected to ${corrected.weight} ${weightUnit} ×${corrected.reps}.`);return true;
  };
  const choosePlanDay=(index:number)=>{const day=savedDays[index];const next:LoggedTopSet[]=(day?.muscles||[]).flatMap(muscle=>{const assigned=(day.exercises||[]).map(name=>exercises.find(exercise=>exercise.name===name)).find(exercise=>exercise?.enabled&&exercise.kind==='Strength'&&exerciseCategory(exercise)==='Strength'&&exercise.muscles.includes(muscle));return assigned?[{muscle,lift:assigned.name,weight:0,reps:0,completed:true}]:[]});setSelectedPlanDay(index);setTopSets(next);setLift('');setWeight('');setReps('1');setNewTopSetMuscle('');setHistoryExercise(next[0]?.lift||'');setManualMuscles(false)};
  const saveWorkout=async()=>{
    setSaved(false);
    // A training day is worth saving without a top set: a body-weight check-in, a
    // note, an effort rating or an already quick-logged set are all real records.
    // This guard used to demand a set/lift/cardio while the message promised
    // otherwise, and it was stricter than the one that opens the review.
    if(!editingRecord&&!completedTopSets.length&&!lift&&!hasCardio&&!quickLoggedKeys.length&&!bodyWeight&&!notes.trim()&&!effort){setSaveMessage('Add a top set, cardio entry, body-weight check-in, effort rating, or note before saving a new day.');return}
    const title=editingRecord?.title||(workoutSource==='repeat'?repeatedWorkout.name:workoutSource==='plan'?(plannedDay?.name||'Planned Workout'):'Custom Workout');
    const selectedLiftData=exercises.find(exercise=>exercise.name===lift);const savedTopSets=completedTopSets.length?completedTopSets:(lift&&weight&&reps?[{muscle:selectedLiftData?.muscles.find(muscle=>sourceMuscles.includes(muscle))||selectedLiftData?.muscles[0]||'Primary',lift,weight:Number(weight),reps:Number(reps),calculatedMax:calculatedMax??undefined,completed:true}]:[]);const firstSet=savedTopSets[0];
    const draft={date:sessionIso,title,muscles:Array.from(new Set([...savedTopSets.map(set=>set.muscle),...(hasCardio?['Cardio']:[])])),topSets:savedTopSets.length?savedTopSets:undefined,lift:firstSet?.lift,weight:firstSet?.weight,reps:firstSet?.reps,calculatedMax:firstSet?.calculatedMax,hasCardio,cardioSessions:hasCardio?cardioSessions:undefined,effort:effort||undefined,notes:notes.trim()||undefined,bodyWeight:bodyWeight?Number(bodyWeight):undefined,...recommendationMetadata,selectedRecommendationTopSetIds:savedTopSets.map(set=>set.recommendationTopSetId).filter((id):id is string=>Boolean(id))};
    const result=editingRecord?updateRecord(editingRecord.id,draft):addRecord(draft);
    if(!result.ok){setSaveMessage(editingRecord?'This workout could not be found. Return to History and try again.':'This exact workout is already in your history. Nothing was saved twice.');return}
    // Only real training closes out the day's recommendation. A body-weight
    // check-in or a note must not consume the workout you still owe.
    if(!editingRecord&&workoutSource==='plan'&&(savedTopSets.length>0||hasCardio))markCompleted();setSaved(true);setReviewing(false);navigate(editingRecord?'/history':'/');
  };
  const openReview=()=>{setSaved(false);if(editingRecord){setSaveMessage('');setReviewing(true);return}const hasQuickLoggedTopSet=quickLoggedKeys.length>0;const hasContext=Boolean(bodyWeight||notes.trim()||effort);if(!completedTopSets.length&&!lift&&!hasCardio&&!hasQuickLoggedTopSet&&!hasContext){setSaveMessage('Add a result or session detail before finishing the day.');return}setSaveMessage('');setReviewing(true)};
  const removeWorkout=async()=>{if(!editingRecord||!window.confirm(`Delete the workout record for ${todayShort}? This permanently removes it from History and Insights.`))return;setSaveMessage('');const removed=await deleteRecord(editingRecord.id);if(removed)navigate('/history');else setSaveMessage('The workout could not be deleted. Check the sync message and try again.')};
  if(editId&&!editingRecord)return <div className="narrow stack-xl"><PageIntro eyebrow="WORKOUT HISTORY" title="Workout not found" copy="This workout may have been removed from this device."/><section className="card"><Link className="button" to="/history">Return to History</Link></section></div>;
  if(completedOnEntry)return <div className="narrow stack-xl workout-editor completed-workout-entry">
    <PageIntro eyebrow={todayLong.toUpperCase()} title="Today is already logged" copy="Forge will not build a second workout on top of a completed day."/>
    <section className="card completed-day-card">
      <span className="completed-day-check">✓</span>
      <div><span className="eyebrow">TODAY · COMPLETE</span><h2>{completedOnEntry.title}</h2><p>{completedOnEntry.muscles.filter(muscle=>muscle!=='Cardio').join(' · ')||(completedOnEntry.hasCardio?'Cardio':'Completed training')}</p></div>
      <div className="completed-day-results"><div><strong>{completedOnEntry.topSets?.filter(set=>set.completed!==false).length||0}</strong><span>Top sets</span></div><div><strong>{completedOnEntry.cardioSessions?.length||0}</strong><span>Cardio</span></div></div>
      <CompletedDayReview record={completedOnEntry} unit={weightUnit}/>
      <footer><Link className="button" to={`/workout?edit=${completedOnEntry.id}`}>Review or edit today</Link><Link className="button ghost" to="/history">Open history</Link></footer>
    </section>
    <p className="completed-day-note">Need to add another result? Open today and add it to the same training day so your split advances only once.</p>
  </div>;
  return <div className="narrow stack-xl workout-editor"><PageIntro eyebrow={todayLong.toUpperCase()} title={editingRecord?'Edit training day':requestedDate?'Add a training day':"Log today's workout"} copy={editingRecord?'Update the saved results for this day. History and insights will refresh automatically.':requestedDate?'Log anything you completed on this date. It will be saved as one editable training day.':'Start with the plan, repeat a previous session, or record only what you performed.'} />
    {editingRecord&&<section className="coach-loaded"><div><span>EDITING COMPLETED SESSION</span><strong>{editingRecord.title}</strong><small>Saving replaces this session on {todayShort}; it will not create a duplicate.</small></div><div className="button-row"><Link to="/history">Cancel</Link><button type="button" className="text-button danger" onClick={removeWorkout}>Delete workout</button></div></section>}
    {searchParams.get('source')==='recommendation'&&recommendation&&<section className="coach-loaded"><div><span>SAVED DAILY RECOMMENDATION</span><strong>{recommendation.splitDay.name} · {topSets.length} selected top {topSets.length===1?'set':'sets'}</strong><small>Today, Log, and Coach are using recommendation {recommendation.id?.slice(0,8)||recommendation.date}. Record actual results; only completed items advance progression.</small></div><button className="text-button" onClick={()=>openCoachBubble('Why is this my saved workout today?')}>Why this workout?</button></section>}
    {historyExercise&&!topSets.length&&<LastPerformanceBanner exercise={historyExercise} records={records} unit={weightUnit} onClose={()=>setHistoryExercise('')} onUse={(nextWeight,nextReps)=>{setWeight(String(nextWeight));setReps(String(nextReps))}}/>}
    {!editingRecord&&<section className="card workout-source-card compact-workout-source"><div className="workout-date"><span className="eyebrow">LOGGING · {todayShort.toUpperCase()}</span><strong>{workoutSource==='plan'?(plannedDay?.name||'Today’s recommendation'):workoutSource==='repeat'?'Repeat workout':'Start blank'}</strong></div><div className="source-options"><button className={workoutSource==='plan'?'active':''} onClick={()=>{setWorkoutSource('plan');setManualMuscles(false);setTopSets(recommendationTopSets)}}><span>FORGE</span><b>Recommended</b></button><button className={workoutSource==='repeat'?'active':''} onClick={()=>{setWorkoutSource('repeat');setManualMuscles(false);setTopSets(repeatTopSetsFor(selectedRecent));setLift('');setWeight('');setReps('1')}}><span>REUSE</span><b>Repeat</b></button><button className={workoutSource==='blank'?'active':''} onClick={()=>{setWorkoutSource('blank');setManualMuscles(false);setTopSets([]);setLift('');setWeight('');setReps('1')}}><span>FREE</span><b>Blank</b></button></div>{workoutSource==='plan'&&recommendation&&<div className="saved-recommendation-source"><span>Split position {recommendation.splitDay.position}</span><strong>{recommendation.splitDay.muscles.join(' · ')||recommendation.splitDay.type}</strong><small>This day cannot drift from Today or Coach. Complete it, repeat something else, or log a blank session honestly.</small></div>}{workoutSource==='repeat'&&<div className="recent-workout-picker"><div><span className="field-caption">CHOOSE A RECENT WORKOUT</span><small>The structure copies over; completed values stay blank.</small></div>{!recentWorkouts.length&&<p className="empty-history">No completed workouts to repeat yet.</p>}{recentWorkouts.map(item=><button className={selectedRecent===item.id?'active':''} onClick={()=>chooseRepeatedWorkout(item.id)} key={item.id}><span>{item.date}</span><div><strong>{item.name}</strong><small>{item.detail}</small></div><b>{selectedRecent===item.id?'Selected':'Choose'}</b></button>)}</div>}</section>}
    {!topSets.length&&<section className="card form-card accent-card"><div className="section-title compact-title"><span>01</span><div><h3>Exercise & Top Set <small>(optional)</small></h3><p>{workoutSource==='plan'&&sourceMuscles.length?`Showing exercises mapped to ${sourceMuscles.join(', ')} from today’s split.`:'Every completed weighted set receives a calculated max.'}</p></div></div>
<label>Lift<select value={lift} onChange={event=>{if(event.target.value==='__new__'){setAddingExercise(true);setNewExerciseMuscles(sourceMuscles.filter(muscle=>muscle!=='Cardio'));return}setLift(event.target.value)}}><option value="">Choose a lift</option>{allowedStrengthExercises.map(exercise=><option key={exercise.id}>{exercise.name}</option>)}<option value="__new__">＋ Add a new exercise…</option></select></label>
{addingExercise&&<div className="inline-exercise-creator"><label>Exercise name<input value={newExerciseName} onChange={event=>setNewExerciseName(event.target.value)} placeholder="e.g. Smith incline bench"/></label><div><span className="field-caption">MUSCLE GROUPS</span><div className="muscle-picker">{(sourceMuscles.length?sourceMuscles.filter(muscle=>muscle!=='Cardio'):muscleOptions.filter(muscle=>muscle!=='Cardio')).map(muscle=><button type="button" className={newExerciseMuscles.includes(muscle)?'muscle-chip active':'muscle-chip'} onClick={()=>toggleNewExerciseMuscle(muscle)} key={muscle}>{muscle}</button>)}</div></div><div className="button-row"><button type="button" className="button" disabled={!newExerciseName.trim()||!newExerciseMuscles.length} onClick={saveNewExercise}>Save to library & select</button><button type="button" className="button ghost" onClick={()=>setAddingExercise(false)}>Cancel</button></div></div>}<TopSetHistory lift={lift} unit={weightUnit} suggestedExercises={workoutSource==='repeat'?repeatedWorkout.exercises:workoutSource==='plan'?allowedStrengthExercises.map(exercise=>exercise.name):undefined} onChoose={(name,set)=>useRecent(name,String(set.weight),String(set.reps))} /><div className="field-grid"><label>Weight ({weightUnit})<input value={weight} onChange={e=>setWeight(e.target.value)} inputMode="decimal" placeholder="0" /><div className="step-controls"><button onClick={()=>setWeight(String(Math.max(0,Number(weight||0)-5)))}>−5</button><button onClick={()=>setWeight(String(Number(weight||0)+5))}>+5</button></div></label><label>Reps<input value={reps} onChange={e=>setReps(e.target.value)} inputMode="numeric" /><div className="step-controls"><button onClick={()=>setReps(String(Math.max(1,Number(reps||1)-1)))}>−1</button><button onClick={()=>setReps(String(Number(reps||0)+1))}>+1</button></div></label></div>{weight&&reps&&<div className="calculated-max"><div><span>{Number(reps)===1?'REAL 1RM':'CALCULATED MAX'}</span><strong>{calculatedMax??'—'} <small>{weightUnit}</small></strong></div><div><b>{Number(reps)===1?'Logged one-rep result':'Epley estimate'}</b><small>{Number(reps)===1?'Counts toward Real 1RM goals':`${weight} × (1 + ${reps} ÷ 30)`}</small></div></div>}{lift&&previousSet&&<div className="last-set"><span>LAST TIME ON {lift.toUpperCase()}</span><strong>{previousSet.weight} lb ×{previousSet.reps}</strong><small>Calculated max {previousCalculatedMax} lb</small><b>{weight?`Today: ${weight} ${weightUnit} ×${reps} · Calc. max ${calculatedMax} ${weightUnit}`:'Enter today’s set'}</b></div>}<small className="calculated-max-rule">Only saved completed sets become measurements in Insights.</small></section>}
    {workoutSource==='plan'&&plannedExerciseNames.size>0&&<small className="lift-scope-note">{restrictToPlannedExercises?`Showing the ${plannedExerciseNames.size} exercise${plannedExerciseNames.size===1?'':'s'} mapped to this split day.`:'Showing every strength exercise.'} <button type="button" className="text-button" onClick={()=>setShowAllExercises(value=>!value)}>{restrictToPlannedExercises?'Show all':'Show this day only'}</button></small>}
    {topSets.length>0&&<TopSetCards collapsible={workoutSource==='plan'&&!editingRecord} planLabel={plannedDay?.name?`FROM ${plannedDay.name.toUpperCase()}`:undefined} sets={topSets} onChange={updateTopSet} onQuickLog={quickLogTopSet} onEditLogged={editLoggedTopSet} loggedKeys={quickLoggedKeys} exercises={allowedStrengthExercises} muscles={sourceMuscles.filter(muscle=>muscle!=='Cardio')} records={records} date={sessionIso} unit={weightUnit} onAdd={addBlankTopSet} onRemove={removeTopSet} onCreateExercise={createExerciseForTopSet}/>}
    {manualTopSet&&<div className="quick-log-top-sets embedded">{[manualTopSet].map(set=>{const logged=quickLoggedKeys.includes(topSetKey(set));return <div className="quick-log-row" key={topSetKey(set)}><span><strong>{set.lift}</strong><small>{set.muscle} · {set.weight} {weightUnit} ×{set.reps}</small></span><button type="button" className={logged?'button ghost':'button'} disabled={logged} onClick={()=>quickLogTopSet(set)}>{logged?'Logged ✓':'Log top set now'}</button></div>})}{quickLogMessage&&<small className="quick-log-message">{quickLogMessage}</small>}</div>}
    {topSets.length>0&&<details className="card form-card add-top-set-card"><summary><h3>Add another top set</h3><p>Choose a muscle group from {plannedDay?.name||'this workout'} first. Exercise choices stay inside that split-day mapping.</p></summary><div className="field-grid"><label>Muscle group<select value={newTopSetMuscle} onChange={event=>{setNewTopSetMuscle(event.target.value);setLift('')}}><option value="">Choose muscle group</option>{sourceMuscles.filter(muscle=>muscle!=='Cardio').map(muscle=><option key={muscle}>{muscle}</option>)}</select></label><label>Exercise<select value={lift} onChange={event=>setLift(event.target.value)} disabled={!newTopSetMuscle}><option value="">Choose exercise</option>{topSetExerciseOptions.filter(exercise=>!topSets.some(set=>set.lift===exercise.name)).map(exercise=><option key={exercise.id}>{exercise.name}</option>)}</select></label><label>Weight ({weightUnit})<input value={weight} onChange={event=>setWeight(event.target.value)} inputMode="decimal"/></label><label>Reps<input value={reps} onChange={event=>setReps(event.target.value)} inputMode="numeric"/></label></div><button type="button" className="button" disabled={!newTopSetMuscle||!lift||!Number(weight)||!Number(reps)} onClick={addAnotherTopSet}>Add completed top set</button></details>}
    <CardioBuilder sectionNumber="02" onEntriesChange={(hasEntries,entries)=>{setHasCardio(hasEntries);setCardioSessions(entries)}} initialOpen={Boolean(searchParams.get('cardio'))} initialEntries={editingRecord?.cardioSessions} plannedSummary={workoutSource==='plan'&&recommendation?.cardio?.selected?recommendation.cardio.summary:undefined}/>
    <section className="card form-card session-details"><div className="section-title compact-title"><span>03</span><div><h3>Session Details</h3><p>Review the context Forge will save with this workout.</p></div></div><div className="derived-muscles"><div><span className="field-caption">MUSCLE GROUPS</span><small>{manualMuscles?'Manually adjusted':workoutSource==='plan'?'Highlighted from today’s split workout':'Automatically derived from the selected workout and logged work'}</small></div>{!manualMuscles?<button className="text-button" onClick={startAdjustingMuscles}>Adjust</button>:<button className="text-button" onClick={()=>setManualMuscles(false)}>Use automatic</button>}<div className={manualMuscles?'muscle-picker editable':'muscle-picker automatic'}>{manualMuscles?muscleOptions.map(m=><button key={m} className={displayedMuscles.includes(m)?'muscle-chip active':'muscle-chip'} onClick={()=>chooseMuscle(m)}>{m}</button>):muscleOptions.map(m=><span className={displayedMuscles.includes(m)?'muscle-chip active':'muscle-chip muted'} key={m}>{m}</span>)}</div></div><div className="field-grid session-context"><label className="body-checkin">Today's body weight <span>Optional check-in used for body-weight trends</span><div className="weight-input"><input value={bodyWeight} onChange={e=>setBodyWeight(e.target.value)} inputMode="decimal" /><b>{weightUnit}</b></div></label><label>Session effort<select value={effort} onChange={e=>setEffort(e.target.value)}><option value="">Not recorded</option><option>Easy</option><option>Moderate</option><option>Hard</option><option>Max effort</option></select></label></div><label>Workout notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} placeholder="How did the session feel? Add anything the numbers do not capture." /></label></section>
    {reviewing&&<div className="workout-review-backdrop" role="dialog" aria-modal="true" aria-label="Finish training day"><section className="workout-review"><header><div><span className="eyebrow">FINISH DAY</span><h2>{editingRecord?'Finish with these changes?':'Finish today’s training?'}</h2><p>Everything completed today is stored together as one editable training day.</p></div><button onClick={()=>setReviewing(false)} aria-label="Close review">×</button></header><div className="review-summary"><div><span>DATE</span><strong>{todayShort}</strong></div><div><span>SESSION</span><strong>{workoutSource==='repeat'?repeatedWorkout.name:workoutSource==='plan'?(plannedDay?.name||'Planned Workout'):'Custom Workout'}</strong></div><div><span>MUSCLES</span><strong>{displayedMuscles.join(' · ')||'Cardio only'}</strong></div></div>{completedTopSets.length>0?<section><span className="field-caption">COMPLETED TOP SETS</span>{completedTopSets.map(set=><div className="review-result" key={`${set.muscle}-${set.lift}`}><small>{set.muscle}</small><strong>{set.lift} · {set.weight} {weightUnit} ×{set.reps}</strong><small>{set.reps===1?`Real 1RM ${set.weight} ${weightUnit}`:`Calculated max ${set.calculatedMax} ${weightUnit}`}</small></div>)}</section>:lift&&<section><span className="field-caption">TOP SET</span><h3>{lift}</h3><strong className="review-result">{weight} {weightUnit} ×{reps} <small>{Number(reps)===1?`Real 1RM ${weight} ${weightUnit}`:`Calculated max ${calculatedMax} ${weightUnit}`}</small></strong></section>}{cardioSessions.length>0&&<section><span className="field-caption">CARDIO</span>{cardioSessions.map(session=><div className="review-cardio" key={session.id}><strong>{session.summary}</strong>{session.prescription.note?<small>{String(session.prescription.note)}</small>:null}</div>)}</section>}<section className="review-context"><span>{effort||'Effort not recorded'}</span>{bodyWeight&&<span>{bodyWeight} {weightUnit} body weight</span>}{notes&&<p>{notes}</p>}</section>{saveMessage&&!saved&&<p className="review-blocked" role="alert">{saveMessage}</p>}<footer><button className="button ghost" onClick={()=>setReviewing(false)}>Keep editing</button><button className="button" onClick={saveWorkout}>{editingRecord?'Finish Day →':'Finish Day →'}</button></footer></section></div>}
    {saveMessage&&<div className={saved?'save-confirmation':'save-confirmation save-warning'} role="status">{saveMessage}{saved&&<> <Link to="/history">View day in History →</Link></>}</div>}<button className="button wide save-workout" onClick={openReview}>{saved?'Day finished ✓':'Finish Day →'}</button></div>;
}

export function InsightsPage() {
  return <div className="stack-xl"><PageIntro eyebrow="PERFORMANCE" title="Your progress, in context" copy="True maxes, comparable sets, and training consistency—kept intentionally separate." action={<Link className="button secondary" to="/insights/compare">Compare with a friend</Link>} />
    <section className="metrics-strip"><Metric value="1,210 lb" label="Strength total" delta="+35 lb in 90 days" /><Metric value="475 lb" label="Squat 1RM" /><Metric value="315 lb" label="Bench 1RM" /><Metric value="420 lb" label="Deadlift 1RM" /></section>
    <div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><span className="eyebrow">SQUAT · 12 MONTHS</span><h3>Tested 1RM progression</h3></div><select className="compact-select"><option>Squat</option><option>Bench Press</option></select></div><div className="line-chart"><div className="grid-lines"/><svg viewBox="0 0 600 190" preserveAspectRatio="none"><polyline points="0,155 85,148 170,118 255,126 340,85 425,92 510,48 600,31" fill="none" stroke="currentColor" strokeWidth="5" vectorEffect="non-scaling-stroke"/><circle cx="600" cy="31" r="7" fill="currentColor"/></svg><div className="chart-labels"><span>SEP</span><span>NOV</span><span>JAN</span><span>MAR</span><span>MAY</span><span>JUL</span></div></div></section><section className="card"><span className="eyebrow">PERSONAL RECORDS</span><div className="record-list">{[['Squat','475 lb','Jul 21'],['Bench','315 lb','Jul 21'],['Hack Squat','500 ×3','Aug 2'],['Pull Ups','105 ×5','Jul 31']].map(r=><div key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><small>{r[2]}</small></div>)}</div></section></div></div>;
}

export function ProfilePage() {
  return <div className="stack-xl"><section className="profile-hero"><div className="avatar xlarge">PN</div><div><span className="eyebrow">ATHLETE PROFILE</span><h2>{athlete.name}</h2><p>@{athlete.username} · {athlete.level} · {athlete.goal}</p></div><Link className="button secondary" to="/onboarding">Edit profile</Link></section><section className="metrics-strip compact"><Metric value="190 lb" label="Current weight" /><Metric value="178 lb" label="Starting weight" /><Metric value={athlete.height} label="Height" /><Metric value={`${athlete.age}`} label="Age" /></section>
    <div className="profile-grid"><Link className="feature-card" to="/profile/split"><span className="feature-number">4 DAYS</span><h3>Build Your Split</h3><p>Push Strength · Pull Strength · Lower Body · Upper Volume</p><b>Manage training split →</b></Link><Link className="feature-card" to="/friends"><span className="feature-number">8 FRIENDS</span><h3>Your training circle</h3><p>Share only the progress metrics you choose.</p><b>Manage friends →</b></Link><Link className="feature-card" to="/settings/security"><span className="feature-number">SECURE</span><h3>Account & security</h3><p>Google sign-in, authenticator, and active sessions.</p><b>Open security →</b></Link><Link className="feature-card" to="/settings/billing"><span className="feature-number">PRO TRIAL</span><h3>Plan & billing</h3><p>14 days remaining. No charge during this prototype.</p><b>View plan →</b></Link></div></div>;
}

export function OnboardingPage() {
  const [step,setStep]=useState(1); return <div className="narrow stack-xl"><PageIntro eyebrow={`PROFILE SETUP · ${step} OF 3`} title={step===1?'Tell us about you':step===2?'Shape your training':'Privacy & preferences'} copy="This information makes recommendations safer, more relevant, and easier to compare over time." /><div className="stepper">{[1,2,3].map(n=><i key={n} className={n<=step?'active':''}/>)}</div><section className="card form-card">
    {step===1&&<><div className="field-grid"><label>Display name<input defaultValue="Preston Noland" /></label><label>Username<input defaultValue="prestonlifts" /></label><label>Date of birth<input type="date" defaultValue="1997-04-18" /></label><label>Height<input defaultValue="6 ft 0 in" /></label><label>Starting weight<input defaultValue="178 lb" /></label><label>Current weight<input defaultValue="190 lb" /></label></div></>}
    {step===2&&<><label>Primary goal<div className="choice-grid">{['Build strength','Build muscle','Improve endurance','General fitness'].map((x,i)=><button className={i===0?'choice active':'choice'} key={x}>{x}</button>)}</div></label><label>Experience level<select defaultValue="Advanced"><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Competitive</option></select></label><label>Available equipment<textarea defaultValue="Barbell, rack, bench, cables, hack squat, dumbbells" /></label></>}
    {step===3&&<><label>Units<div className="segmented"><button className="active">Imperial</button><button>Metric</button></div></label><label>Profile visibility<select><option>Friends only</option><option>Private</option><option>Public</option></select></label><div className="toggle-row"><div><strong>Allow friend comparisons</strong><span>You still choose which metrics each friend can see.</span></div><input type="checkbox" defaultChecked /></div><div className="toggle-row"><div><strong>Training reminders</strong><span>Gentle reminders on scheduled workout days.</span></div><input type="checkbox" defaultChecked /></div></>}
    <div className="form-actions">{step>1&&<button className="button ghost" onClick={()=>setStep(step-1)}>Back</button>}<button className="button" onClick={()=>setStep(Math.min(3,step+1))}>{step===3?'Save profile':'Continue'} →</button></div></section></div>;
}

export function SplitBuilderPage() { return <div className="stack-xl"><PageIntro eyebrow="PROFILE · TRAINING PLAN" title="Build Your Split" copy="Give every training day a clear job. Your recommendations use this structure—not a generic weekly template." action={<button className="button">Save split</button>} /><section className="card split-summary"><div><span className="eyebrow">ACTIVE SPLIT</span><input className="title-input" defaultValue="Strength + Conditioning" /></div><div><strong>4</strong><span>training days</span></div><div><strong>3</strong><span>recovery days</span></div></section><div className="split-builder">{splitDays.map((d,i)=><section className="day-card" key={d.day}><div className="day-index">{String(i+1).padStart(2,'0')}</div><div className="day-content"><div className="card-head"><div><span className="eyebrow">{d.day}</span><h3>{d.name}</h3></div><button className="icon-button">•••</button></div><span className="field-caption">MUSCLE GROUPS</span><div className="tag-row">{d.groups.map(g=><span className="tag" key={g}>{g}</span>)}</div><span className="field-caption">FOCUS LIFTS</span><div className="lift-list">{d.lifts.map(l=><span key={l}>{l}<b>↗</b></span>)}</div></div></section>)}<button className="add-day">＋ Add training day</button></div></div> }

export function FriendsPage() { const [query,setQuery]=useState(''); return <div className="stack-xl"><PageIntro eyebrow="COMMUNITY" title="Train alongside your people" copy="Friendships are mutual. Progress stays private until you choose what to share." /><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by username" /><button>Search</button></div><section><div className="section-row"><h3>Friend requests</h3><span className="count">1</span></div><div className="request-card"><span className="avatar blue">ML</span><div><strong>Morgan Lee</strong><small>@morgantrains · 3 mutual friends</small></div><button className="button small-button">Accept</button><button className="button ghost small-button">Decline</button></div></section><section><div className="section-row"><h3>Your friends</h3><span className="muted">8 total</span></div><div className="friends-grid">{friends.map(f=><article className="friend-card" key={f.username}><div className="friend-top"><span className="avatar" style={{background:f.accent,color:'#08110e'}}>{f.initials}</span><span className="status-dot">{f.status}</span></div><h3>{f.name}</h3><p>@{f.username}</p><div className="friend-stats"><span><strong>{f.sessions}</strong>sessions / week</span><span><strong>{f.total}</strong>strength total</span></div><div className="button-row"><Link className="button secondary small-button" to="/insights/compare">Compare</Link><button className="icon-button">•••</button></div></article>)}</div></section></div> }

export function ComparePage() { return <div className="stack-xl"><PageIntro eyebrow="FRIEND INSIGHTS" title="You vs. Adam" copy="A useful comparison without turning training into a leaderboard." action={<select className="compact-select"><option>Adam Davis</option><option>Jordan Miles</option></select>} /><div className="compare-head"><div><span className="avatar xlarge">PN</span><strong>You</strong><small>@prestonlifts</small></div><span>VS</span><div><span className="avatar xlarge mint">AD</span><strong>Adam</strong><small>@adamlifts</small></div></div><section className="card compare-table"><div className="compare-row header"><span>METRIC</span><span>YOU</span><span>ADAM</span></div>{[['Strength total','1,210 lb','1,145 lb'],['Weekly sessions','4','5'],['Current streak','6 days','12 days'],['Squat 1RM','475 lb','455 lb'],['Bench 1RM','315 lb','330 lb']].map(r=><div className="compare-row" key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><strong>{r[2]}</strong></div>)}</section><section className="privacy-note"><span>◉</span><div><strong>Adam shares 5 metrics with you</strong><p>Neither of you can see body weight, age, private notes, or workout details.</p></div><button>Edit what I share</button></section></div> }

export function SecurityPage() { return <div className="narrow stack-xl"><PageIntro eyebrow="ACCOUNT" title="Security" copy="Keep sign-in simple while protecting training history and personal information." /><section className="card settings-list"><div className="setting-row"><span className="setting-icon">G</span><div><strong>Google account</strong><small>preston@example.com</small></div><span className="verified">CONNECTED</span></div><div className="setting-row"><span className="setting-icon">#</span><div><strong>Authenticator app</strong><small>Add a Google Authenticator-compatible second step.</small></div><button className="button secondary small-button">Set up</button></div><div className="setting-row"><span className="setting-icon">◎</span><div><strong>Active sessions</strong><small>1 device · Chrome on macOS</small></div><button className="text-button">Review</button></div></section><section className="card"><span className="eyebrow">SIGN-IN POLICY</span><h3>Google is your primary identity</h3><p className="muted">Your username is public inside the app, but it is not a password. Optional authenticator codes add protection without creating a second password to remember.</p></section></div> }

export function BillingPage() { return <div className="stack-xl"><PageIntro eyebrow="MEMBERSHIP" title="Choose the support you need" copy="Billing is a visual prototype. No payment information is collected yet." /><div className="plans"><article className="plan-card"><span className="eyebrow">FREE</span><h3>$0 <small>/ forever</small></h3><p>Everything needed to log consistently.</p><ul><li>Workout and top-set logging</li><li>Goals and core insights</li><li>Up to 5 friends</li></ul><button className="button ghost wide">Current plan</button></article><article className="plan-card featured"><span className="plan-badge">RECOMMENDED</span><span className="eyebrow">PRO</span><h3>$7.99 <small>/ month</small></h3><p>Deeper guidance for serious progress.</p><ul><li>Advanced training insights</li><li>Unlimited friends and comparisons</li><li>AI-assisted programming</li><li>Data export and priority support</li></ul><button className="button wide">Start 14-day trial</button></article><article className="plan-card"><span className="eyebrow">COACH</span><h3>Coming soon</h3><p>Program and monitor multiple athletes.</p><ul><li>Coach dashboard</li><li>Athlete programming</li><li>Shared progress reports</li></ul><button className="button ghost wide" disabled>Join waitlist</button></article></div></div> }
