import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAdaptiveTraining } from '../features/training/AdaptiveTrainingProvider';
import { wearableConnections } from '../features/training/wearableService';
import { useGoals } from '../features/goals/GoalsProvider';
import { useWorkoutHistory } from '../features/training/WorkoutHistoryProvider';
import { useProfileSetup } from '../features/profile/ProfileSetupProvider';
import { useAppearance,type AppearanceSettings } from '../features/preferences/AppearanceProvider';
import { beginStravaConnection, disconnectStrava, finishStravaConnection, getActivityConnection, syncStravaActivities, type ActivityConnectionStatus } from '../features/training/activityConnectionService';

type View='profile'|'recovery'|'connections'|'appearance';
export function ProfilePage(){
  const {setup}=useProfileSetup();const {profile,recovery,health}=useAdaptiveTraining();const {goals}=useGoals();const {records}=useWorkoutHistory();const {settings,update,applyPreset,reset}=useAppearance();const [view,setView]=useState<View>('profile');const [activity,setActivity]=useState<ActivityConnectionStatus|null>(null);const [connectionMessage,setConnectionMessage]=useState('');const [connectionBusy,setConnectionBusy]=useState(false);const latest=health[health.length-1];const name=setup?.displayName||'Athlete';const initials=name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();const metric=setup?.units==='Metric';const distanceUnit=metric?'km':'mi';const distanceValue=(miles:number)=>Number((metric?miles*1.609344:miles).toFixed(1));const weeklyDistance=distanceValue(profile.weeklyMileage);const longestDistance=distanceValue(profile.longestRunMiles);
  const loadConnection=async()=>{try{setActivity(await getActivityConnection())}catch(reason){setConnectionMessage(reason instanceof Error?reason.message:'Connection status is unavailable.')}};
  useEffect(()=>{void loadConnection();const params=new URLSearchParams(window.location.search);const code=params.get('code');const state=params.get('state');if(params.get('strava')==='callback'&&code&&state){setView('connections');setConnectionBusy(true);void finishStravaConnection(code,state).then(()=>{window.history.replaceState({},'',`${window.location.pathname}#/profile`);setConnectionMessage('Strava connected. Your recent activities are ready to sync.');return loadConnection()}).catch(reason=>setConnectionMessage(reason instanceof Error?reason.message:'Strava could not connect.')).finally(()=>setConnectionBusy(false))}},[]);
  const connectionAction=async(action:'connect'|'sync'|'disconnect')=>{setConnectionBusy(true);setConnectionMessage('');try{if(action==='connect')await beginStravaConnection();if(action==='sync'){const result=await syncStravaActivities();setConnectionMessage(`${result.importedActivities||0} recent activities synced.`)}if(action==='disconnect'){await disconnectStrava();setConnectionMessage('Strava disconnected. Previously imported activity summaries remain in your account.')}await loadConnection()}catch(reason){setConnectionMessage(reason instanceof Error?reason.message:'The connection could not be updated.')}finally{setConnectionBusy(false)}};
  return <div className="stack-xl simple-profile">
    <section className="simple-profile-head"><div className="avatar xlarge">{initials}</div><div><span className="eyebrow">ATHLETE PROFILE</span><h2>{name}</h2><p>{/* Each half stays whole so the line never breaks straight after the separator. */}<span className="nowrap">{setup?.primaryFocus||'Hybrid'} training</span> <span className="nowrap">· {setup?.scheduleStyle||'Rolling cycle'}</span></p></div>{recovery.confidence!=='Low'&&<div className="profile-ready"><strong>{recovery.readiness}</strong><span>readiness</span></div>}<Link className="button secondary" to="/onboarding">Edit profile</Link></section>
    <nav className="profile-tabs">{([['profile','Profile'],['recovery','Recovery'],['connections','Connections'],['appearance','Appearance']] as const).map(([key,label])=><button className={view===key?'active':''} onClick={()=>setView(key)} key={key}>{label}</button>)}</nav>
    {view==='profile'&&<><section className="simple-profile-stats"><div><span>WORKOUTS</span><strong>{records.length}</strong></div><div><span>WEEKLY RUNNING</span><strong>{weeklyDistance} {distanceUnit}</strong></div><div><span>LONGEST RUN</span><strong>{longestDistance} {distanceUnit}</strong></div><div><span>ACTIVE GOALS</span><strong>{goals.length}</strong></div></section><section className="simple-settings-list"><Link to="/plan?view=split"><div><strong>Split</strong><span>Training and rest-day structure</span></div><b>›</b></Link><Link to="/exercises"><div><strong>Exercise library</strong><span>Browse every movement Forge knows</span></div><b>›</b></Link></section></>}
    {view==='recovery'&&<><section className="simple-recovery"><div><span className="eyebrow">SMARTWATCH RECOVERY</span><h3>{recovery.confidence==='Low'?'No smartwatch data synced':recovery.hardTrainingAllowed?'Recovery supports the plan':'Recovery safeguard active'}</h3><p>{recovery.confidence==='Low'?'Forge will ignore sleep, HRV, resting heart rate, and readiness until verified watch data is available. Your workout history and goals still guide training.':recovery.reasons.join(' · ')}</p></div><strong>{recovery.confidence==='Low'?'—':recovery.readiness}</strong></section>{recovery.confidence==='Low'?<section className="card wearable-empty"><div><span className="eyebrow">NO DEVICE SIGNAL</span><h3>Connect a smartwatch to use recovery</h3><p>Health data is read-only and automatically synced. There is no manual recovery entry, and Forge never fills missing health values with guesses.</p></div><button className="button secondary" onClick={()=>setView('connections')}>View connections</button></section>:<section className="simple-profile-stats"><div><span>SLEEP</span><strong>{Math.round(latest.sleepMinutes/6)/10} hr</strong></div><div><span>HRV</span><strong>{latest.hrvRmssd??'—'} ms</strong></div><div><span>RESTING HR</span><strong>{latest.restingHr??'—'}</strong></div><div><span>LAST SYNC</span><strong>{latest.provider}</strong></div></section>}</>}
    {view==='connections'&&<div className="connection-stack"><section className="simple-connections activity-connection"><header><div><span className="eyebrow">REAL ACTIVITY IMPORT</span><h3>Connect through Strava</h3><p>Import recorded runs, rides, rows, and other activities from watches that sync to Strava.</p></div><span className={activity?.connected?'connection-pill connected':'connection-pill'}>{activity?.connected?'Connected':activity?.configured===false?'Setup needed':'Not connected'}</span></header><article><div><strong>{activity?.athleteName||'Strava activity sync'}</strong><span>{activity?.connected?`${activity.importedActivities||0} activities stored${activity.lastSyncedAt?` · last sync ${new Date(activity.lastSyncedAt).toLocaleDateString()}`:''}`:'Workout data only — Strava does not supply complete sleep or HRV recovery data.'}</span></div><div className="connection-actions">{activity?.connected?<><button disabled={connectionBusy} onClick={()=>void connectionAction('sync')}>Sync now</button><button className="danger" disabled={connectionBusy} onClick={()=>void connectionAction('disconnect')}>Disconnect</button></>:<button className="button" disabled={connectionBusy||activity?.configured===false} onClick={()=>void connectionAction('connect')}>Connect Strava</button>}</div></article>{connectionMessage&&<p className="connection-message">{connectionMessage}</p>}{activity?.configured===false&&<p className="connection-message">The app side is built, but the Strava client credentials still need to be added in Supabase before this button can open authorization.</p>}</section><section className="simple-connections"><header><div><span className="eyebrow">RECOVERY DATA</span><h3>Direct smartwatch recovery</h3><p>Sleep, HRV, and resting heart rate require a native phone bridge or an approved device partnership.</p></div></header>{wearableConnections.map(item=><article key={item.provider}><div><strong>{item.provider}</strong><span>{item.capabilities.join(' · ')}</span></div><b>{item.provider===latest.provider?'Connected':item.status}</b></article>)}</section></div>}
    {view==='appearance'&&<AppearancePanel settings={settings} update={update} applyPreset={applyPreset} reset={reset}/>}
  </div>;
}

function AppearancePanel({settings,update,applyPreset,reset}:{settings:AppearanceSettings;update:(changes:Partial<AppearanceSettings>)=>void;applyPreset:(preset:Exclude<AppearanceSettings['preset'],'custom'>)=>void;reset:()=>void}){
  const presets:[Exclude<AppearanceSettings['preset'],'custom'>,string,string][]=[['forge','Forge','Signature contrast'],['focus','Focus','Quiet and compact'],['endurance','Endurance','Cool data palette'],['power','Power','Warm, high energy']];
  const accents:[AppearanceSettings['accent'],string][]=[['volt','Volt'],['ice','Ice'],['ocean','Ocean'],['ember','Ember'],['violet','Violet'],['gold','Gold']];
  return <section className="profile-customizer">
    <header><div><span className="eyebrow">APP APPEARANCE</span><h2>Make Forge yours</h2><p>Choose a starting style, then adjust only what matters. Changes apply everywhere and save on this device.</p></div><button className="text-button" onClick={reset}>Reset</button></header>
    <div className="customizer-presets">{presets.map(([key,name,copy])=><button className={settings.preset===key?'active':''} onClick={()=>applyPreset(key)} key={key}><i className={`preset-dot ${key}`}/><strong>{name}</strong><span>{copy}</span></button>)}</div>
    <div className="customizer-grid">
      <section><span className="eyebrow">COLOR</span><h3>Accent & charts</h3><div className="customizer-swatches">{accents.map(([key,label])=><button aria-label={`${label} accent`} title={label} className={`${key} ${settings.accent===key?'active':''}`} onClick={()=>update({accent:key})} key={key}><i/><span>{label}</span></button>)}</div><div className="mini-chart-preview"><i/><i/><i/><i/><i/><i/></div><small>Strength follows your accent. Endurance and body composition stay distinct.</small></section>
      <section><span className="eyebrow">BACKGROUND</span><h3>Surface</h3><div className="compact-choice-grid">{([['midnight','Midnight'],['graphite','Graphite'],['deep-navy','Deep navy'],['carbon','Carbon'],['light','Light']] as [AppearanceSettings['surface'],string][]).map(([key,label])=><button className={settings.surface===key?'active':''} onClick={()=>update({surface:key})} key={key}><i className={key}/><span>{label}</span></button>)}</div><label>Background detail<select value={settings.atmosphere} onChange={event=>update({atmosphere:event.target.value as AppearanceSettings['atmosphere']})}><option value="solid">Solid</option><option value="glow">Soft glow</option><option value="grid">Training grid</option></select></label></section>
      <section><span className="eyebrow">TYPE</span><h3>Typography</h3><div className="type-preview-list">{([['forge','Forge condensed','Bold and athletic'],['modern','Modern','Simple and familiar'],['technical','Technical','Precise and data-first']] as [AppearanceSettings['type'],string,string][]).map(([key,label,copy])=><button className={`${key} ${settings.type===key?'active':''}`} onClick={()=>update({type:key})} key={key}><strong>Ag</strong><span><b>{label}</b><small>{copy}</small></span></button>)}</div></section>
      <section><span className="eyebrow">LAYOUT</span><h3>Comfort</h3><label className="customizer-toggle"><span><b>Compact layout</b><small>Fit more training data on screen</small></span><input type="checkbox" checked={settings.compact} onChange={event=>update({compact:event.target.checked})}/></label><label className="customizer-toggle"><span><b>Interface motion</b><small>Keep subtle transitions and feedback</small></span><input type="checkbox" checked={settings.motion} onChange={event=>update({motion:event.target.checked})}/></label></section>
    </div>
  </section>
}
