import { useEffect,useMemo,useRef,useState } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { CardioPlanBuilder,cardioPlanSummary,type PlannedCardio } from '../components/CardioPlanBuilder';
import { useGoals } from '../features/goals/GoalsProvider';
import { useAdaptiveTraining } from '../features/training/AdaptiveTrainingProvider';
import { useProfileSetup } from '../features/profile/ProfileSetupProvider';
import { LongRangeTrainingPlan } from '../components/LongRangeTrainingPlan';
import { buildLongRangePlan } from '../lib/longRangePlanEngine';
import { useCoachingStrategy } from '../features/training/CoachingStrategyProvider';
import { exerciseCategory,useTrainingLibrary } from '../features/training/TrainingLibraryProvider';
import { requestForgeCoach } from '../features/training/coachService';
import { useAuth } from '../features/auth/AuthProvider';
import { saveTrainingSplit } from '../features/splits/splitService';
import { isDemoMode } from '../lib/env';

const muscles=['Chest','Back','Shoulders','Quads','Hamstrings','Glutes','Biceps','Triceps','Forearms','Abs'];
type CardioPolicy='none'|'forge'|'planned';
type DayType='strength'|'cardio'|'mixed'|'rest';
type TrainingDay={name:string;weekday:string;dayType:DayType;muscles:string[];exercises:string[];cardioPolicy:CardioPolicy;cardio:PlannedCardio[];recoveryStyle:'Full rest'|'Mobility'|'Active recovery';maxDuration:string;strengthDuration:string};
type SavedPlan={name:string;rhythm:'rolling'|'weekly';days:TrainingDay[];minWeeklyMileage?:number;maxWeeklyMileage?:number};
const planStorageKey='forge-training-plan-v1';
const loadSavedPlan=():SavedPlan|null=>{try{return JSON.parse(localStorage.getItem(planStorageKey)||'null')}catch{return null}};
const plannedCardioMinutes=(plan:PlannedCardio)=>{if(plan.structure==='Steady'||plan.structure==='Custom')return Math.max(0,Number(plan.duration)||0);if(plan.structure==='Intervals'){const work=/seconds?/i.test(plan.workUnit||'')?Number(plan.workDistance||0)/60:/minutes?/i.test(plan.workUnit||'')?Number(plan.workDistance||0):0;return Math.ceil(Math.max(0,Number(plan.repeats)||0)*work+Math.max(0,(Number(plan.repeats)||0)-1)*(Number(plan.rest)||0)/60)}if(plan.structure==='Circuit'){if(plan.circuitFormat==='For time'&&Number(plan.duration)>0)return Number(plan.duration);if(plan.circuitFormat==='AMRAP'||plan.circuitFormat==='EMOM')return Math.max(0,Number(plan.rounds)||0);const rounds=Math.max(0,Number(plan.rounds)||0);return Math.ceil(rounds*8+Math.max(0,rounds-1)*(Number(plan.roundRest)||0)/60)}return 0};
const durationForDay=(day:TrainingDay,cardio=day.cardio)=>{const cardioMinutes=cardio.reduce((total,plan)=>total+plannedCardioMinutes(plan),0);if(day.dayType==='strength')return day.strengthDuration;if(day.dayType==='cardio')return cardioMinutes?String(cardioMinutes):'';if(day.dayType==='mixed')return String((Number(day.strengthDuration)||0)+cardioMinutes);return ''};

export function TrainingPlanPage(){
  const {user}=useAuth();
  const {goals}=useGoals();const {profile}=useAdaptiveTraining();
  const {strategy}=useCoachingStrategy();
  const {exercises:libraryExercises,workouts:libraryWorkouts}=useTrainingLibrary();const strengthExercises=libraryExercises.filter(exercise=>exercise.enabled&&exercise.kind==='Strength'&&exerciseCategory(exercise)==='Strength');const exercises=strengthExercises.map(exercise=>exercise.name);const cardioWorkouts=libraryWorkouts.filter(workout=>Boolean(workout.plan));
  const {setup,saveSetup}=useProfileSetup();
  const savedPlan=useMemo(loadSavedPlan,[]);
  const [params,setParams]=useSearchParams();
  const requested=params.get('view');const tab:'split'|'program'=requested==='split'?'split':'program';
  const [rhythm,setRhythm]=useState<'rolling'|'weekly'>(savedPlan?.rhythm??(setup?.scheduleStyle==='Weekly schedule'?'weekly':'rolling'));
  const [splitName,setSplitName]=useState(savedPlan?.name||'My training split');
  const [minWeeklyMileage,setMinWeeklyMileage]=useState(savedPlan?.minWeeklyMileage??setup?.minWeeklyMileage??Math.max(0,Math.round(profile.weeklyMileage*.8)));
  const [maxWeeklyMileage,setMaxWeeklyMileage]=useState(savedPlan?.maxWeeklyMileage??setup?.maxWeeklyMileage??Math.max(0,Math.round(profile.weeklyMileage*1.2)));
  const [selectedDay,setSelectedDay]=useState(0);
  const [exerciseQuery,setExerciseQuery]=useState('');
  const [exerciseFilter,setExerciseFilter]=useState('');
  const [syncState,setSyncState]=useState<'saving'|'saved'|'local'|'error'>(isDemoMode?'local':'saving');
  const [reviewOpen,setReviewOpen]=useState(false);
  const [reviewQuestion,setReviewQuestion]=useState('');
  const [reviewAnswer,setReviewAnswer]=useState('');
  const [reviewLoading,setReviewLoading]=useState(false);
  const [cardioEditor,setCardioEditor]=useState<{dayIndex:number;cardioIndex:number|null}|null>(null);
  const [draggingDay,setDraggingDay]=useState<number|null>(null);
  const [dragOverDay,setDragOverDay]=useState<number|null>(null);
  const dayTouchStart=useRef<number|null>(null);
  const [days,setDays]=useState<TrainingDay[]>(()=>savedPlan?.days?.length?savedPlan.days.map(day=>({...day,strengthDuration:day.strengthDuration||day.maxDuration||'60'})):setup?.splitDays?.length?setup.splitDays.map((day,index)=>({name:day.name,weekday:['MON','TUE','WED','THU','FRI','SAT','SUN'][index%7],dayType:day.type.toLowerCase() as DayType,muscles:day.muscles||[],exercises:[],cardioPolicy:day.type==='Cardio'||day.type==='Mixed'?'forge':'none',cardio:[],recoveryStyle:'Full rest',strengthDuration:String(setup.strengthSessionMinutes),maxDuration:String(day.type==='Cardio'?setup.cardioSessionMinutes:day.type==='Mixed'?setup.combinedSessionMinutes:setup.strengthSessionMinutes)})):[{name:'Training Day 1',weekday:'MON',dayType:'strength',muscles:[],exercises:[],cardioPolicy:'none',cardio:[],recoveryStyle:'Full rest',strengthDuration:'60',maxDuration:'60'}]);
  const active=days[selectedDay];
  useEffect(()=>{const min=Math.max(0,minWeeklyMileage);const max=Math.max(min,maxWeeklyMileage);localStorage.setItem(planStorageKey,JSON.stringify({name:splitName,rhythm,days,minWeeklyMileage:min,maxWeeklyMileage:max} satisfies SavedPlan));if(setup)saveSetup({...setup,minWeeklyMileage:min,maxWeeklyMileage:max,scheduleStyle:rhythm==='weekly'?'Weekly schedule':'Rolling cycle',splitSource:'Custom',trainingDays:days.filter(day=>day.dayType!=='rest').length,splitDays:days.map(day=>({name:day.name,type:(day.dayType[0].toUpperCase()+day.dayType.slice(1)) as 'Strength'|'Cardio'|'Mixed'|'Rest',muscles:day.muscles}))})},[splitName,rhythm,days,minWeeklyMileage,maxWeeklyMileage]);
  useEffect(()=>{if(isDemoMode||!user){setSyncState('local');return}setSyncState('saving');const timer=window.setTimeout(()=>{void saveTrainingSplit(splitName,days.map((day,index)=>({position:index+1,name:day.name,muscleGroups:day.dayType==='strength'||day.dayType==='mixed'?day.muscles:[],goalLifts:day.dayType==='strength'||day.dayType==='mixed'?day.exercises:[],cardioTypes:day.dayType==='cardio'||day.dayType==='mixed'?(day.cardioPolicy==='planned'?(day.cardio.length?day.cardio.map(cardioPlanSummary):['Planned']):['Forge']):[]}))).then(()=>{setSyncState('saved');window.dispatchEvent(new Event('forge-training-cycle-changed'))}).catch(()=>setSyncState('error'))},1200);return()=>window.clearTimeout(timer)},[user,splitName,days]);
  const updateDay=(change:Partial<TrainingDay>)=>setDays(items=>items.map((day,index)=>{if(index!==selectedDay)return day;const next={...day,...change};next.maxDuration=durationForDay(next);return next}));
  const toggleMuscle=(muscle:string)=>updateDay({muscles:active.muscles.includes(muscle)?active.muscles.filter(item=>item!==muscle):[...active.muscles,muscle]});
  /* Scrolling one flat list of every strength movement on a phone is the slowest
     part of building a split, so the picker filters by muscle group first and
     the day's own selections sort to the top. */
  const pickerMuscles=muscles.filter(muscle=>strengthExercises.some(exercise=>exercise.muscles.includes(muscle)));
  const visibleExercises=strengthExercises.filter(exercise=>(!exerciseFilter||exercise.muscles.includes(exerciseFilter))&&exercise.name.toLowerCase().includes(exerciseQuery.trim().toLowerCase())).map(exercise=>exercise.name).sort((a,b)=>Number(active.exercises.includes(b))-Number(active.exercises.includes(a)));
  const musclesForExercises=(names:string[])=>Array.from(new Set(names.flatMap(name=>strengthExercises.find(item=>item.name===name)?.muscles.filter(muscle=>muscles.includes(muscle))||[])));
  const addExercise=(exercise:string)=>{if(!exercise||active.exercises.includes(exercise))return;const next=[...active.exercises,exercise];updateDay({exercises:next,muscles:musclesForExercises(next)})};
  const removeExercise=(exercise:string)=>{const next=active.exercises.filter(item=>item!==exercise);updateDay({exercises:next,muscles:next.length?musclesForExercises(next):active.muscles.filter(muscle=>!(strengthExercises.find(item=>item.name===exercise)?.muscles||[]).includes(muscle))})};
  const toggleExercise=(exercise:string)=>active.exercises.includes(exercise)?removeExercise(exercise):addExercise(exercise);
  const setPolicy=(policy:CardioPolicy)=>updateDay({cardioPolicy:policy});
  const setDayType=(dayType:DayType)=>updateDay({dayType,...(dayType==='strength'?{cardioPolicy:'none' as const,cardio:[]} : dayType==='cardio'?{muscles:[],exercises:[],cardioPolicy:'forge' as const}:dayType==='mixed'?{cardioPolicy:active.cardioPolicy==='none'?'forge' as const:active.cardioPolicy}:{muscles:[],exercises:[],cardioPolicy:'none' as const,cardio:[]})});
  const saveCardio=(plan:PlannedCardio)=>{if(!cardioEditor)return;setDays(items=>items.map((day,index)=>{if(index!==cardioEditor.dayIndex)return day;const cardio=cardioEditor.cardioIndex===null?[...day.cardio,plan]:day.cardio.map((entry,entryIndex)=>entryIndex===cardioEditor.cardioIndex?plan:entry);return{...day,cardio,maxDuration:durationForDay(day,cardio)}}));setCardioEditor(null)};
  const removeCardio=(cardioIndex:number)=>{const cardio=active.cardio.filter((_,index)=>index!==cardioIndex);updateDay({cardio,maxDuration:durationForDay(active,cardio)})};
  const attachLibraryCardio=(workoutId:string)=>{const workout=cardioWorkouts.find(item=>String(item.id)===workoutId);if(workout?.plan){const cardio=[...active.cardio,{...workout.plan,id:Date.now()}];updateDay({cardio,cardioPolicy:'planned',maxDuration:durationForDay(active,cardio)})}};
  const attachWorkoutToSplit=(workout:typeof libraryWorkouts[number],dayIndexes:number[])=>{if(!workout.plan)return;setDays(items=>items.map((day,index)=>{if(!dayIndexes.includes(index)||day.cardio.some(plan=>plan.id===workout.plan!.id))return day;const cardio=[...day.cardio,{...workout.plan!}];const dayType=day.dayType==='strength'||day.dayType==='rest'?'mixed':day.dayType;const next={...day,dayType,cardioPolicy:'planned' as const,cardio};return{...next,maxDuration:durationForDay(next,cardio)}}));setParams({view:'split'})};
  const reviewFindings=useMemo(()=>{const findings:string[]=[];const strengthDays=days.filter(day=>day.dayType==='strength'||day.dayType==='mixed');const cardioDays=days.filter(day=>day.cardioPolicy!=='none');const restDays=days.filter(day=>day.dayType==='rest');const emptyStrength=strengthDays.filter(day=>!day.exercises.length);if(emptyStrength.length)findings.push(`${emptyStrength.length} strength day${emptyStrength.length===1?' has':'s have'} no exercises selected.`);if(!cardioDays.length&&goals.some(goal=>goal.type==='Endurance'))findings.push('An endurance goal is active, but no split day currently permits cardio.');if(!restDays.length)findings.push('The cycle has no dedicated recovery day.');restDays.filter(day=>day.recoveryStyle==='Full rest'&&day.cardioPolicy!=='none').forEach(day=>findings.push(`${day.name} is marked Full rest but also permits cardio; confirm that is intentional.`));days.filter(day=>day.cardioPolicy==='planned'&&!day.cardio.length).forEach(day=>findings.push(`${day.name} expects planned cardio but has no attached option.`));return findings},[days,goals]);
  const openSplitReview=()=>{setReviewOpen(true);setTimeout(()=>document.getElementById('splitReviewPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),0)};
  const askSplitCoach=async()=>{const question=reviewQuestion.trim();if(!question)return;setReviewLoading(true);const fallback=reviewFindings.length?`The clearest issues are: ${reviewFindings.join(' ')} Keep the rolling strength order separate from calendar-week mileage and attach multiple cardio workouts as alternatives, not stacked sessions.`:`This split is structurally complete. Forge would preserve the rolling strength order, reconcile cardio by calendar week, and recommend only one attached cardio option per day.`;const response=await requestForgeCoach({question,scope:'plan',context:{rhythm,weeklyMileageBoundary:{minimum:minWeeklyMileage,maximum:maxWeeklyMileage},coachStrategy:strategy,days:days.map(day=>({name:day.name,type:day.dayType,muscles:day.muscles,exercises:day.exercises,cardioPolicy:day.cardioPolicy,cardioOptions:day.cardio.map(cardioPlanSummary),recoveryStyle:day.recoveryStyle,maxDuration:day.maxDuration})),findings:reviewFindings,goals:goals.map(goal=>({title:goal.title,type:goal.type,target:goal.target,date:goal.date}))}},fallback);setReviewAnswer(response.answer);setReviewLoading(false)};
  const addDay=()=>{const next:TrainingDay={name:`Training Day ${days.length+1}`,weekday:'MON',dayType:'strength',muscles:[],exercises:[],cardioPolicy:'none',cardio:[],recoveryStyle:'Full rest',strengthDuration:'60',maxDuration:'60'};setDays(items=>[...items,next]);setSelectedDay(days.length)};
  const removeDay=()=>{if(days.length===1)return;setDays(items=>items.filter((_,index)=>index!==selectedDay));setSelectedDay(Math.max(0,selectedDay-1))};
  const moveDay=(direction:-1|1)=>{const destination=selectedDay+direction;if(destination<0||destination>=days.length)return;setDays(items=>{const next=[...items];[next[selectedDay],next[destination]]=[next[destination],next[selectedDay]];return next});setSelectedDay(destination)};
  const reorderDay=(from:number,to:number)=>{if(from===to||from<0||to<0||from>=days.length||to>=days.length)return;setDays(items=>{const next=[...items];const [moved]=next.splice(from,1);next.splice(to,0,moved);return next});setSelectedDay(current=>{if(current===from)return to;if(from<current&&to>=current)return current-1;if(from>current&&to<=current)return current+1;return current})};
  const policyLabel=(day:TrainingDay)=>day.cardioPolicy==='none'?'No cardio':day.cardioPolicy==='forge'?'Forge decides':day.cardio.length?cardioPlanSummary(day.cardio[0]):'Planned cardio needed';
  const downloadPlan=()=>{const weeks=buildLongRangePlan(goals,profile,24);const lines=['FORGE ADAPTIVE TRAINING PLAN',`${splitName} · ${rhythm==='rolling'?'Rolling cycle':'Weekly schedule'}`,`${weeks.length}-week goal-driven progression`,'',`Starting running volume: ${profile.weeklyMileage} mi/week`,`Running availability: ${profile.runningDays} days`,`Active goals: ${goals.map(goal=>goal.title).join(' · ')||'Baseline development'}`,'','AUTHORIZED SPLIT',...days.flatMap((day,index)=>[`${index+1}. ${day.name}${rhythm==='weekly'?` · ${day.weekday}`:''} · ${day.dayType.toUpperCase()}`,`   Focus: ${day.muscles.join(', ')||'Not set'}`,`   Strength: ${day.exercises.join(', ')||'None'}`,`   Cardio: ${policyLabel(day)}`]),'','LONG-RANGE ROADMAP',...weeks.flatMap(week=>[`WEEK ${week.week} · ${week.start} · ${week.phase}`,`   Weekly volume: ${week.mileage} mi${week.change?` · ${week.change>0?'+':''}${week.change}%`:''}`,`   Strength priority: ${week.topSet}`,`   Quality session: ${week.quality}`,`   Long run: ${week.longRun}`,`   Easy / recovery: ${week.easy}`,`   Coaching rationale: ${week.why} ${week.adjustment}`,'']),'ADAPTATION POLICY','Forge may change upcoming volume, interval structure, target load, session timing, substitutions, recovery work, deloads, and taper timing.','Forge will not silently change goals, protected rest days, assigned muscle groups, injury constraints, completed history, or an athlete-authored workout.'];const blob=new Blob([lines.join('\n')],{type:'text/plain'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='forge-adaptive-training-plan.txt';link.click();URL.revokeObjectURL(url)};
  return <div className="stack-xl training-plan-page plan-studio">
    {cardioEditor&&<CardioPlanBuilder initial={cardioEditor.cardioIndex===null?undefined:days[cardioEditor.dayIndex].cardio[cardioEditor.cardioIndex]} onClose={()=>setCardioEditor(null)} onSave={saveCardio}/>}
    <nav className="plan-tabs"><button className={tab==='program'?'active':''} onClick={()=>setParams({view:'program'})}>Plan</button><button className={tab==='split'?'active':''} onClick={()=>setParams({view:'split'})}>Split</button></nav>
    {tab==='split'&&strategy.updatedAt&&<section className="coach-plan-banner"><div><span>AI COACH ADJUSTMENT ACTIVE</span><strong>{profile.weeklyMileage} mi/week · {strategy.loadBiasPercent>0?'+':''}{strategy.loadBiasPercent}% generated load · {strategy.splitEmphasis} emphasis</strong><small>{strategy.lastAdjustment||'Your confirmed coaching preferences now shape future Forge workouts.'}</small></div><button className="button ghost" onClick={openSplitReview}>Review split</button></section>}
    {tab==='split'&&reviewOpen&&<section className="card split-review-panel" id="splitReviewPanel"><header><div><span className="eyebrow">FORGE SPLIT REVIEW</span><h2>{reviewFindings.length?`${reviewFindings.length} item${reviewFindings.length===1?'':'s'} to review`:'Split structure looks complete'}</h2><p>Forge reviews the saved structure without rewriting completed history or applying changes automatically.</p></div><button className="text-button" onClick={()=>setReviewOpen(false)}>Close</button></header><div className="split-review-summary"><div><strong>{days.length}</strong><span>cycle days</span></div><div><strong>{days.filter(day=>day.dayType==='strength'||day.dayType==='mixed').length}</strong><span>strength days</span></div><div><strong>{days.filter(day=>day.cardioPolicy!=='none').length}</strong><span>cardio windows</span></div><div><strong>{days.reduce((sum,day)=>sum+day.cardio.length,0)}</strong><span>attached options</span></div></div><div className="split-review-findings">{reviewFindings.length?reviewFindings.map((finding,index)=><div key={finding}><span>{index+1}</span><p>{finding}</p></div>):<div className="clear"><span>✓</span><p>Every strength day has exercises, every cardio day has a source, and the cycle includes recovery.</p></div>}</div><div className="split-review-coach"><div><span className="eyebrow">ASK FORGE ABOUT THIS SPLIT</span><p>Ask about balance, recovery, exercise order, cardio scheduling, or a specific day.</p></div><div><textarea rows={2} value={reviewQuestion} onChange={event=>setReviewQuestion(event.target.value)} placeholder="Example: Is my lower-body work too close to the long run?"/><button className="button" disabled={reviewLoading||!reviewQuestion.trim()} onClick={askSplitCoach}>{reviewLoading?'Reviewing…':'Ask Forge'}</button></div>{reviewAnswer&&<article><span>FORGE REVIEW</span><p>{reviewAnswer}</p></article>}</div></section>}
    {tab==='program'&&(goals.length?<LongRangeTrainingPlan goals={goals} profile={{...profile,weeklyMileage:Math.max(minWeeklyMileage,Math.min(maxWeeklyMileage||Infinity,profile.weeklyMileage))}} rhythm={rhythm} splitDays={days.map(day=>({name:day.name,dayType:day.dayType,muscles:day.muscles,exercises:day.exercises,cardioPolicy:day.cardioPolicy,cardio:day.cardio}))}/>:<section className="card plan-empty"><h2>Add a goal to build your plan</h2><p>Your split tells Forge when you can train. A goal tells it what progression to build.</p><Link className="button" to="/goals">Create a goal</Link></section>)}
    {tab==='split'&&<>
      <section className="plan-studio-header desktop-plan-settings"><label>Plan name<input value={splitName} onChange={event=>setSplitName(event.target.value)}/></label><div><span className="field-caption">SCHEDULE STYLE</span><div className="segmented"><button className={rhythm==='rolling'?'active':''} onClick={()=>setRhythm('rolling')}>Rolling cycle</button><button className={rhythm==='weekly'?'active':''} onClick={()=>setRhythm('weekly')}>Weekly schedule</button></div></div><div className="mileage-boundary"><span className="field-caption">WEEKLY MILEAGE BOUNDARY</span><label>Minimum<input type="number" min="0" step="1" value={minWeeklyMileage} onChange={event=>setMinWeeklyMileage(Number(event.target.value))}/></label><label>Maximum<input type="number" min={minWeeklyMileage} step="1" value={maxWeeklyMileage} onChange={event=>setMaxWeeklyMileage(Number(event.target.value))}/></label></div><aside><span>{days.length}</span><small>training days</small></aside></section>
      <details className="card mobile-plan-settings"><summary><div><span className="eyebrow">PLAN SETTINGS</span><strong>{splitName}</strong></div><b>＋</b></summary><div><label>Plan name<input value={splitName} onChange={event=>setSplitName(event.target.value)}/></label><label>Schedule<select value={rhythm} onChange={event=>setRhythm(event.target.value as 'rolling'|'weekly')}><option value="rolling">Rolling cycle</option><option value="weekly">Weekly schedule</option></select></label><div className="field-grid"><label>Minimum weekly miles<input type="number" min="0" value={minWeeklyMileage} onChange={event=>setMinWeeklyMileage(Number(event.target.value))}/></label><label>Maximum weekly miles<input type="number" min={minWeeklyMileage} value={maxWeeklyMileage} onChange={event=>setMaxWeeklyMileage(Number(event.target.value))}/></label></div></div></details>
      <div className="plan-studio-layout">
        <aside className="plan-day-list"><div><span className="eyebrow">YOUR SPLIT</span><small className={`split-autosave ${syncState}`}>{syncState==='saving'?'Saving…':syncState==='error'?'Saved here · sync retry needed':syncState==='local'?'Saved on this device':'Saved to account'}</small></div>{days.map((day,index)=><button draggable className={`${selectedDay===index?'active ':''}${draggingDay===index?'dragging ':''}${dragOverDay===index&&draggingDay!==index?'drag-over':''}`.trim()} onClick={()=>setSelectedDay(index)} onDragStart={event=>{setDraggingDay(index);setDragOverDay(index);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(index))}} onDragEnter={()=>setDragOverDay(index)} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='move'}} onDrop={event=>{event.preventDefault();const stored=Number(event.dataTransfer.getData('text/plain'));const from=draggingDay??stored;if(Number.isInteger(from))reorderDay(from,index);setDraggingDay(null);setDragOverDay(null)}} onDragEnd={()=>{setDraggingDay(null);setDragOverDay(null)}} title="Drag to reorder this day" key={`${day.name}-${index}`}><span>{rhythm==='rolling'?String(index+1).padStart(2,'0'):day.weekday}</span><div><strong>{day.name}</strong><small>{day.dayType.toUpperCase()} · {day.dayType==='rest'?day.recoveryStyle:day.dayType==='cardio'?policyLabel(day):day.dayType==='mixed'?`${day.exercises.length} strength · ${policyLabel(day)}`:`${day.exercises.length} exercises`}</small></div><b className="day-drag-handle" aria-label="Drag to reorder">⋮⋮</b></button>)}<button className="add-plan-day" onClick={addDay}>＋ Add cycle day</button></aside>
        {active&&<section className={`day-editor-panel day-${active.dayType}`} onTouchStart={event=>{dayTouchStart.current=event.touches[0]?.clientX??null}} onTouchEnd={event=>{if(dayTouchStart.current===null)return;const distance=(event.changedTouches[0]?.clientX??dayTouchStart.current)-dayTouchStart.current;dayTouchStart.current=null;if(Math.abs(distance)<70)return;setSelectedDay(current=>Math.max(0,Math.min(days.length-1,current+(distance<0?1:-1))))}}><header><div><span className="eyebrow">{rhythm==='rolling'?`DAY ${selectedDay+1}`:active.weekday} · {active.dayType.toUpperCase()}</span><h2>{active.name}</h2><small className="mobile-swipe-hint">Swipe to move between days</small></div><div className="button-row day-order-actions"><button onClick={()=>moveDay(-1)} disabled={selectedDay===0}>↑ Up</button><button onClick={()=>moveDay(1)} disabled={selectedDay===days.length-1}>↓ Down</button><button className="danger" onClick={removeDay}>Remove</button></div></header><div className="day-editor-basics"><label>Day name<input value={active.name} onChange={event=>updateDay({name:event.target.value})}/></label>{rhythm==='weekly'&&<label>Weekday<select value={active.weekday} onChange={event=>updateDay({weekday:event.target.value})}>{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(day=><option key={day}>{day}</option>)}</select></label>}{(active.dayType==='strength'||active.dayType==='mixed')&&<label>Strength time<select value={active.strengthDuration||'60'} onChange={event=>updateDay({strengthDuration:event.target.value})}>{['30','45','60','75','90','120'].map(value=><option value={value} key={value}>{value} minutes</option>)}</select></label>}{(active.dayType==='cardio'||active.dayType==='mixed')&&<div className="derived-day-duration"><span>{active.dayType==='mixed'?'TOTAL PLANNED TIME':'PLANNED TIME'}</span><strong>{active.maxDuration?`${active.maxDuration} min`:active.cardioPolicy==='forge'?'Set by Forge':'Add a workout below'}</strong>{active.dayType==='mixed'&&<small>Strength + attached cardio</small>}</div>}</div>
          <section className="day-editor-section day-type-section"><div className="day-section-heading"><div><span>01</span><div><h3>Day type</h3><p>This controls what Forge is allowed to schedule here.</p></div></div></div><div className="day-type-options">{([['strength','Strength','Lifting and muscle work'],['cardio','Cardio','Running, conditioning, or circuits'],['mixed','Mixed','Strength and cardio together'],['rest','Rest','No training load']] as const).map(([type,label,copy])=><button className={active.dayType===type?'active':''} onClick={()=>setDayType(type)} key={type}><b>{label}</b><span>{copy}</span></button>)}</div></section>
          <section className="day-editor-section strength-config"><div className="day-section-heading"><div><span>02</span><div><h3>Training focus</h3><p>{active.exercises.length?'Derived from the exercises you selected below. Change the exercises to change the focus.':'Pick the muscle groups this day trains, or just choose exercises below and Forge will derive them.'}</p></div></div></div><div className={active.exercises.length?'muscle-picker compact-muscle-picker derived':'muscle-picker compact-muscle-picker'}>{muscles.map(muscle=><button className={active.muscles.includes(muscle)?'muscle-chip active':'muscle-chip'} onClick={()=>toggleMuscle(muscle)} disabled={active.exercises.length>0} key={muscle}>{muscle}</button>)}</div></section>
          <section className="day-editor-section strength-config exercise-selector-section"><div className="day-section-heading"><div><span>03</span><div><h3>Strength exercises</h3><p>Only movements in the Strength category appear here. HYROX and CrossFit stay in Cardio & circuits.</p></div></div><b>{active.exercises.length}</b></div><div className="selected-exercise-panel"><div className="selected-exercise-title"><span>SELECTED FOR THIS DAY</span><b>{active.exercises.length}</b></div>{active.exercises.length?<div className="selected-exercise-chips">{active.exercises.map((exercise,index)=><button type="button" onClick={()=>removeExercise(exercise)} key={exercise}><span>{index+1}</span>{exercise}<b aria-label={`Remove ${exercise}`}>×</b></button>)}</div>:<p>No exercises selected yet. Choose them from the Strength library below.</p>}</div><div className="exercise-multi-picker"><div className="exercise-picker-search"><input value={exerciseQuery} onChange={event=>setExerciseQuery(event.target.value)} placeholder="Search exercises…"/><span>{visibleExercises.length} shown</span></div><div className="exercise-picker-filters" role="group" aria-label="Filter exercises by muscle group"><button type="button" className={exerciseFilter?'':'active'} onClick={()=>setExerciseFilter('')}>All</button>{pickerMuscles.map(muscle=><button type="button" className={exerciseFilter===muscle?'active':''} onClick={()=>setExerciseFilter(exerciseFilter===muscle?'':muscle)} key={muscle}>{muscle}</button>)}</div><div className="exercise-picker-options">{visibleExercises.length?visibleExercises.map(exercise=>{const selected=active.exercises.includes(exercise);return <button type="button" className={selected?'selected':''} aria-pressed={selected} onClick={()=>toggleExercise(exercise)} key={exercise}><span className="exercise-check">{selected?'✓':''}</span><strong>{exercise}</strong></button>}):<p className="exercise-picker-empty">No exercises match that search.</p>}</div></div></section>
          <section className="day-editor-section cardio-policy-section"><div className="day-section-heading"><div><span>{active.dayType==='mixed'?'04':'02'}</span><div><h3>Cardio & circuits</h3><p>Let Forge choose the session when the day arrives, or attach one of your reusable workouts.</p></div></div></div><div className="cardio-policy-options"><button className={active.cardioPolicy==='forge'?'active':''} onClick={()=>setPolicy('forge')}><b>Forge chooses</b><span>Use goals, history, and recovery</span></button><button className={active.cardioPolicy==='planned'?'active':''} onClick={()=>setPolicy('planned')}><b>Attach workout</b><span>Use a saved cardio or circuit</span></button></div>{active.cardioPolicy==='forge'&&<div className="forge-cardio-rule"><span>FORGE WILL CHOOSE</span><p>The exact session and duration are set from your goals, recent work, mileage limits, and recovery.</p></div>}{active.cardioPolicy==='planned'&&<div className="planned-cardio-list">{active.cardio.map((plan,index)=><article key={plan.id}><div><span>{plan.structure.toUpperCase()}</span><strong>{cardioPlanSummary(plan)}</strong></div><div><button onClick={()=>setCardioEditor({dayIndex:selectedDay,cardioIndex:index})}>Edit</button><button onClick={()=>removeCardio(index)}>Remove</button></div></article>)}{cardioWorkouts.length>0&&<label className="attach-library-cardio">My cardio & circuits<select value="" onChange={event=>attachLibraryCardio(event.target.value)}><option value="">Choose a saved workout</option>{cardioWorkouts.map(workout=><option value={workout.id} key={workout.id}>{workout.name} · {workout.summary}</option>)}</select></label>}<button onClick={()=>setCardioEditor({dayIndex:selectedDay,cardioIndex:null})}>＋ Build a workout</button>{!active.cardio.length&&<small>Attach a saved workout or build one here.</small>}</div>}</section>
          <section className="day-editor-section recovery-config"><div className="day-section-heading"><div><span>02</span><div><h3>Recovery day</h3><p>Choose the recovery intent. No strength, cardio, or circuits will be scheduled.</p></div></div></div><div className="recovery-style-options">{(['Full rest','Mobility','Active recovery'] as const).map(style=><button className={active.recoveryStyle===style?'active':''} onClick={()=>updateDay({recoveryStyle:style})} key={style}><b>{style}</b><span>{style==='Full rest'?'No prescribed activity':style==='Mobility'?'Mobility or easy walking':'Low-intensity recovery movement'}</span></button>)}</div><div className="rest-boundary"><strong>RECOVERY PROTECTED</strong><span>This day cannot contain a strength workout, cardio session, or circuit.</span></div></section>
        </section>}
      </div>
    </>}
  </div>;
}
