import { useMemo,useState } from 'react';

export type CircuitStation={id:number;kind:'Cardio'|'Strength'|'Bodyweight'|'Rest';name:string;target:string;unit:string;load?:string;rest?:string};
export type PlannedCardio={id:number;activity:string;structure:'Steady'|'Intervals'|'Circuit'|'Custom';targetSource:'Goal generated'|'Manual plan';distance?:string;distanceUnit?:string;duration?:string;stationTime?:string;pace?:string;repeats?:string;intervalBasis?:'Distance'|'Time';workDistance?:string;workUnit?:string;rest?:string;recoveryType?:string;warmup?:string;cooldown?:string;rounds?:string;circuitFormat?:'Rounds'|'AMRAP'|'EMOM'|'For time';roundRest?:string;stationEntries?:CircuitStation[];customTarget?:string};

const activityUnits:Record<string,string>={Run:'miles',Bike:'miles',Rowing:'meters','Stair Climber':'floors',Elliptical:'minutes',Swimming:'yards',SkiErg:'meters',Circuit:'rounds'};
export const cardioActivities=Object.keys(activityUnits);
const stationDefaults:Record<CircuitStation['kind'],{name:string;unit:string}>={Cardio:{name:'Row',unit:'meters'},Strength:{name:'Kettlebell Swing',unit:'reps'},Bodyweight:{name:'Burpees',unit:'reps'},Rest:{name:'Rest',unit:'seconds'}};
const stationUnits:Record<CircuitStation['kind'],string[]>={Cardio:['meters','yards','miles','kilometers','calories','seconds','minutes'],Strength:['reps','seconds'],Bodyweight:['reps','seconds','meters'],Rest:['seconds','minutes']};
const distanceToMiles=(value:string,unit:string)=>{const distance=Number(value);if(!Number.isFinite(distance)||distance<=0)return 0;const normalized=unit.toLowerCase();if(normalized.startsWith('kilo'))return distance*.621371;if(normalized.startsWith('meter'))return distance/1609.344;if(normalized.startsWith('yard'))return distance/1760;return normalized.startsWith('mile')?distance:0};
const paceToMinutes=(value:string)=>{const match=value.trim().match(/^(\d{1,2}):(\d{2})(?:\s*\/?\s*mi)?$/i);if(match){const minutes=Number(match[1]),seconds=Number(match[2]);return seconds<60?minutes+seconds/60:0}const decimal=Number(value.replace(/\s*\/?\s*mi/i,''));return Number.isFinite(decimal)&&decimal>0?decimal:0};
const formatPace=(minutes:number)=>{const seconds=Math.round(minutes*60);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}/mi`};

export function cardioPlanSummary(plan:PlannedCardio){if(plan.structure==='Intervals')return `${plan.activity} · ${plan.repeats} × ${plan.workDistance} ${plan.workUnit} · ${plan.pace||'target effort'} · ${plan.rest}s recovery`;if(plan.structure==='Circuit')return plan.circuitFormat==='For time'?`For time · ${plan.rounds||'1'} rounds · ${plan.stationEntries?.length||0} stations · ${plan.duration||'—'} min target`:`${plan.circuitFormat||'Rounds'} · ${plan.rounds||'3'} ${plan.circuitFormat==='AMRAP'||plan.circuitFormat==='EMOM'?'min':'rounds'} · ${plan.stationEntries?.length||0} stations`;if(plan.structure==='Custom')return `${plan.activity} · ${plan.customTarget||'custom target'}`;return `${plan.activity}${plan.distance?` · ${plan.distance} ${plan.distanceUnit}`:''} · ${plan.duration||'—'} min${plan.pace?` · ${plan.pace}`:''}`}

export function CardioPlanBuilder({initial,onClose,onSave}:{initial?:PlannedCardio;onClose:()=>void;onSave:(plan:PlannedCardio)=>void}){
  const [activity,setActivity]=useState(initial?.activity||'Run');const [structure,setStructure]=useState<PlannedCardio['structure']>(initial?.structure||'Steady');const [targetSource,setTargetSource]=useState<PlannedCardio['targetSource']>(initial?.targetSource||'Goal generated');
  const [distance,setDistance]=useState(initial?.distance||'3');const [distanceUnit,setDistanceUnit]=useState(initial?.distanceUnit||activityUnits[initial?.activity||'Run']);const [duration,setDuration]=useState(initial?.duration||'30');const [pace,setPace]=useState(initial?.pace||'8:00/mi');
  const [calculationSource,setCalculationSource]=useState<'pace'|'duration'>('pace');
  const [repeats,setRepeats]=useState(initial?.repeats||'6');const [intervalBasis,setIntervalBasis]=useState<PlannedCardio['intervalBasis']>(initial?.intervalBasis||'Distance');const [workDistance,setWorkDistance]=useState(initial?.workDistance||'600');const [workUnit,setWorkUnit]=useState(initial?.workUnit||'meters');const [rest,setRest]=useState(initial?.rest||'120');const [recoveryType,setRecoveryType]=useState(initial?.recoveryType||'Rest');const [warmup,setWarmup]=useState(initial?.warmup||'1 mile');const [cooldown,setCooldown]=useState(initial?.cooldown||'1 mile');
  const [rounds,setRounds]=useState(initial?.rounds||'3');const [circuitFormat,setCircuitFormat]=useState<PlannedCardio['circuitFormat']>(initial?.circuitFormat||'Rounds');const [roundRest,setRoundRest]=useState(initial?.roundRest||'90');const [stations,setStations]=useState<CircuitStation[]>(initial?.stationEntries||[{id:1,kind:'Cardio',name:'Row',target:'250',unit:'meters',rest:'20'},{id:2,kind:'Strength',name:'Kettlebell Swing',target:'15',unit:'reps',load:'35 lb',rest:'20'},{id:3,kind:'Cardio',name:'Bike',target:'45',unit:'seconds',rest:'20'}]);const [customTarget,setCustomTarget]=useState(initial?.customTarget||'');
  const plan=useMemo<PlannedCardio>(()=>({id:initial?.id||Date.now(),activity,structure,targetSource,distance,distanceUnit,duration,pace,repeats,intervalBasis,workDistance,workUnit,rest,recoveryType,warmup,cooldown,rounds,circuitFormat,roundRest,stationEntries:stations,customTarget}),[initial?.id,activity,structure,targetSource,distance,distanceUnit,duration,pace,repeats,intervalBasis,workDistance,workUnit,rest,recoveryType,warmup,cooldown,rounds,circuitFormat,roundRest,stations,customTarget]);
  const updateStation=(id:number,change:Partial<CircuitStation>)=>setStations(items=>items.map(item=>item.id===id?{...item,...change}:item));const changeKind=(id:number,kind:CircuitStation['kind'])=>updateStation(id,{kind,...stationDefaults[kind],target:'',load:kind==='Strength'?'0 lb':undefined});const addStation=()=>setStations(items=>[...items,{id:Date.now(),kind:'Cardio',name:'Run',target:'200',unit:'meters',rest:'20'}]);const moveStation=(index:number,direction:-1|1)=>setStations(items=>{const target=index+direction;if(target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next});
  const syncFromPace=(nextDistance=distance,nextUnit=distanceUnit,nextPace=pace)=>{const miles=distanceToMiles(nextDistance,nextUnit),minutes=paceToMinutes(nextPace);if(activity==='Run'&&miles&&minutes)setDuration(String(Math.round(miles*minutes*10)/10))};
  const syncFromDuration=(nextDistance=distance,nextUnit=distanceUnit,nextDuration=duration)=>{const miles=distanceToMiles(nextDistance,nextUnit),minutes=Number(nextDuration);if(activity==='Run'&&miles&&Number.isFinite(minutes)&&minutes>0)setPace(formatPace(minutes/miles))};
  const changeDistance=(value:string)=>{setDistance(value);calculationSource==='pace'?syncFromPace(value):syncFromDuration(value)};
  const changeUnit=(value:string)=>{setDistanceUnit(value);calculationSource==='pace'?syncFromPace(distance,value):syncFromDuration(distance,value)};
  const changeDuration=(value:string)=>{setDuration(value);setCalculationSource('duration');syncFromDuration(distance,distanceUnit,value)};
  const changePace=(value:string)=>{setPace(value);setCalculationSource('pace');syncFromPace(distance,distanceUnit,value)};
  const changeActivity=(value:string)=>{setActivity(value);setDistanceUnit(activityUnits[value]||'minutes');if(value==='Circuit')setStructure('Circuit')};
  return <div className="cardio-plan-backdrop" role="dialog" aria-modal="true"><section className="cardio-plan-modal"><header><div><span className="eyebrow">CARDIO SESSION BUILDER</span><h2>{initial?'Edit planned cardio':'Plan cardio'}</h2><p>Build measurable work once. Planned targets and completed actuals remain separate.</p></div><button onClick={onClose}>×</button></header><div className="cardio-plan-source"><button className={targetSource==='Goal generated'?'active':''} onClick={()=>setTargetSource('Goal generated')}><b>Goal guided</b><span>Forge may adapt targets from the endurance goal.</span></button><button className={targetSource==='Manual plan'?'active':''} onClick={()=>setTargetSource('Manual plan')}><b>Manual plan</b><span>Keep these targets fixed.</span></button></div><div className="field-grid"><label>Activity<select value={activity} onChange={e=>changeActivity(e.target.value)}>{cardioActivities.map(item=><option key={item}>{item}</option>)}</select></label><label>Session type<select value={structure} onChange={e=>setStructure(e.target.value as PlannedCardio['structure'])}><option>Steady</option><option>Intervals</option><option>Circuit</option><option>Custom</option></select></label></div>
  {structure==='Steady'&&<div className="cardio-plan-fields"><div className="field-grid three"><label>Distance<input value={distance} onChange={e=>changeDistance(e.target.value)}/></label><label>Unit<select value={distanceUnit} onChange={e=>changeUnit(e.target.value)}>{['miles','kilometers','meters','yards','floors','calories'].map(unit=><option key={unit}>{unit}</option>)}</select></label><label>Duration (min)<input value={duration} onChange={e=>changeDuration(e.target.value)}/></label></div><label>Target pace or intensity<input value={pace} onChange={e=>changePace(e.target.value)} placeholder="8:00/mi, Zone 2, easy…"/>{activity==='Run'&&<small>For runs, enter duration or pace and Forge calculates the other.</small>}</label></div>}
  {structure==='Intervals'&&<div className="cardio-plan-fields"><div className="interval-basis"><button className={intervalBasis==='Distance'?'active':''} onClick={()=>{setIntervalBasis('Distance');if(['seconds','minutes'].includes(workUnit||''))setWorkUnit('meters')}}>Distance intervals</button><button className={intervalBasis==='Time'?'active':''} onClick={()=>{setIntervalBasis('Time');setWorkUnit('seconds')}}>Time intervals</button></div><div className="field-grid three"><label>Repetitions<input value={repeats} onChange={e=>setRepeats(e.target.value)}/></label><label>{intervalBasis==='Distance'?'Distance per rep':'Work time per rep'}<input value={workDistance} onChange={e=>setWorkDistance(e.target.value)}/></label><label>Unit<select value={workUnit} onChange={e=>setWorkUnit(e.target.value)}>{(intervalBasis==='Distance'?['meters','yards','miles','kilometers']:['seconds','minutes']).map(unit=><option key={unit}>{unit}</option>)}</select></label></div><div className="field-grid three"><label>Target pace / effort<input value={pace} onChange={e=>setPace(e.target.value)} placeholder="5K pace, hard, Zone 4…"/></label><label>Recovery<input value={rest} onChange={e=>setRest(e.target.value)}/></label><label>Recovery type<select value={recoveryType} onChange={e=>setRecoveryType(e.target.value)}><option>Rest</option><option>Walk</option><option>Easy movement</option></select></label></div><div className="field-grid"><label>Warm-up<input value={warmup} onChange={e=>setWarmup(e.target.value)}/></label><label>Cooldown<input value={cooldown} onChange={e=>setCooldown(e.target.value)}/></label></div></div>}
  {structure==='Circuit'&&<div className="cardio-plan-fields"><div className="field-grid three"><label>Format<select value={circuitFormat} onChange={e=>setCircuitFormat(e.target.value as PlannedCardio['circuitFormat'])}><option>Rounds</option><option>AMRAP</option><option>EMOM</option><option>For time</option></select></label><label>{circuitFormat==='AMRAP'||circuitFormat==='EMOM'?'Duration (min)':'Rounds'}<input value={rounds} onChange={e=>setRounds(e.target.value)}/></label><label>Rest between rounds (sec)<input value={roundRest} onChange={e=>setRoundRest(e.target.value)}/></label></div><div className="circuit-stations"><div className="circuit-station-head"><span>STATIONS</span><small>Each station stores its own measurable target.</small></div>{stations.map((station,index)=><article key={station.id}><div className="station-order"><b>{index+1}</b><button onClick={()=>moveStation(index,-1)} disabled={index===0}>↑</button><button onClick={()=>moveStation(index,1)} disabled={index===stations.length-1}>↓</button></div><div className="station-fields"><label>Type<select value={station.kind} onChange={e=>changeKind(station.id,e.target.value as CircuitStation['kind'])}><option>Cardio</option><option>Strength</option><option>Bodyweight</option><option>Rest</option></select></label><label>Station<input value={station.name} onChange={e=>updateStation(station.id,{name:e.target.value})}/></label><label>Target<input value={station.target} onChange={e=>updateStation(station.id,{target:e.target.value})}/></label><label>Unit<select value={station.unit} onChange={e=>updateStation(station.id,{unit:e.target.value})}>{stationUnits[station.kind].map(unit=><option key={unit}>{unit}</option>)}</select></label>{station.kind==='Strength'&&<label>Load<input value={station.load||''} onChange={e=>updateStation(station.id,{load:e.target.value})} placeholder="35 lb"/></label>}<label>Rest after (sec)<input value={station.rest||''} onChange={e=>updateStation(station.id,{rest:e.target.value})}/></label></div><button className="remove-station" onClick={()=>setStations(items=>items.filter(item=>item.id!==station.id))}>Remove</button></article>)}<button className="add-station" onClick={addStation}>＋ Add station</button></div></div>}
  {structure==='Custom'&&<div className="cardio-plan-fields"><label>Measurable planned target<textarea rows={4} value={customTarget} onChange={e=>setCustomTarget(e.target.value)}/></label></div>}
  <div className="cardio-plan-preview"><span>COLLAPSED PLAN PREVIEW</span><strong>{cardioPlanSummary(plan)}</strong><small>{targetSource==='Goal generated'?'Targets may adapt; the structure stays attached to this day.':'Manual targets remain fixed until edited.'}</small></div><footer><button className="button ghost" onClick={onClose}>Cancel</button><button className="button" onClick={()=>onSave(plan)}>Save cardio session</button></footer></section></div>}
