import { useMemo, useState } from 'react';
import { useWorkoutHistory } from '../features/training/WorkoutHistoryProvider';
import { calculateEstimatedOneRepMax } from '../lib/strength';
import { summarizeCardioDraft } from '../lib/cardioSession';
import { friends } from '../data/demo';

type Metric='strength'|'endurance';
type Point={label:string;value:number};
const sharedPreview:Record<string,{strength:Point[];endurance:Point[]}>= {
  adamlifts:{strength:[410,418,425,431,438,445].map((value,index)=>({label:`W${index+1}`,value})),endurance:[115,128,132,144,151,158].map((value,index)=>({label:`W${index+1}`,value}))},
  jordanmoves:{strength:[315,320,324,331,334,339].map((value,index)=>({label:`W${index+1}`,value})),endurance:[142,150,146,166,174,181].map((value,index)=>({label:`W${index+1}`,value}))},
  samstrength:{strength:[365,370,378,381,389,397].map((value,index)=>({label:`W${index+1}`,value})),endurance:[72,80,86,83,94,101].map((value,index)=>({label:`W${index+1}`,value}))},
};

export function FriendProgressComparison(){
  const {records}=useWorkoutHistory();const [open,setOpen]=useState(false);const [username,setUsername]=useState(friends[0].username);const [metric,setMetric]=useState<Metric>('strength');const friend=friends.find(item=>item.username===username)??friends[0];
  const userPoints=useMemo<Point[]>(()=>{if(metric==='strength'){const liftCounts=records.reduce<Record<string,number>>((all,record)=>record.lift?{...all,[record.lift]:(all[record.lift]||0)+1}:all,{});const lift=Object.entries(liftCounts).sort((a,b)=>b[1]-a[1])[0]?.[0];return records.filter(record=>record.lift===lift&&record.weight&&record.reps).sort((a,b)=>a.date.localeCompare(b.date)).slice(-6).map(record=>({label:new Date(`${record.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}),value:record.calculatedMax||calculateEstimatedOneRepMax(record.weight!,record.reps!)||record.weight!}))}return records.flatMap(record=>(record.cardioSessions||[]).map(session=>({date:record.date,minutes:summarizeCardioDraft(session).minutes}))).filter(item=>item.minutes>0).sort((a,b)=>a.date.localeCompare(b.date)).slice(-6).map(item=>({label:new Date(`${item.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}),value:item.minutes}))},[records,metric]);
  const friendPoints=sharedPreview[friend.username][metric];const width=760,height=280,left=52,right=18,top=20,bottom=36,plotWidth=width-left-right,plotHeight=height-top-bottom;const all=[...userPoints,...friendPoints];const minRaw=Math.min(...all.map(point=>point.value),0),maxRaw=Math.max(...all.map(point=>point.value),1),padding=Math.max(5,(maxRaw-minRaw)*.12),min=Math.max(0,minRaw-padding),max=maxRaw+padding,spread=Math.max(1,max-min);const plot=(points:Point[])=>points.map((point,index)=>({...point,x:points.length===1?left+plotWidth/2:left+index*plotWidth/(points.length-1),y:top+plotHeight-(point.value-min)/spread*plotHeight}));const yours=plot(userPoints),theirs=plot(friendPoints);const latest=(points:Point[])=>points.at(-1)?.value;const change=(points:Point[])=>points.length>1?points.at(-1)!.value-points[0].value:null;const unit=metric==='strength'?'lb':'min';
  return <section className={`friend-comparison ${open?'open':''}`}>
    <button className="friend-comparison-toggle" onClick={()=>setOpen(value=>!value)}><div><span className="eyebrow">FRIEND INSIGHTS</span><strong>Compare progress with a friend</strong><small>Same measurement, same scale, privacy-safe shared data</small></div><b>{open?'Close':'Compare →'}</b></button>
    {open&&<div className="card friend-comparison-body"><header><div><span className="eyebrow">YOU VS. {friend.name.toUpperCase()}</span><h2>{metric==='strength'?'Strength trend':'Endurance volume'}</h2></div><div className="friend-compare-controls"><select value={username} onChange={event=>setUsername(event.target.value)} aria-label="Friend to compare">{friends.map(item=><option value={item.username} key={item.username}>{item.name}</option>)}</select><div>{(['strength','endurance'] as Metric[]).map(value=><button className={metric===value?'active':''} onClick={()=>setMetric(value)} key={value}>{value}</button>)}</div></div></header>
      <div className="friend-chart-legend"><span><i className="you"/>You</span><span><i className="friend"/>{friend.name}</span></div>
      <div className="friend-comparison-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`You compared with ${friend.name}`}>{[0,1,2,3,4].map(index=>{const y=top+index*plotHeight/4;return <g className="chart-grid-line" key={index}><line x1={left} y1={y} x2={width-right} y2={y}/><text x={left-10} y={y+4} textAnchor="end">{Math.round((max-index*spread/4)*10)/10}</text></g>})}{yours.length>0&&<polyline points={yours.map(point=>`${point.x},${point.y}`).join(' ')} fill="none" stroke="var(--chart-strength)" strokeWidth="5"/>}<polyline points={theirs.map(point=>`${point.x},${point.y}`).join(' ')} fill="none" stroke={friend.accent} strokeWidth="5"/>{yours.map(point=><circle key={`you-${point.label}`} cx={point.x} cy={point.y} r="5" fill="var(--chart-strength)"/>)}{theirs.map(point=><circle key={`friend-${point.label}`} cx={point.x} cy={point.y} r="5" fill={friend.accent}/>)}</svg>{!yours.length&&<div className="friend-no-user-data">Log matching {metric} results to add your line.</div>}</div>
      <div className="friend-comparison-table"><div><span>METRIC</span><b>YOU</b><b>{friend.name.split(' ')[0].toUpperCase()}</b></div><div><span>Latest {metric==='strength'?'calculated max':'session'}</span><strong>{latest(userPoints)??'—'} {latest(userPoints)?unit:''}</strong><strong>{latest(friendPoints)} {unit}</strong></div><div><span>Change shown</span><strong>{change(userPoints)===null?'—':`${change(userPoints)!>0?'+':''}${change(userPoints)} ${unit}`}</strong><strong>{change(friendPoints)!>0?'+':''}{change(friendPoints)} {unit}</strong></div><div><span>Entries shared</span><strong>{userPoints.length}</strong><strong>{friendPoints.length}</strong></div></div>
      <footer><span>◉</span><p><b>Privacy stays explicit.</b> Only metrics both athletes allow are compared. Body weight, notes, recovery, and full workout details remain private by default.</p><small>Friend values are preview shared data until account syncing is connected.</small></footer>
    </div>}
  </section>;
}
