import { Link } from 'react-router-dom';
import type { CreatedGoal } from './GoalBuilder';
import { useAdaptiveTraining } from '../features/training/AdaptiveTrainingProvider';
import { useState } from 'react';
import { useWorkoutHistory } from '../features/training/WorkoutHistoryProvider';
import { calculateEstimatedOneRepMax } from '../lib/strength';

const domainCopy={
  strength:{type:'Strength',title:'Strength',metric:'Calculated max, tested 1RM, and muscle frequency',fallback:'Track comparable top sets and supporting muscle exposure.'},
  endurance:{type:'Endurance',title:'Endurance',metric:'Performance time, pace, distance, and training volume',fallback:'Track meaningful cardio efforts and endurance volume.'},
  body:{type:'Body Composition',title:'Body Composition',metric:'Weight, body fat, circumference, or lean mass',fallback:'Track a consistent body-composition measurement.'},
} as const;

export function InsightsOverview({goals,onOpen}:{goals:CreatedGoal[];onOpen:(view:'strength'|'endurance'|'body')=>void}){
  const {recovery}=useAdaptiveTraining();
  const {records}=useWorkoutHistory();
  if(!goals.length) return <section className="goal-insights-empty"><span className="eyebrow">NO ACTIVE GOALS</span><h2>Your insights need a destination</h2><p>Create a strength, endurance, or body-composition goal. Forge will keep the analytics structure stable and tailor the coaching inside it.</p><Link className="button" to="/goals">Create a goal</Link></section>;
  const hasStrength=goals.some(goal=>goal.type==='Strength');const hasEndurance=goals.some(goal=>goal.type==='Endurance');const hasBody=goals.some(goal=>goal.type==='Body Composition');
  const strengthRecords=records.filter(record=>record.weight&&record.reps).sort((a,b)=>a.date.localeCompare(b.date));const firstStrength=strengthRecords[0];const latestStrength=strengthRecords.at(-1);const strengthChange=firstStrength&&latestStrength?(calculateEstimatedOneRepMax(latestStrength.weight!,latestStrength.reps!)||0)-(calculateEstimatedOneRepMax(firstStrength.weight!,firstStrength.reps!)||0):null;
  const cardioSessions=records.reduce((sum,record)=>sum+(record.cardioSessions?.length||0),0);const bodyRecords=records.filter(record=>record.bodyWeight).sort((a,b)=>a.date.localeCompare(b.date));const bodyChange=bodyRecords.length>1?Number((bodyRecords.at(-1)!.bodyWeight!-bodyRecords[0].bodyWeight!).toFixed(1)):null;
  return <div className="coach-overview">
    <section className="coach-overview-brief"><div><span className="eyebrow">YOUR DATA</span><h2>{records.length?'Your completed work, summarized':'Log a workout to begin'}</h2><p>{records.length?'These signals come only from saved workouts and check-ins. Open an area for detail.':'Forge will not invent a trend before you have recorded results.'}</p></div><div><span>TODAY'S DECISION</span><strong>{recovery.hardTrainingAllowed?'Train as planned':'Reduce intensity'}</strong><small>{recovery.readiness}% readiness · {recovery.strengthFatigue.toLowerCase()} strength fatigue</small></div></section>
    <section className="coach-signal-grid">
      <button onClick={()=>onOpen('strength')}><span>STRENGTH RESPONSE</span><strong>{strengthChange===null?'—':`${strengthChange>0?'+':''}${strengthChange} lb`}</strong><p>{strengthRecords.length?`${strengthRecords.length} logged top sets. First-to-latest calculated-max change shown above.`:hasStrength?'Log a top set to establish the trend.':'Comparable top sets remain available as training context.'}</p><b>View strength →</b></button>
      <button onClick={()=>onOpen('endurance')}><span>ENDURANCE RESPONSE</span><strong>{cardioSessions}</strong><p>{cardioSessions?`${cardioSessions} structured cardio session${cardioSessions===1?'':'s'} logged. Work and recovery are evaluated separately.`:hasEndurance?'Log cardio to establish the trend.':'Completed cardio sessions will establish the trend.'}</p><b>View endurance →</b></button>
      <button onClick={()=>onOpen('body')}><span>BODY TREND</span><strong>{bodyChange===null?'—':`${bodyChange>0?'+':''}${bodyChange} lb`}</strong><p>{bodyRecords.length>1?'First-to-latest logged body-weight change.':hasBody?'Add another body-weight check-in to establish a trend.':'Body measurements remain optional training context.'}</p><b>View body trend →</b></button>
    </section>
    <section className="coach-next-action"><span>NEXT COACHING ACTION</span><p>Complete today’s prescribed work and log the actual result. Forge will use that performance—not the target—to adjust the next session.</p><Link to="/workout">Log workout →</Link></section>
  </div>;
}

export function BodyCompositionInsight({goal,rangeLabel}:{goal?:CreatedGoal;rangeLabel:string}){
  const {records}=useWorkoutHistory();
  const [activePoint,setActivePoint]=useState<number|null>(null);
  const [bodyMode,setBodyMode]=useState<'rolling'|'measurements'>('rolling');
  if(!goal) return <section className="goal-insights-empty"><span className="eyebrow">BODY COMPOSITION</span><h2>No body-composition goal set</h2><p>This area is available as a stable part of Insights, but it will not influence coaching until you choose a body-weight, body-fat, circumference, or lean-mass goal.</p><Link className="button" to="/goals">Add body-composition goal</Link></section>;
  const entries=records.filter(record=>record.bodyWeight).sort((a,b)=>a.date.localeCompare(b.date)).map(record=>({label:new Date(`${record.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}),value:record.bodyWeight!}));
  if(entries.length<2)return <section className="goal-insights-empty"><span className="eyebrow">BODY COMPOSITION · {rangeLabel.toUpperCase()}</span><h2>One more check-in creates the trend</h2><p>{entries.length?`Your first recorded body weight is ${entries[0].value} ${goal.unit}.`:'No body-weight check-ins are saved yet.'} Forge needs at least two comparable entries and will not substitute demo measurements.</p><Link className="button" to="/workout">Log a check-in</Link></section>;
  const displayedEntries=bodyMode==='rolling'?entries.map((entry,index)=>{const window=entries.slice(Math.max(0,index-2),index+1);return{...entry,value:Number((window.reduce((sum,item)=>sum+item.value,0)/window.length).toFixed(1))}}):entries;const plot={left:58,right:18,top:18,bottom:34,width:720,height:280};const target=Number.parseFloat(goal.target)||entries.at(-1)!.value;const rawValues=[...displayedEntries.map(entry=>entry.value),target];const rawMin=Math.min(...rawValues),rawMax=Math.max(...rawValues),padding=Math.max(2,(rawMax-rawMin)*.2);const min=Math.floor(rawMin-padding),max=Math.ceil(rawMax+padding),spread=Math.max(1,max-min);const plotWidth=plot.width-plot.left-plot.right;const plotHeight=plot.height-plot.top-plot.bottom;const points=displayedEntries.map((entry,index)=>({...entry,x:plot.left+index*(plotWidth/(displayedEntries.length-1)),y:plot.top+plotHeight-((entry.value-min)/spread)*plotHeight}));const yTicks=Array.from({length:5},(_,index)=>Number((max-index*spread/4).toFixed(1)));const focused=activePoint===null?null:points[activePoint];const current=entries[entries.length-1];const change=current.value-entries[0].value;const remaining=Math.abs(target-current.value);
  return <div className="strength-insights strength-progress-layout">
    <section className="card strength-chart progress-chart-card">
      <div className="strength-chart-controls"><div><span className="eyebrow">BODY COMPOSITION · {rangeLabel.toUpperCase()}</span><h3>Comparable measurements</h3></div><select className="compact-select" aria-label="Body composition metric" value={goal.metric||'Body Weight'}><option>{goal.metric||'Body Weight'}</option></select></div>
      <div className="performance-mode"><button className={bodyMode==='rolling'?'active':''} onClick={()=>setBodyMode('rolling')}>Rolling Average</button><button className={bodyMode==='measurements'?'active':''} onClick={()=>setBodyMode('measurements')}>Measurements</button></div>
      <div className="performance-line-chart" aria-label={`${goal.metric||'Body weight'} history`} onMouseLeave={()=>setActivePoint(null)}><svg viewBox={`0 0 ${plot.width} ${plot.height}`} role="img"><defs><linearGradient id="performanceArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".18"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs>{yTicks.map((tick,index)=>{const y=plot.top+index*(plotHeight/4);return <g className="chart-grid-line" key={tick}><line x1={plot.left} y1={y} x2={plot.width-plot.right} y2={y}/><text x={plot.left-12} y={y+4} textAnchor="end">{tick}</text></g>})}<line className="body-target-line" x1={plot.left} x2={plot.width-plot.right} y1={plot.top+plotHeight-((target-min)/(max-min))*plotHeight} y2={plot.top+plotHeight-((target-min)/(max-min))*plotHeight}/><polygon className="chart-area" points={`${points[0].x},${plot.top+plotHeight} ${points.map(point=>`${point.x},${point.y}`).join(' ')} ${points[points.length-1].x},${plot.top+plotHeight}`}/><polyline className="chart-line" points={points.map(point=>`${point.x},${point.y}`).join(' ')} fill="none"/>{points.map((point,index)=><g className={activePoint===index?'chart-point active':'chart-point'} key={point.label} onMouseEnter={()=>setActivePoint(index)} onFocus={()=>setActivePoint(index)} tabIndex={0} role="button" aria-label={`${point.label}: ${point.value} ${goal.unit}`}><circle className="point-hit" cx={point.x} cy={point.y} r="14"/><circle className="point-dot" cx={point.x} cy={point.y} r="5"/></g>)}{points.filter((_,index)=>index===0||index===3||index===5||index===7).map(point=><text className="chart-date" key={point.label} x={point.x} y={plot.height-8} textAnchor={point===points[0]?'start':point===points[points.length-1]?'end':'middle'}>{point.label}</text>)}</svg>{focused&&<div className="chart-tooltip" style={{left:`${(focused.x/plot.width)*100}%`,top:`${(focused.y/plot.height)*100}%`}}><span>{focused.label}</span><strong>{focused.value} {goal.unit}</strong><small>Rolling measurement</small></div>}</div>
      <details className="performance-data"><summary>View data <span>{displayedEntries.length} entries</span></summary><div className="performance-records">{displayedEntries.map(entry=><div key={entry.label}><span>{entry.label}</span><strong>{entry.value} {goal.unit}</strong><small>{bodyMode==='rolling'?'Rolling average':'Measured value'}</small></div>)}</div></details><p>Forge uses a rolling trend so one measurement never changes training guidance by itself.</p>
    </section>
    <section className="card performance-peak-card"><span className="eyebrow">LATEST IN RANGE</span><h3>{goal.metric||'Body Weight'}</h3><strong>{current.value} {goal.unit}</strong><p>{current.label} · {remaining} {goal.unit} to target</p><div><span>First to latest</span><b className={change>=0?'positive-change':'negative-change'}>{change>0?'+':''}{change} {goal.unit}</b></div></section>
  </div>;
}
