import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { useWorkoutHistory } from '../features/training/WorkoutHistoryProvider';
import { useProfileSetup } from '../features/profile/ProfileSetupProvider';
import { calculateEstimatedOneRepMax } from '../lib/strength';
import { summarizeCardioDraft } from '../lib/cardioSession';
import { friends } from '../data/demo';

type TimeRange='4w'|'3m'|'6m'|'1y'|'all';type Domain='strength'|'endurance'|'body';type Entry={date:string;label:string;value:number};type EnduranceMetric='duration'|'distance'|'pace'|'actual-mile'|'actual-5k'|'actual-10k'|'calc-mile'|'calc-5k'|'calc-10k';
const rangeDays:Record<TimeRange,number>={'4w':28,'3m':92,'6m':183,'1y':366,all:Infinity};const colors:Record<Domain,string>={strength:'var(--chart-strength)',endurance:'var(--chart-endurance)',body:'var(--chart-body)'};
const friendSeries:Record<string,Record<Domain,number[]>>={adamlifts:{strength:[410,418,425,431,438,445],endurance:[115,128,132,144,151,158],body:[202,201,200,199,198,197]},jordanmoves:{strength:[315,320,324,331,334,339],endurance:[142,150,146,166,174,181],body:[168,169,168,170,169,171]},samstrength:{strength:[365,370,378,381,389,397],endurance:[72,80,86,83,94,101],body:[184,185,186,185,187,188]}};
const runTargets:Partial<Record<EnduranceMetric,number>>={'actual-mile':1,'actual-5k':3.10686,'actual-10k':6.21371,'calc-mile':1,'calc-5k':3.10686,'calc-10k':6.21371};
const isRunTimeMetric=(metric:EnduranceMetric)=>metric.startsWith('actual-')||metric.startsWith('calc-');
const formatMinutes=(minutes:number)=>{const seconds=Math.max(0,Math.round(minutes*60));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`};
const toMiles=(distance:number,unit:unknown)=>{const value=String(unit??'miles').toLowerCase();if(value.startsWith('kilo')||value==='km')return distance*.621371;if(value.startsWith('meter'))return distance*.000621371;if(value.startsWith('yard'))return distance*.000568182;return distance};

export function ProgressOverviewChart({range,rangeLabel}:{range:TimeRange;rangeLabel:string}){
  const {records}=useWorkoutHistory();const {setup}=useProfileSetup();const weightUnit=setup?.units==='Metric'?'kg':'lb';const [domain,setDomain]=useState<Domain>('strength');const [lift,setLift]=useState('');const [activity,setActivity]=useState('');const [compareFriend,setCompareFriend]=useState('');const [strengthMetric,setStrengthMetric]=useState<'calculated'|'real'>('calculated');const [enduranceMetric,setEnduranceMetric]=useState<EnduranceMetric>('duration');const [activePoint,setActivePoint]=useState<{series:'you'|'friend';index:number}|null>(null);
  const completedStrength=records.flatMap(record=>record.topSets?.length?record.topSets.filter(set=>set.completed!==false&&set.weight>0&&set.reps>0).map(set=>({date:record.date,lift:set.lift,weight:set.weight,reps:set.reps,calculatedMax:set.calculatedMax})):(record.lift&&record.weight&&record.reps?[{date:record.date,lift:record.lift,weight:record.weight,reps:record.reps,calculatedMax:record.calculatedMax}]:[]));
  const lifts=[...new Set(completedStrength.map(result=>result.lift))],activities=[...new Set(records.flatMap(record=>(record.cardioSessions||[]).filter(session=>{const result=summarizeCardioDraft(session);return result.completed>0&&(result.minutes>0||result.distance>0||session.structure==='circuit')}).map(session=>session.activity)))];const effectiveLift=lifts.includes(lift)?lift:(lifts[0]||''),effectiveActivity=activities.includes(activity)?activity:(activities[0]||'');const friend=friends.find(item=>item.username===compareFriend);
  const entries=useMemo<Entry[]>(()=>{const cutoff=rangeDays[range]===Infinity?-Infinity:Date.now()-rangeDays[range]*86400000,inRange=(date:string)=>new Date(`${date}T12:00:00`).getTime()>=cutoff,label=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'});if(domain==='strength')return completedStrength.filter(result=>inRange(result.date)&&result.lift===effectiveLift&&(strengthMetric==='calculated'||result.reps===1)).map(result=>({date:result.date,label:label(result.date),value:strengthMetric==='real'?result.weight:result.calculatedMax||calculateEstimatedOneRepMax(result.weight,result.reps)||result.weight})).sort((a,b)=>a.date.localeCompare(b.date));if(domain==='endurance')return records.flatMap(record=>(record.cardioSessions||[]).filter(session=>session.activity===effectiveActivity).map(session=>{const result=summarizeCardioDraft(session),distanceMiles=toMiles(result.distance,session.prescription.distanceUnit);let value=0;if(enduranceMetric==='duration')value=result.minutes;else if(enduranceMetric==='distance')value=result.distance;else if(enduranceMetric==='pace')value=distanceMiles>0?result.minutes/distanceMiles:0;else{const targetMiles=runTargets[enduranceMetric];const continuousRun=session.activity==='Run'&&(session.structure==='steady'||session.structure==='custom');if(!continuousRun||!targetMiles||!result.minutes||!distanceMiles)return{date:record.date,label:label(record.date),value:0};if(enduranceMetric.startsWith('actual-')){const tolerance=Math.max(.03,targetMiles*.01);value=Math.abs(distanceMiles-targetMiles)<=tolerance?result.minutes:0}else value=result.minutes*Math.pow(targetMiles/distanceMiles,1.06)}return{date:record.date,label:label(record.date),value:Number(value.toFixed(3))}})).filter(entry=>inRange(entry.date)&&entry.value>0).sort((a,b)=>a.date.localeCompare(b.date));return records.filter(record=>inRange(record.date)&&record.bodyWeight).map(record=>({date:record.date,label:label(record.date),value:record.bodyWeight!})).sort((a,b)=>a.date.localeCompare(b.date))},[records,completedStrength,range,domain,effectiveLift,effectiveActivity,strengthMetric,enduranceMetric]);
  const friendEntries:Entry[]=friend?friendSeries[friend.username][domain].map((raw,index)=>{let value=raw;if(domain==='strength'||domain==='body')value=weightUnit==='kg'?raw*.453592:raw;else if(enduranceMetric==='distance')value=raw/10;else if(enduranceMetric==='pace')value=9.8-index*.12;else if(isRunTimeMetric(enduranceMetric)){const target=runTargets[enduranceMetric]||3.10686;value=(8.9-index*.08)*target}else value=raw;return{date:`friend-${index}`,label:`W${index+1}`,value:Number(value.toFixed(3))}}):[];const width=760,height=270,left=54,right=18,top=20,bottom=34,plotWidth=width-left-right,plotHeight=height-top-bottom,values=[...entries,...friendEntries].map(item=>item.value),rawMin=values.length?Math.min(...values):0,rawMax=values.length?Math.max(...values):1,padding=Math.max(domain==='body'?1:isRunTimeMetric(enduranceMetric)?0.25:5,(rawMax-rawMin)*.15),min=rawMin-padding,max=rawMax+padding,spread=Math.max(.1,max-min);const plot=(items:Entry[])=>items.map((item,index)=>({...item,x:items.length===1?left+plotWidth/2:left+index*plotWidth/(items.length-1),y:top+plotHeight-(item.value-min)/spread*plotHeight})),points=plot(entries),friendPoints=plot(friendEntries),unit=domain==='strength'?weightUnit:domain==='endurance'?(enduranceMetric==='duration'?'min':enduranceMetric==='distance'?'distance':enduranceMetric==='pace'?'min/mi':isRunTimeMetric(enduranceMetric)?'time':''):weightUnit;
  const dateLabelIndexes=new Set(points.length<=4?points.map((_,index)=>index):Array.from({length:4},(_,index)=>Math.round(index*(points.length-1)/3)));
  const changeOf=(items:Entry[])=>items.length>1?Number((items.at(-1)!.value-items[0].value).toFixed(3)):null;const userChange=changeOf(entries),friendChange=changeOf(friendEntries),lowerIsBetter=domain==='endurance'&&(enduranceMetric==='pace'||isRunTimeMetric(enduranceMetric));const changeText=(value:number|null)=>value===null?'Not enough data':isRunTimeMetric(enduranceMetric)||domain==='endurance'&&enduranceMetric==='pace'?`${value>0?'+':'−'}${formatMinutes(Math.abs(value))}`:`${value>0?'+':''}${value} ${unit}`;const changeClass=(value:number|null)=>value===null||domain==='body'?'neutral':(lowerIsBetter?value<=0:value>=0)?'up':'down';
  const focused=activePoint?(activePoint.series==='you'?points[activePoint.index]:friendPoints[activePoint.index]):null;const focusedName=activePoint?.series==='friend'?(friend?.name||'Friend'):'You';const displayValue=(value:number)=>domain==='endurance'&&(enduranceMetric==='pace'||isRunTimeMetric(enduranceMetric))?formatMinutes(value):`${Math.round(value*10)/10}${unit?` ${unit}`:''}`;const metricLabel=domain==='strength'?(strengthMetric==='real'?'Real 1RM':'Calculated max'):domain==='body'?'Body weight':enduranceMetric==='duration'?'Duration':enduranceMetric==='distance'?'Distance':enduranceMetric==='pace'?'Average pace':enduranceMetric.replace('-', ' ').toUpperCase();
  return <section className={`card overview-progress-chart domain-${domain}`} style={{'--domain-color':colors[domain]} as CSSProperties}>
    <header><span className="eyebrow">ALL PROGRESS · {rangeLabel.toUpperCase()}</span><div className="progress-domain-filter">{(['strength','endurance','body'] as Domain[]).map(value=><button className={domain===value?'active':''} onClick={()=>setDomain(value)} key={value}><i/>{value==='body'?'Body comp':value}</button>)}</div></header>
    <div className="overview-chart-controls"><label>Measurement<select value={domain==='strength'?effectiveLift:domain==='endurance'?effectiveActivity:'Body weight'} onChange={event=>domain==='strength'?setLift(event.target.value):domain==='endurance'&&setActivity(event.target.value)} disabled={domain==='body'}>{domain==='strength'&&<>{!lifts.length&&<option>No strength data</option>}{lifts.map(value=><option key={value}>{value}</option>)}</>}{domain==='endurance'&&<>{!activities.length&&<option>No endurance data</option>}{activities.map(value=><option key={value}>{value}</option>)}</>}{domain==='body'&&<option>Body weight</option>}</select></label><label>Compare<select value={compareFriend} onChange={event=>setCompareFriend(event.target.value)}><option value="">Just me</option>{friends.map(item=><option value={item.username} key={item.username}>{item.name}</option>)}</select><small>{domain==='body'?'Compare only with a friend who shares weight':'Optional friend overlay'}</small></label><label>Metric{domain==='strength'?<select value={strengthMetric} onChange={event=>setStrengthMetric(event.target.value as typeof strengthMetric)}><option value="calculated">Calculated max</option><option value="real">Real 1RM</option></select>:domain==='endurance'?<select value={enduranceMetric} onChange={event=>setEnduranceMetric(event.target.value as typeof enduranceMetric)}><option value="duration">Completed duration</option><option value="distance">Completed distance</option><option value="pace">Average pace</option>{effectiveActivity==='Run'&&<><option value="actual-mile">1-mile time · actual</option><option value="calc-mile">1-mile time · calculated</option><option value="actual-5k">5K time · actual</option><option value="calc-5k">5K time · calculated</option><option value="actual-10k">10K time · actual</option><option value="calc-10k">10K time · calculated</option></>}</select>:<select disabled><option>Logged body weight</option></select>}<small>{domain==='strength'&&strengthMetric==='real'?'Logged one-rep sets only':domain==='endurance'&&isRunTimeMetric(enduranceMetric)?(enduranceMetric.startsWith('actual-')?'Exact-distance continuous runs only':'Equivalent time from continuous-run distance and duration'):unit}</small></label></div>
    {friend&&<div className="friend-chart-legend inline"><span><i className="you"/>You</span><span><i style={{background:friend.accent}}/>{friend.name}</span></div>}
    <div className="chart-change-strip"><div><span>YOU · FIRST TO LATEST</span><strong className={changeClass(userChange)}>{userChange!==null&&(userChange>=0?'↑ ':'↓ ')}{changeText(userChange)}</strong></div>{friend&&<div><span>{friend.name.toUpperCase()} · FIRST TO LATEST</span><strong className={changeClass(friendChange)}>{friendChange!==null&&(friendChange>=0?'↑ ':'↓ ')}{changeText(friendChange)}</strong></div>}</div>
    {points.length||friendPoints.length?<div className="overview-progress-plot" onMouseLeave={()=>setActivePoint(null)}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${domain} progress chart`}>{[0,1,2,3,4].map(index=>{const y=top+index*plotHeight/4,tick=max-index*spread/4;return <g className="chart-grid-line" key={index}><line x1={left} y1={y} x2={width-right} y2={y}/><text x={left-10} y={y+4} textAnchor="end">{domain==='endurance'&&(enduranceMetric==='pace'||isRunTimeMetric(enduranceMetric))?formatMinutes(tick):Math.round(tick*10)/10}</text></g>})}{points.length>0&&<polyline points={points.map(point=>`${point.x},${point.y}`).join(' ')} fill="none" stroke="var(--domain-color)" strokeWidth="5"/>}{friend&&friendPoints.length>0&&<polyline points={friendPoints.map(point=>`${point.x},${point.y}`).join(' ')} fill="none" stroke={friend.accent} strokeWidth="5"/>}{points.map((point,index)=><g className="overview-chart-point" key={`${point.date}-${point.value}`} tabIndex={0} role="button" aria-label={`${point.label}: ${displayValue(point.value)}`} onMouseEnter={()=>setActivePoint({series:'you',index})} onFocus={()=>setActivePoint({series:'you',index})}><circle className="overview-point-hit" cx={point.x} cy={point.y} r="15"/><circle className="overview-point-dot" cx={point.x} cy={point.y} r="5" fill="var(--domain-color)"/>{dateLabelIndexes.has(index)&&<text className="chart-date" x={point.x} y={height-8} textAnchor={index===0?'start':index===points.length-1?'end':'middle'}>{point.label}</text>}</g>)}{friend&&friendPoints.map((point,index)=><g className="overview-chart-point" key={point.date} tabIndex={0} role="button" aria-label={`${friend.name}, ${point.label}: ${displayValue(point.value)}`} onMouseEnter={()=>setActivePoint({series:'friend',index})} onFocus={()=>setActivePoint({series:'friend',index})}><circle className="overview-point-hit" cx={point.x} cy={point.y} r="15"/><circle className="overview-point-dot" cx={point.x} cy={point.y} r="5" fill={friend.accent}/></g>)}</svg>{focused&&<div className="overview-chart-tooltip" style={{left:`${focused.x/width*100}%`,top:`${focused.y/height*100}%`}}><span>{focusedName} · {focused.label}</span><strong>{displayValue(focused.value)}</strong><small>{metricLabel}</small></div>}{!points.length&&friend&&<div className="friend-no-user-data">Log matching {domain} results to add your line.</div>}</div>:<div className="performance-empty">No comparable {domain==='body'?'body-composition':domain} entries in this range yet.</div>}
    {friend&&<small className="inline-comparison-note">Friend values are preview shared data. Weight comparison requires explicit sharing when accounts are connected.</small>}
  </section>;
}
